--- 
title: "Spatial Modelling for Data Scientists"
author: "Francisco Rowe & Dani Arribas-Bel"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: gdsl-ul/san
description: "Teaching resources for a course on Spatial Modeling using R."
---

# Spatial Modelling for Data Scientists

Welcome to Spatial Modeling for Data Scientists (*ENVS453*), a course taught by Dr. Francisco Rowe and Dr. Dani Arribas-Bel in the Second Semester of 2020/21.

A compilation of this course is hosted as a GitHub repository that you can access:

* As a [download](https://github.com/GDSL-UL/san/archive/master.zip) of a `.zip` file that contains all the materials.
* As an [html website](https://gdsl-ul.github.io/san/).
* As a [pdf document](https://gdsl-ul.github.io/san/spatial_analysis_notes.pdf)
* As a [GitHub repository](https://github.com/GDSL-UL/san).

## Contact

> Francisco Rowe - `F.Rowe-Gonzalez [at] liverpool.ac.uk`   
Senior Lecturer in Quantitative Human Geography   
Office 507, Roxby Building,  
University of Liverpool - 74 Bedford St S,  
Liverpool, L69 7ZT,  
United Kingdom.

> Dani Arribas-Bel - `D.Arribas-Bel [at] liverpool.ac.uk`  
Senior Lecturer in Geographic Data Science  
Office 508, Roxby Building,  
University of Liverpool - 74 Bedford St S,  
Liverpool, L69 7ZT,  
United Kingdom.
