<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 9 Geographically Weighted Regression | Spatial Modelling for Data Scientists</title>
  <meta name="description" content="This course will teach you how to analyse and model spatial data using R." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 9 Geographically Weighted Regression | Spatial Modelling for Data Scientists" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This course will teach you how to analyse and model spatial data using R." />
  <meta name="github-repo" content="gdsl-ul/san" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 9 Geographically Weighted Regression | Spatial Modelling for Data Scientists" />
  
  <meta name="twitter:description" content="This course will teach you how to analyse and model spatial data using R." />
  

<meta name="author" content="Francisco Rowe and Dani Arribas-Bel" />


<meta name="date" content="2021-03-04" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="mlm2.html"/>
<link rel="next" href="sta.html"/>
<script src="libs/header-attrs-2.7/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Spatial Modelling for Data Scientists</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#contact"><i class="fa fa-check"></i>Contact</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="overview.html"><a href="overview.html"><i class="fa fa-check"></i><b>1</b> Overview</a>
<ul>
<li class="chapter" data-level="1.1" data-path="overview.html"><a href="overview.html#aims"><i class="fa fa-check"></i><b>1.1</b> Aims</a></li>
<li class="chapter" data-level="1.2" data-path="overview.html"><a href="overview.html#learning-outcomes"><i class="fa fa-check"></i><b>1.2</b> Learning Outcomes</a></li>
<li class="chapter" data-level="1.3" data-path="overview.html"><a href="overview.html#feedback"><i class="fa fa-check"></i><b>1.3</b> Feedback</a></li>
<li class="chapter" data-level="1.4" data-path="overview.html"><a href="overview.html#computational-environment"><i class="fa fa-check"></i><b>1.4</b> Computational Environment</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="overview.html"><a href="overview.html#dependency-list"><i class="fa fa-check"></i><b>1.4.1</b> Dependency list</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="overview.html"><a href="overview.html#assessment"><i class="fa fa-check"></i><b>1.5</b> Assessment</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="overview.html"><a href="overview.html#format-requirements"><i class="fa fa-check"></i><b>1.5.1</b> Format Requirements</a></li>
<li class="chapter" data-level="1.5.2" data-path="overview.html"><a href="overview.html#marking-criteria"><i class="fa fa-check"></i><b>1.5.2</b> Marking criteria</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="spatial-data.html"><a href="spatial-data.html"><i class="fa fa-check"></i><b>2</b> Spatial Data</a>
<ul>
<li class="chapter" data-level="2.1" data-path="spatial-data.html"><a href="spatial-data.html#spatial-data-types"><i class="fa fa-check"></i><b>2.1</b> Spatial Data types</a></li>
<li class="chapter" data-level="2.2" data-path="spatial-data.html"><a href="spatial-data.html#hierarchical-structure-of-data"><i class="fa fa-check"></i><b>2.2</b> Hierarchical Structure of Data</a></li>
<li class="chapter" data-level="2.3" data-path="spatial-data.html"><a href="spatial-data.html#key-challenges"><i class="fa fa-check"></i><b>2.3</b> Key Challenges</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="spatial-data.html"><a href="spatial-data.html#modifible-area-unit-problem-maup"><i class="fa fa-check"></i><b>2.3.1</b> Modifible Area Unit Problem (MAUP)</a></li>
<li class="chapter" data-level="2.3.2" data-path="spatial-data.html"><a href="spatial-data.html#ecological-fallacy"><i class="fa fa-check"></i><b>2.3.2</b> Ecological Fallacy</a></li>
<li class="chapter" data-level="2.3.3" data-path="spatial-data.html"><a href="spatial-data.html#spatial-dependence"><i class="fa fa-check"></i><b>2.3.3</b> Spatial Dependence</a></li>
<li class="chapter" data-level="2.3.4" data-path="spatial-data.html"><a href="spatial-data.html#spatial-heterogeneity"><i class="fa fa-check"></i><b>2.3.4</b> Spatial Heterogeneity</a></li>
<li class="chapter" data-level="2.3.5" data-path="spatial-data.html"><a href="spatial-data.html#spatial-nonstationarity"><i class="fa fa-check"></i><b>2.3.5</b> Spatial nonstationarity</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-wrangling.html"><a href="data-wrangling.html"><i class="fa fa-check"></i><b>3</b> Data Wrangling</a>
<ul>
<li class="chapter" data-level="3.1" data-path="data-wrangling.html"><a href="data-wrangling.html#dependencies"><i class="fa fa-check"></i><b>3.1</b> Dependencies</a></li>
<li class="chapter" data-level="3.2" data-path="data-wrangling.html"><a href="data-wrangling.html#introducing-r"><i class="fa fa-check"></i><b>3.2</b> Introducing R</a></li>
<li class="chapter" data-level="3.3" data-path="data-wrangling.html"><a href="data-wrangling.html#setting-the-working-directory"><i class="fa fa-check"></i><b>3.3</b> Setting the working directory</a></li>
<li class="chapter" data-level="3.4" data-path="data-wrangling.html"><a href="data-wrangling.html#r-scripts-and-notebooks"><i class="fa fa-check"></i><b>3.4</b> R Scripts and Notebooks</a></li>
<li class="chapter" data-level="3.5" data-path="data-wrangling.html"><a href="data-wrangling.html#getting-help"><i class="fa fa-check"></i><b>3.5</b> Getting Help</a></li>
<li class="chapter" data-level="3.6" data-path="data-wrangling.html"><a href="data-wrangling.html#variables-and-objects"><i class="fa fa-check"></i><b>3.6</b> Variables and objects</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="data-wrangling.html"><a href="data-wrangling.html#basic-data-types"><i class="fa fa-check"></i><b>3.6.1</b> Basic Data Types</a></li>
<li class="chapter" data-level="3.6.2" data-path="data-wrangling.html"><a href="data-wrangling.html#random-variables"><i class="fa fa-check"></i><b>3.6.2</b> Random Variables</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="data-wrangling.html"><a href="data-wrangling.html#data-frames"><i class="fa fa-check"></i><b>3.7</b> Data Frames</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="data-wrangling.html"><a href="data-wrangling.html#creating-a-data-frame"><i class="fa fa-check"></i><b>3.7.1</b> Creating A Data Frame</a></li>
<li class="chapter" data-level="3.7.2" data-path="data-wrangling.html"><a href="data-wrangling.html#referencing-data-frames"><i class="fa fa-check"></i><b>3.7.2</b> Referencing Data Frames</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="data-wrangling.html"><a href="data-wrangling.html#sec_readdata"><i class="fa fa-check"></i><b>3.8</b> Read Data</a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="data-wrangling.html"><a href="data-wrangling.html#quickly-inspect-the-data"><i class="fa fa-check"></i><b>3.8.1</b> Quickly inspect the data</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="data-wrangling.html"><a href="data-wrangling.html#manipulation-data"><i class="fa fa-check"></i><b>3.9</b> Manipulation Data</a>
<ul>
<li class="chapter" data-level="3.9.1" data-path="data-wrangling.html"><a href="data-wrangling.html#adding-new-variables"><i class="fa fa-check"></i><b>3.9.1</b> Adding New Variables</a></li>
<li class="chapter" data-level="3.9.2" data-path="data-wrangling.html"><a href="data-wrangling.html#selecting-variables"><i class="fa fa-check"></i><b>3.9.2</b> Selecting Variables</a></li>
<li class="chapter" data-level="3.9.3" data-path="data-wrangling.html"><a href="data-wrangling.html#filtering-data"><i class="fa fa-check"></i><b>3.9.3</b> Filtering Data</a></li>
<li class="chapter" data-level="3.9.4" data-path="data-wrangling.html"><a href="data-wrangling.html#joining-data-drames"><i class="fa fa-check"></i><b>3.9.4</b> Joining Data Drames</a></li>
<li class="chapter" data-level="3.9.5" data-path="data-wrangling.html"><a href="data-wrangling.html#saving-data"><i class="fa fa-check"></i><b>3.9.5</b> Saving Data</a></li>
</ul></li>
<li class="chapter" data-level="3.10" data-path="data-wrangling.html"><a href="data-wrangling.html#using-spatial-data-frames"><i class="fa fa-check"></i><b>3.10</b> Using Spatial Data Frames</a>
<ul>
<li class="chapter" data-level="3.10.1" data-path="data-wrangling.html"><a href="data-wrangling.html#read-spatial-data"><i class="fa fa-check"></i><b>3.10.1</b> Read Spatial Data</a></li>
<li class="chapter" data-level="3.10.2" data-path="data-wrangling.html"><a href="data-wrangling.html#basic-mapping"><i class="fa fa-check"></i><b>3.10.2</b> Basic Mapping</a></li>
<li class="chapter" data-level="3.10.3" data-path="data-wrangling.html"><a href="data-wrangling.html#comparing-geographies"><i class="fa fa-check"></i><b>3.10.3</b> Comparing geographies</a></li>
</ul></li>
<li class="chapter" data-level="3.11" data-path="data-wrangling.html"><a href="data-wrangling.html#useful-functions"><i class="fa fa-check"></i><b>3.11</b> Useful Functions</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="points.html"><a href="points.html"><i class="fa fa-check"></i><b>4</b> Points</a>
<ul>
<li class="chapter" data-level="4.1" data-path="points.html"><a href="points.html#dependencies-1"><i class="fa fa-check"></i><b>4.1</b> Dependencies</a></li>
<li class="chapter" data-level="4.2" data-path="points.html"><a href="points.html#data"><i class="fa fa-check"></i><b>4.2</b> Data</a></li>
<li class="chapter" data-level="4.3" data-path="points.html"><a href="points.html#binning"><i class="fa fa-check"></i><b>4.3</b> Binning</a></li>
<li class="chapter" data-level="4.4" data-path="points.html"><a href="points.html#kde"><i class="fa fa-check"></i><b>4.4</b> KDE</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="points.html"><a href="points.html#one-dimensional-kde"><i class="fa fa-check"></i><b>4.4.1</b> One-dimensional KDE</a></li>
<li class="chapter" data-level="4.4.2" data-path="points.html"><a href="points.html#two-dimensional-spatial-kde"><i class="fa fa-check"></i><b>4.4.2</b> Two-dimensional (spatial) KDE</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="points.html"><a href="points.html#spatial-interpolation"><i class="fa fa-check"></i><b>4.5</b> Spatial Interpolation</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="points.html"><a href="points.html#inverse-distance-weight-idw-interpolation"><i class="fa fa-check"></i><b>4.5.1</b> Inverse Distance Weight (IDW) interpolation</a></li>
<li class="chapter" data-level="4.5.2" data-path="points.html"><a href="points.html#a-surface-of-housing-prices"><i class="fa fa-check"></i><b>4.5.2</b> A surface of housing prices</a></li>
<li class="chapter" data-level="4.5.3" data-path="points.html"><a href="points.html#what-should-the-next-houses-price-be"><i class="fa fa-check"></i><b>4.5.3</b> <em>“What should the next house’s price be?”</em></a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="points.html"><a href="points.html#questions"><i class="fa fa-check"></i><b>4.6</b> Questions</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="flows.html"><a href="flows.html"><i class="fa fa-check"></i><b>5</b> Flows</a>
<ul>
<li class="chapter" data-level="5.1" data-path="flows.html"><a href="flows.html#dependencies-2"><i class="fa fa-check"></i><b>5.1</b> Dependencies</a></li>
<li class="chapter" data-level="5.2" data-path="flows.html"><a href="flows.html#data-1"><i class="fa fa-check"></i><b>5.2</b> Data</a></li>
<li class="chapter" data-level="5.3" data-path="flows.html"><a href="flows.html#seeing-flows"><i class="fa fa-check"></i><b>5.3</b> “<em>Seeing</em>” flows</a></li>
<li class="chapter" data-level="5.4" data-path="flows.html"><a href="flows.html#modelling-flows"><i class="fa fa-check"></i><b>5.4</b> Modelling flows</a></li>
<li class="chapter" data-level="5.5" data-path="flows.html"><a href="flows.html#predicting-flows"><i class="fa fa-check"></i><b>5.5</b> Predicting flows</a></li>
<li class="chapter" data-level="5.6" data-path="flows.html"><a href="flows.html#questions-1"><i class="fa fa-check"></i><b>5.6</b> Questions</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="spatialecon.html"><a href="spatialecon.html"><i class="fa fa-check"></i><b>6</b> Spatial Econometrics</a>
<ul>
<li class="chapter" data-level="6.1" data-path="spatialecon.html"><a href="spatialecon.html#dependencies-3"><i class="fa fa-check"></i><b>6.1</b> Dependencies</a></li>
<li class="chapter" data-level="6.2" data-path="spatialecon.html"><a href="spatialecon.html#data-2"><i class="fa fa-check"></i><b>6.2</b> Data</a></li>
<li class="chapter" data-level="6.3" data-path="spatialecon.html"><a href="spatialecon.html#non-spatial-regression-a-refresh"><i class="fa fa-check"></i><b>6.3</b> Non-spatial regression, a refresh</a></li>
<li class="chapter" data-level="6.4" data-path="spatialecon.html"><a href="spatialecon.html#spatial-regression-a-very-first-dip"><i class="fa fa-check"></i><b>6.4</b> Spatial regression: a (very) first dip</a></li>
<li class="chapter" data-level="6.5" data-path="spatialecon.html"><a href="spatialecon.html#spatial-heterogeneity-1"><i class="fa fa-check"></i><b>6.5</b> Spatial heterogeneity</a></li>
<li class="chapter" data-level="6.6" data-path="spatialecon.html"><a href="spatialecon.html#spatial-dependence-1"><i class="fa fa-check"></i><b>6.6</b> Spatial dependence</a></li>
<li class="chapter" data-level="6.7" data-path="spatialecon.html"><a href="spatialecon.html#predicting-house-prices"><i class="fa fa-check"></i><b>6.7</b> Predicting house prices</a></li>
<li class="chapter" data-level="6.8" data-path="spatialecon.html"><a href="spatialecon.html#questions-2"><i class="fa fa-check"></i><b>6.8</b> Questions</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="mlm1.html"><a href="mlm1.html"><i class="fa fa-check"></i><b>7</b> Multilevel Modelling - Part 1</a>
<ul>
<li class="chapter" data-level="7.1" data-path="mlm1.html"><a href="mlm1.html#dependencies-4"><i class="fa fa-check"></i><b>7.1</b> Dependencies</a></li>
<li class="chapter" data-level="7.2" data-path="mlm1.html"><a href="mlm1.html#data-3"><i class="fa fa-check"></i><b>7.2</b> Data</a></li>
<li class="chapter" data-level="7.3" data-path="mlm1.html"><a href="mlm1.html#modelling"><i class="fa fa-check"></i><b>7.3</b> Modelling</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="mlm1.html"><a href="mlm1.html#baseline-linear-regression-model"><i class="fa fa-check"></i><b>7.3.1</b> Baseline Linear Regression Model</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="mlm1.html"><a href="mlm1.html#multilevel-modelling-random-intercept-model"><i class="fa fa-check"></i><b>7.4</b> Multilevel Modelling: Random Intercept Model</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="mlm1.html"><a href="mlm1.html#interpretation"><i class="fa fa-check"></i><b>7.4.1</b> Interpretation</a></li>
<li class="chapter" data-level="7.4.2" data-path="mlm1.html"><a href="mlm1.html#variance-partition-coefficient-vpc"><i class="fa fa-check"></i><b>7.4.2</b> Variance Partition Coefficient (VPC)</a></li>
<li class="chapter" data-level="7.4.3" data-path="mlm1.html"><a href="mlm1.html#uncertainty-of-estimates"><i class="fa fa-check"></i><b>7.4.3</b> Uncertainty of Estimates</a></li>
<li class="chapter" data-level="7.4.4" data-path="mlm1.html"><a href="mlm1.html#assessing-group-level-variation"><i class="fa fa-check"></i><b>7.4.4</b> Assessing Group-level Variation</a></li>
<li class="chapter" data-level="7.4.5" data-path="mlm1.html"><a href="mlm1.html#adding-individual-level-predictors"><i class="fa fa-check"></i><b>7.4.5</b> Adding Individual-level Predictors</a></li>
<li class="chapter" data-level="7.4.6" data-path="mlm1.html"><a href="mlm1.html#adding-group-level-predictors"><i class="fa fa-check"></i><b>7.4.6</b> Adding Group-level Predictors</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="mlm1.html"><a href="mlm1.html#questions-3"><i class="fa fa-check"></i><b>7.5</b> Questions</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="mlm2.html"><a href="mlm2.html"><i class="fa fa-check"></i><b>8</b> Multilevel Modelling - Part 2</a>
<ul>
<li class="chapter" data-level="8.1" data-path="mlm2.html"><a href="mlm2.html#dependencies-5"><i class="fa fa-check"></i><b>8.1</b> Dependencies</a></li>
<li class="chapter" data-level="8.2" data-path="mlm2.html"><a href="mlm2.html#data-4"><i class="fa fa-check"></i><b>8.2</b> Data</a></li>
<li class="chapter" data-level="8.3" data-path="mlm2.html"><a href="mlm2.html#conceptual-overview"><i class="fa fa-check"></i><b>8.3</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="mlm2.html"><a href="mlm2.html#exploratory-analysis-varying-slopes"><i class="fa fa-check"></i><b>8.3.1</b> Exploratory Analysis: Varying Slopes</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="mlm2.html"><a href="mlm2.html#estimating-varying-intercept-and-slopes-models"><i class="fa fa-check"></i><b>8.4</b> Estimating Varying Intercept and Slopes Models</a></li>
<li class="chapter" data-level="8.5" data-path="mlm2.html"><a href="mlm2.html#interpreting-correlations-between-group-level-intercepts-and-slopes"><i class="fa fa-check"></i><b>8.5</b> Interpreting Correlations Between Group-level Intercepts and Slopes</a></li>
<li class="chapter" data-level="8.6" data-path="mlm2.html"><a href="mlm2.html#model-building"><i class="fa fa-check"></i><b>8.6</b> Model building</a>
<ul>
<li class="chapter" data-level="8.6.1" data-path="mlm2.html"><a href="mlm2.html#model-comparison"><i class="fa fa-check"></i><b>8.6.1</b> Model Comparison</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="mlm2.html"><a href="mlm2.html#questions-4"><i class="fa fa-check"></i><b>8.7</b> Questions</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="gwr.html"><a href="gwr.html"><i class="fa fa-check"></i><b>9</b> Geographically Weighted Regression</a>
<ul>
<li class="chapter" data-level="9.1" data-path="gwr.html"><a href="gwr.html#dependencies-6"><i class="fa fa-check"></i><b>9.1</b> Dependencies</a></li>
<li class="chapter" data-level="9.2" data-path="gwr.html"><a href="gwr.html#data-5"><i class="fa fa-check"></i><b>9.2</b> Data</a></li>
<li class="chapter" data-level="9.3" data-path="gwr.html"><a href="gwr.html#recap-spatial-effects"><i class="fa fa-check"></i><b>9.3</b> Recap: Spatial Effects</a></li>
<li class="chapter" data-level="9.4" data-path="gwr.html"><a href="gwr.html#exploratory-analysis"><i class="fa fa-check"></i><b>9.4</b> Exploratory Analysis</a></li>
<li class="chapter" data-level="9.5" data-path="gwr.html"><a href="gwr.html#global-regression"><i class="fa fa-check"></i><b>9.5</b> Global Regression</a>
<ul>
<li class="chapter" data-level="9.5.1" data-path="gwr.html"><a href="gwr.html#global-regression-results"><i class="fa fa-check"></i><b>9.5.1</b> Global Regression Results</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="gwr.html"><a href="gwr.html#fitting-a-geographically-weighted-regression"><i class="fa fa-check"></i><b>9.6</b> Fitting a Geographically Weighted Regression</a>
<ul>
<li class="chapter" data-level="9.6.1" data-path="gwr.html"><a href="gwr.html#fixed-or-adaptive-kernel"><i class="fa fa-check"></i><b>9.6.1</b> Fixed or Adaptive Kernel</a></li>
<li class="chapter" data-level="9.6.2" data-path="gwr.html"><a href="gwr.html#optimal-bandwidth"><i class="fa fa-check"></i><b>9.6.2</b> Optimal Bandwidth</a></li>
<li class="chapter" data-level="9.6.3" data-path="gwr.html"><a href="gwr.html#shape-of-spatial-kernel"><i class="fa fa-check"></i><b>9.6.3</b> Shape of Spatial Kernel</a></li>
<li class="chapter" data-level="9.6.4" data-path="gwr.html"><a href="gwr.html#selecting-a-bandwidth"><i class="fa fa-check"></i><b>9.6.4</b> Selecting a Bandwidth</a></li>
<li class="chapter" data-level="9.6.5" data-path="gwr.html"><a href="gwr.html#model-fit"><i class="fa fa-check"></i><b>9.6.5</b> Model fit</a></li>
<li class="chapter" data-level="9.6.6" data-path="gwr.html"><a href="gwr.html#interpretation-1"><i class="fa fa-check"></i><b>9.6.6</b> Interpretation</a></li>
<li class="chapter" data-level="9.6.7" data-path="gwr.html"><a href="gwr.html#assessing-statistical-significance"><i class="fa fa-check"></i><b>9.6.7</b> Assessing statistical significance</a></li>
<li class="chapter" data-level="9.6.8" data-path="gwr.html"><a href="gwr.html#collinearity-in-gwr"><i class="fa fa-check"></i><b>9.6.8</b> Collinearity in GWR</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="gwr.html"><a href="gwr.html#questions-5"><i class="fa fa-check"></i><b>9.7</b> Questions</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="sta.html"><a href="sta.html"><i class="fa fa-check"></i><b>10</b> Spatio-Temporal Analysis</a>
<ul>
<li class="chapter" data-level="10.1" data-path="sta.html"><a href="sta.html#dependencies-7"><i class="fa fa-check"></i><b>10.1</b> Dependencies</a></li>
<li class="chapter" data-level="10.2" data-path="sta.html"><a href="sta.html#data-6"><i class="fa fa-check"></i><b>10.2</b> Data</a></li>
<li class="chapter" data-level="10.3" data-path="sta.html"><a href="sta.html#why-spatio-temporal-analysis"><i class="fa fa-check"></i><b>10.3</b> Why Spatio-Temporal Analysis?</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="sta.html"><a href="sta.html#spatio-temporal-data-structures"><i class="fa fa-check"></i><b>10.3.1</b> Spatio-temporal Data Structures</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="sta.html"><a href="sta.html#data-wrangling"><i class="fa fa-check"></i><b>10.4</b> Data Wrangling</a></li>
<li class="chapter" data-level="10.5" data-path="sta.html"><a href="sta.html#exploring-spatio-temporal-data"><i class="fa fa-check"></i><b>10.5</b> Exploring Spatio-Temporal Data</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="sta.html"><a href="sta.html#visualisation"><i class="fa fa-check"></i><b>10.5.1</b> Visualisation</a></li>
<li class="chapter" data-level="10.5.2" data-path="sta.html"><a href="sta.html#exploratory-analysis-1"><i class="fa fa-check"></i><b>10.5.2</b> Exploratory Analysis</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="sta.html"><a href="sta.html#spatio-temporal-data-modelling"><i class="fa fa-check"></i><b>10.6</b> Spatio-Temporal Data Modelling</a>
<ul>
<li class="chapter" data-level="10.6.1" data-path="sta.html"><a href="sta.html#intuition"><i class="fa fa-check"></i><b>10.6.1</b> Intuition</a></li>
<li class="chapter" data-level="10.6.2" data-path="sta.html"><a href="sta.html#fitting-spatio-temporal-models"><i class="fa fa-check"></i><b>10.6.2</b> Fitting Spatio-Temporal Models</a></li>
</ul></li>
<li class="chapter" data-level="10.7" data-path="sta.html"><a href="sta.html#questions-6"><i class="fa fa-check"></i><b>10.7</b> Questions</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="datasets.html"><a href="datasets.html"><i class="fa fa-check"></i><b>11</b> Data Sets</a>
<ul>
<li class="chapter" data-level="11.1" data-path="datasets.html"><a href="datasets.html#madrid-airbnb"><i class="fa fa-check"></i><b>11.1</b> Madrid AirBnb</a>
<ul>
<li class="chapter" data-level="" data-path="datasets.html"><a href="datasets.html#availability"><i class="fa fa-check"></i>Availability</a></li>
<li class="chapter" data-level="" data-path="datasets.html"><a href="datasets.html#variables"><i class="fa fa-check"></i>Variables</a></li>
<li class="chapter" data-level="" data-path="datasets.html"><a href="datasets.html#projection"><i class="fa fa-check"></i>Projection</a></li>
<li class="chapter" data-level="" data-path="datasets.html"><a href="datasets.html#source-pre-processing"><i class="fa fa-check"></i>Source &amp; Pre-processing</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="datasets.html"><a href="datasets.html#england-covid-19"><i class="fa fa-check"></i><b>11.2</b> England COVID-19</a>
<ul>
<li class="chapter" data-level="" data-path="datasets.html"><a href="datasets.html#availability-1"><i class="fa fa-check"></i>Availability</a></li>
<li class="chapter" data-level="" data-path="datasets.html"><a href="datasets.html#variables-1"><i class="fa fa-check"></i>Variables</a></li>
<li class="chapter" data-level="" data-path="datasets.html"><a href="datasets.html#projection-1"><i class="fa fa-check"></i>Projection</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Spatial Modelling for Data Scientists</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="gwr" class="section level1" number="9">
<h1><span class="header-section-number">Chapter 9</span> Geographically Weighted Regression</h1>
<p>This chapter provides an introduction to geographically weighted regression models.</p>
<p>The content of this chapter is based on:</p>
<ul>
<li><p><span class="citation"><a href="references.html#ref-Fotheringham_et_al_2002_book" role="doc-biblioref">S. Fotheringham, Brunsdon, and Charlton</a> (<a href="references.html#ref-Fotheringham_et_al_2002_book" role="doc-biblioref">2002</a>)</span>, a must-go book if you are working or planning to start working on geographically weighted regression modelling.</p></li>
<li><p><span class="citation"><a href="references.html#ref-comber2020gwr" role="doc-biblioref">Comber et al.</a> (<a href="references.html#ref-comber2020gwr" role="doc-biblioref">2020</a>)</span>’s recently published preprint which provides a roadmap to approach various practical issues in the application of GWR.</p></li>
</ul>
<div id="dependencies-6" class="section level2" number="9.1">
<h2><span class="header-section-number">9.1</span> Dependencies</h2>
<p>This chapter uses the following libraries:</p>
<div class="sourceCode" id="cb345"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb345-1"><a href="gwr.html#cb345-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Data manipulation, transformation and visualisation</span></span>
<span id="cb345-2"><a href="gwr.html#cb345-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
<pre><code>## Warning in system(&quot;timedatectl&quot;, intern = TRUE): running command &#39;timedatectl&#39;
## had status 1</code></pre>
<div class="sourceCode" id="cb347"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb347-1"><a href="gwr.html#cb347-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Nice tables</span></span>
<span id="cb347-2"><a href="gwr.html#cb347-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb347-3"><a href="gwr.html#cb347-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Simple features (a standardised way to encode vector data ie. points, lines, polygons)</span></span>
<span id="cb347-4"><a href="gwr.html#cb347-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf) </span>
<span id="cb347-5"><a href="gwr.html#cb347-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Spatial objects conversion</span></span>
<span id="cb347-6"><a href="gwr.html#cb347-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sp) </span>
<span id="cb347-7"><a href="gwr.html#cb347-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Thematic maps</span></span>
<span id="cb347-8"><a href="gwr.html#cb347-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tmap) </span>
<span id="cb347-9"><a href="gwr.html#cb347-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Colour palettes</span></span>
<span id="cb347-10"><a href="gwr.html#cb347-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(RColorBrewer) </span>
<span id="cb347-11"><a href="gwr.html#cb347-11" aria-hidden="true" tabindex="-1"></a><span class="co"># More colour palettes</span></span>
<span id="cb347-12"><a href="gwr.html#cb347-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(viridis) <span class="co"># nice colour schemes</span></span>
<span id="cb347-13"><a href="gwr.html#cb347-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Fitting geographically weighted regression models</span></span>
<span id="cb347-14"><a href="gwr.html#cb347-14" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(spgwr)</span>
<span id="cb347-15"><a href="gwr.html#cb347-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtain correlation coefficients</span></span>
<span id="cb347-16"><a href="gwr.html#cb347-16" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span>
<span id="cb347-17"><a href="gwr.html#cb347-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Exportable regression tables</span></span>
<span id="cb347-18"><a href="gwr.html#cb347-18" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(jtools)</span>
<span id="cb347-19"><a href="gwr.html#cb347-19" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stargazer)</span>
<span id="cb347-20"><a href="gwr.html#cb347-20" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb347-21"><a href="gwr.html#cb347-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Assess multicollinearity</span></span>
<span id="cb347-22"><a href="gwr.html#cb347-22" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code></pre></div>
</div>
<div id="data-5" class="section level2" number="9.2">
<h2><span class="header-section-number">9.2</span> Data</h2>
<p>For this chapter, we will use data on:</p>
<ul>
<li><p>cumulative COVID-19 confirmed cases from 1st January, 2020 to 14th April, 2020 from Public Health England via the <a href="https://coronavirus.data.gov.uk">GOV.UK dashboard</a>;</p></li>
<li><p>resident population characteristics from the 2011 census, available from the <a href="https://www.nomisweb.co.uk/home/census2001.asp">Office of National Statistics</a>; and,</p></li>
<li><p>2019 Index of Multiple Deprivation (IMD) data from <a href="https://www.gov.uk/government/statistics/english-indices-of-deprivation-2019">GOV.UK</a> and published by the Ministry of Housing, Communities &amp; Local Government.</p></li>
</ul>
<p>The data used for this Chapter are organised at the ONS Upper Tier Local Authority (UTLA) level - also known as <a href="https://geoportal.statistics.gov.uk/datasets/fe6bcee87d95476abc84e194fe088abb_0">Counties and Unitary Authorities</a>. They are the geographical units used to report COVID-19 data.</p>
<p>If you use the dataset utilised in this chapter, make sure cite this book. For a full list of the variables included in the data set used in this Chapter, see the readme file in the gwr data folder.<a href="#fn27" class="footnote-ref" id="fnref27"><sup>27</sup></a></p>
<p>Let’s read the data:</p>
<div class="sourceCode" id="cb348"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb348-1"><a href="gwr.html#cb348-1" aria-hidden="true" tabindex="-1"></a><span class="co"># clean workspace</span></span>
<span id="cb348-2"><a href="gwr.html#cb348-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list=</span><span class="fu">ls</span>())</span>
<span id="cb348-3"><a href="gwr.html#cb348-3" aria-hidden="true" tabindex="-1"></a><span class="co"># read data</span></span>
<span id="cb348-4"><a href="gwr.html#cb348-4" aria-hidden="true" tabindex="-1"></a>utla_shp <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">&quot;data/gwr/Covid19_total_cases_geo.shp&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb348-5"><a href="gwr.html#cb348-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(objct, cty19c, ctyu19nm, long, lat, st_rs, st_ln, X2020.<span class="fl">04.14</span>, I.PL1, IMD20, IMD2., Rsdnt, Hshld, Dwlln, Hsh_S, E_16_, A_65_, Ag_85, Mixed, Indin, Pkstn, Bngld, Chins, Oth_A, Black, Othr_t, CB_U_, Crwd_, Lng__, Trn__, Adm__, Ac___, Pb___, Edctn, H____, geometry)</span>
<span id="cb348-6"><a href="gwr.html#cb348-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb348-7"><a href="gwr.html#cb348-7" aria-hidden="true" tabindex="-1"></a><span class="co"># replace nas with 0s</span></span>
<span id="cb348-8"><a href="gwr.html#cb348-8" aria-hidden="true" tabindex="-1"></a>utla_shp[<span class="fu">is.na</span>(utla_shp)] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb348-9"><a href="gwr.html#cb348-9" aria-hidden="true" tabindex="-1"></a><span class="co"># explore data</span></span>
<span id="cb348-10"><a href="gwr.html#cb348-10" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(utla_shp)</span></code></pre></div>
</div>
<div id="recap-spatial-effects" class="section level2" number="9.3">
<h2><span class="header-section-number">9.3</span> Recap: Spatial Effects</h2>
<p>To this point, we have implicitly discussed three distinctive spatial effects:</p>
<ul>
<li><p><em>Spatial heterogeneity</em> refers to the uneven distribution of a variable’s values across space</p></li>
<li><p><em>Spatial dependence</em> refers to the spatial relationship of a variable’s values for a pair of locations at a certain distance apart, so that they are more similar (or less similar) than expected for randomly associated pairs of observations</p></li>
<li><p><em>Spatial nonstationarity</em> refers to variations in the relationship between an outcome variable and a set of predictor variables across space</p></li>
</ul>
<p>In previous sessions, we considered multilevel models to deal with spatial nonstationarity, recognising that the strength and direction of the relationship between an outcome <span class="math inline">\(y\)</span> and a set of predictors <span class="math inline">\(x\)</span> may vary over space. Here we consider a different approach, namely geographically weighted regression (GWR).</p>
</div>
<div id="exploratory-analysis" class="section level2" number="9.4">
<h2><span class="header-section-number">9.4</span> Exploratory Analysis</h2>
<p>We will explore this technique through an empirical analysis considering the current global COVID-19 outbreak. Specifically we will seek to identify potential contextual factors that may be related to an increased risk of local infection. Population density, overcrowded housing, vulnerable individuals and critical workers have all been linked to a higher risk of COVID-19 infection.</p>
<p>First, we will define and develop some basic understanding of our variable of interest. We define the risk of COVID-19 infection by the cumulative number of confirmed positive cases COVID-19 per 100,000 people:</p>
<div class="sourceCode" id="cb349"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb349-1"><a href="gwr.html#cb349-1" aria-hidden="true" tabindex="-1"></a><span class="co"># risk of covid-19 infection</span></span>
<span id="cb349-2"><a href="gwr.html#cb349-2" aria-hidden="true" tabindex="-1"></a>utla_shp<span class="sc">$</span>covid19_r <span class="ot">&lt;-</span> (utla_shp<span class="sc">$</span>X2020.<span class="fl">04.14</span> <span class="sc">/</span> utla_shp<span class="sc">$</span>Rsdnt) <span class="sc">*</span> <span class="dv">100000</span></span>
<span id="cb349-3"><a href="gwr.html#cb349-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb349-4"><a href="gwr.html#cb349-4" aria-hidden="true" tabindex="-1"></a><span class="co"># histogram</span></span>
<span id="cb349-5"><a href="gwr.html#cb349-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> utla_shp) <span class="sc">+</span></span>
<span id="cb349-6"><a href="gwr.html#cb349-6" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_density</span>(<span class="at">alpha=</span><span class="fl">0.8</span>, <span class="at">colour=</span><span class="st">&quot;black&quot;</span>, <span class="at">fill=</span><span class="st">&quot;lightblue&quot;</span>, <span class="fu">aes</span>(<span class="at">x =</span> covid19_r)) <span class="sc">+</span></span>
<span id="cb349-7"><a href="gwr.html#cb349-7" aria-hidden="true" tabindex="-1"></a>   <span class="fu">theme_classic</span>()</span></code></pre></div>
<p><img src="09-gwr_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<div class="sourceCode" id="cb350"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb350-1"><a href="gwr.html#cb350-1" aria-hidden="true" tabindex="-1"></a><span class="co"># distribution in numbers</span></span>
<span id="cb350-2"><a href="gwr.html#cb350-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(utla_shp<span class="sc">$</span>covid19_r)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   32.11   92.81  140.15  146.66  190.96  341.56</code></pre>
<p>The results indicate a wide variation in the risk of infection across UTLAs in England, ranging from 31 to 342 confirmed positive cases of COVID-19 per 100,000 people with a median of 147. We map the cases to understand their spatial structure.</p>
<div class="sourceCode" id="cb352"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb352-1"><a href="gwr.html#cb352-1" aria-hidden="true" tabindex="-1"></a><span class="co"># read region boundaries for a better looking map</span></span>
<span id="cb352-2"><a href="gwr.html#cb352-2" aria-hidden="true" tabindex="-1"></a>reg_shp <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">&quot;data/gwr/Regions_December_2019_Boundaries_EN_BGC.shp&quot;</span>)</span></code></pre></div>
<pre><code>## Reading layer `Regions_December_2019_Boundaries_EN_BGC&#39; from data source `/home/jovyan/work/data/gwr/Regions_December_2019_Boundaries_EN_BGC.shp&#39; using driver `ESRI Shapefile&#39;
## Simple feature collection with 9 features and 9 fields
## geometry type:  MULTIPOLYGON
## dimension:      XY
## bbox:           xmin: 82672 ymin: 5342.7 xmax: 655653.8 ymax: 657536
## projected CRS:  OSGB 1936 / British National Grid</code></pre>
<div class="sourceCode" id="cb354"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb354-1"><a href="gwr.html#cb354-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ensure geometry is valid</span></span>
<span id="cb354-2"><a href="gwr.html#cb354-2" aria-hidden="true" tabindex="-1"></a>utla_shp <span class="ot">=</span> sf<span class="sc">::</span><span class="fu">st_make_valid</span>(utla_shp)</span>
<span id="cb354-3"><a href="gwr.html#cb354-3" aria-hidden="true" tabindex="-1"></a>reg_shp <span class="ot">=</span> sf<span class="sc">::</span><span class="fu">st_make_valid</span>(reg_shp)</span>
<span id="cb354-4"><a href="gwr.html#cb354-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb354-5"><a href="gwr.html#cb354-5" aria-hidden="true" tabindex="-1"></a><span class="co"># map</span></span>
<span id="cb354-6"><a href="gwr.html#cb354-6" aria-hidden="true" tabindex="-1"></a>legend_title <span class="ot">=</span> <span class="fu">expression</span>(<span class="st">&quot;Cumulative cases per 100,000&quot;</span>)</span>
<span id="cb354-7"><a href="gwr.html#cb354-7" aria-hidden="true" tabindex="-1"></a>map_utla <span class="ot">=</span> <span class="fu">tm_shape</span>(utla_shp) <span class="sc">+</span></span>
<span id="cb354-8"><a href="gwr.html#cb354-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">&quot;covid19_r&quot;</span>, <span class="at">title =</span> legend_title, <span class="at">palette =</span> <span class="fu">magma</span>(<span class="dv">256</span>), <span class="at">style =</span> <span class="st">&quot;cont&quot;</span>) <span class="sc">+</span> <span class="co"># add fill</span></span>
<span id="cb354-9"><a href="gwr.html#cb354-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">&quot;white&quot;</span>, <span class="at">lwd =</span> .<span class="dv">1</span>)  <span class="sc">+</span> <span class="co"># add borders</span></span>
<span id="cb354-10"><a href="gwr.html#cb354-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_compass</span>(<span class="at">type =</span> <span class="st">&quot;arrow&quot;</span>, <span class="at">position =</span> <span class="fu">c</span>(<span class="st">&quot;right&quot;</span>, <span class="st">&quot;top&quot;</span>) , <span class="at">size =</span> <span class="dv">5</span>) <span class="sc">+</span> <span class="co"># add compass</span></span>
<span id="cb354-11"><a href="gwr.html#cb354-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_scale_bar</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">2</span>), <span class="at">text.size =</span> <span class="fl">0.7</span>, <span class="at">position =</span>  <span class="fu">c</span>(<span class="st">&quot;center&quot;</span>, <span class="st">&quot;bottom&quot;</span>)) <span class="sc">+</span> <span class="co"># add scale bar</span></span>
<span id="cb354-12"><a href="gwr.html#cb354-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">bg.color =</span> <span class="st">&quot;white&quot;</span>) <span class="co"># change background colour</span></span>
<span id="cb354-13"><a href="gwr.html#cb354-13" aria-hidden="true" tabindex="-1"></a>map_utla <span class="sc">+</span> <span class="fu">tm_shape</span>(reg_shp) <span class="sc">+</span> <span class="co"># add region boundaries</span></span>
<span id="cb354-14"><a href="gwr.html#cb354-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">&quot;white&quot;</span>, <span class="at">lwd =</span> .<span class="dv">5</span>) <span class="co"># add borders</span></span></code></pre></div>
<p><img src="09-gwr_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>The map shows that concentrations of high incidence of infections in the metropolitan areas of London, Liverpool, Newcastle, Sheffield, Middlesbrough and Birmingham. Below we list the UTLAs in these areas in descending order.</p>
<div class="sourceCode" id="cb355"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb355-1"><a href="gwr.html#cb355-1" aria-hidden="true" tabindex="-1"></a>hotspots <span class="ot">&lt;-</span> utla_shp <span class="sc">%&gt;%</span> <span class="fu">select</span>(ctyu19nm, covid19_r) <span class="sc">%&gt;%</span></span>
<span id="cb355-2"><a href="gwr.html#cb355-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(covid19_r <span class="sc">&gt;</span> <span class="dv">190</span>)</span>
<span id="cb355-3"><a href="gwr.html#cb355-3" aria-hidden="true" tabindex="-1"></a>hotspots[<span class="fu">order</span>(<span class="sc">-</span>hotspots<span class="sc">$</span>covid19_r),]</span></code></pre></div>
<pre><code>## Simple feature collection with 38 features and 2 fields
## geometry type:  MULTIPOLYGON
## dimension:      XY
## bbox:           xmin: 293941.4 ymin: 155850.8 xmax: 561956.7 ymax: 588517.4
## projected CRS:  Transverse_Mercator
## First 10 features:
##     ctyu19nm covid19_r                       geometry
## 14     Brent  341.5645 MULTIPOLYGON (((520113.1 19...
## 32 Southwark  337.1687 MULTIPOLYGON (((532223 1805...
## 27   Lambeth  305.5238 MULTIPOLYGON (((531189.5 18...
## 22    Harrow  286.1254 MULTIPOLYGON (((517363.8 19...
## 17   Croydon  276.8467 MULTIPOLYGON (((531549.3 17...
## 12    Barnet  274.1410 MULTIPOLYGON (((524645.2 19...
## 28  Lewisham  261.3408 MULTIPOLYGON (((536691.6 17...
## 30    Newham  258.4550 MULTIPOLYGON (((542600.7 18...
## 38   Cumbria  255.6726 MULTIPOLYGON (((357012.9 58...
## 15   Bromley  253.7234 MULTIPOLYGON (((542252.7 17...</code></pre>
<blockquote>
<p>Challenge 1:
How does Liverpool ranked in this list?</p>
</blockquote>
</div>
<div id="global-regression" class="section level2" number="9.5">
<h2><span class="header-section-number">9.5</span> Global Regression</h2>
<p>To provide an intuitive understanding of GWR, a useful start is to explore the data using an ordinary least squares (OLS) linear regression model. The key issue here is to understand if high incidence of COVID-19 is linked to structural differences across UTLAs in England. As indicated above, confirmed positive cases of COVID-19 have been associated with overcrowded housing, vulnerable populations - including people in elderly age groups, economically disadvantaged groups and those suffering from chronic health conditions - ethnic minorities, critical workers in the health &amp; social work, education, accommodation &amp; food, transport, and administrative &amp; support sectors. So, let’s create a set of variables to approximate these factors.</p>
<div class="sourceCode" id="cb357"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb357-1"><a href="gwr.html#cb357-1" aria-hidden="true" tabindex="-1"></a><span class="co"># define predictors</span></span>
<span id="cb357-2"><a href="gwr.html#cb357-2" aria-hidden="true" tabindex="-1"></a>utla_shp <span class="ot">&lt;-</span> utla_shp <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(</span>
<span id="cb357-3"><a href="gwr.html#cb357-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">crowded_hou =</span> Crwd_ <span class="sc">/</span> Hshld, <span class="co"># share of crowded housing</span></span>
<span id="cb357-4"><a href="gwr.html#cb357-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">elderly =</span> (A_65_ <span class="sc">+</span> Ag_85) <span class="sc">/</span> Rsdnt, <span class="co"># share of population aged 65+</span></span>
<span id="cb357-5"><a href="gwr.html#cb357-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">lt_illness =</span> Lng__ <span class="sc">/</span> Rsdnt, <span class="co"># share of population in long-term illness</span></span>
<span id="cb357-6"><a href="gwr.html#cb357-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">ethnic =</span> (Mixed <span class="sc">+</span> Indin <span class="sc">+</span> Pkstn <span class="sc">+</span> Bngld <span class="sc">+</span> Chins <span class="sc">+</span> Oth_A <span class="sc">+</span> Black <span class="sc">+</span> Othr_t) <span class="sc">/</span> Rsdnt, <span class="co"># share of nonwhite population</span></span>
<span id="cb357-7"><a href="gwr.html#cb357-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">imd19_ext =</span> IMD20, <span class="co"># proportion of a larger area’s population living in the most deprived LSOAs in the country</span></span>
<span id="cb357-8"><a href="gwr.html#cb357-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">hlthsoc_sec =</span> H____ <span class="sc">/</span> E_16_, <span class="co"># share of workforce in the human health &amp; social work sector</span></span>
<span id="cb357-9"><a href="gwr.html#cb357-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">educ_sec =</span> Edctn <span class="sc">/</span> E_16_, <span class="co"># share of workforce in the education sector</span></span>
<span id="cb357-10"><a href="gwr.html#cb357-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">trnsp_sec=</span> Trn__ <span class="sc">/</span> E_16_, <span class="co"># share of workforce in the Transport &amp; storage sector</span></span>
<span id="cb357-11"><a href="gwr.html#cb357-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">accfood_sec =</span> Ac___ <span class="sc">/</span> E_16_, <span class="co"># share of workforce in the accommodation &amp; food service sector</span></span>
<span id="cb357-12"><a href="gwr.html#cb357-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">admsupport_sec =</span> Adm__ <span class="sc">/</span>  E_16_, <span class="co"># share of workforce in the administrative &amp; support sector</span></span>
<span id="cb357-13"><a href="gwr.html#cb357-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">pblic_sec =</span> Pb___ <span class="sc">/</span> E_16_ <span class="co"># share of workforce in the public administration &amp; defence sector</span></span>
<span id="cb357-14"><a href="gwr.html#cb357-14" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<p>Let’s quickly examine how they correlate to our outcome variable i.e. incidence rate of COVID-19 using correlation coefficients and correlograms.</p>
<div class="sourceCode" id="cb358"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb358-1"><a href="gwr.html#cb358-1" aria-hidden="true" tabindex="-1"></a><span class="co"># obtain a matrix of Pearson correlation coefficients</span></span>
<span id="cb358-2"><a href="gwr.html#cb358-2" aria-hidden="true" tabindex="-1"></a>df_sel <span class="ot">&lt;-</span> <span class="fu">st_set_geometry</span>(utla_shp[,<span class="dv">37</span><span class="sc">:</span><span class="dv">48</span>], <span class="cn">NULL</span>) <span class="co"># temporary data set removing geometries</span></span>
<span id="cb358-3"><a href="gwr.html#cb358-3" aria-hidden="true" tabindex="-1"></a>cormat <span class="ot">&lt;-</span> <span class="fu">cor</span>(df_sel, <span class="at">use=</span><span class="st">&quot;complete.obs&quot;</span>, <span class="at">method=</span><span class="st">&quot;pearson&quot;</span>)</span>
<span id="cb358-4"><a href="gwr.html#cb358-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb358-5"><a href="gwr.html#cb358-5" aria-hidden="true" tabindex="-1"></a><span class="co"># significance test</span></span>
<span id="cb358-6"><a href="gwr.html#cb358-6" aria-hidden="true" tabindex="-1"></a>sig1 <span class="ot">&lt;-</span> corrplot<span class="sc">::</span><span class="fu">cor.mtest</span>(df_sel, <span class="at">conf.level =</span> .<span class="dv">95</span>)</span>
<span id="cb358-7"><a href="gwr.html#cb358-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb358-8"><a href="gwr.html#cb358-8" aria-hidden="true" tabindex="-1"></a><span class="co"># creta a correlogram</span></span>
<span id="cb358-9"><a href="gwr.html#cb358-9" aria-hidden="true" tabindex="-1"></a>corrplot<span class="sc">::</span><span class="fu">corrplot</span>(cormat, <span class="at">type=</span><span class="st">&quot;lower&quot;</span>,</span>
<span id="cb358-10"><a href="gwr.html#cb358-10" aria-hidden="true" tabindex="-1"></a>                   <span class="at">method =</span> <span class="st">&quot;circle&quot;</span>, </span>
<span id="cb358-11"><a href="gwr.html#cb358-11" aria-hidden="true" tabindex="-1"></a>                   <span class="at">order =</span> <span class="st">&quot;original&quot;</span>, </span>
<span id="cb358-12"><a href="gwr.html#cb358-12" aria-hidden="true" tabindex="-1"></a>                   <span class="at">tl.cex =</span> <span class="fl">0.7</span>,</span>
<span id="cb358-13"><a href="gwr.html#cb358-13" aria-hidden="true" tabindex="-1"></a>                   <span class="at">p.mat =</span> sig1<span class="sc">$</span>p, <span class="at">sig.level =</span> .<span class="dv">05</span>, </span>
<span id="cb358-14"><a href="gwr.html#cb358-14" aria-hidden="true" tabindex="-1"></a>                   <span class="at">col =</span> viridis<span class="sc">::</span><span class="fu">viridis</span>(<span class="dv">100</span>, <span class="at">option =</span> <span class="st">&quot;plasma&quot;</span>),</span>
<span id="cb358-15"><a href="gwr.html#cb358-15" aria-hidden="true" tabindex="-1"></a>                   <span class="at">diag =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p><img src="09-gwr_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>The correlogram shows the strength and significance of the linear relationship between our set of variables. The size of the circle reflects the strength of the relationships as captured by the Pearson correlation coefficient, and crosses indicate statistically insignificant relationships at the 95% level of confidence. The colour indicate the direction of the relationship with dark (light) colours indicating a negative (positive) association.</p>
<p>The results indicate that the incidence of COVID-19 is significantly and positively related to the share of overcrowded housing, nonwhite ethnic minorities and administrative &amp; support workers. Against expectations, the incidence of COVID-19 appears to be negatively correlated with the share of elderly population, of population suffering from long-term illness and of administrative &amp; support workers, and displays no significant association with the share of the population living in deprived areas as well as the share of public administration &amp; defence workers, and health &amp; social workers. The latter probably reflects the effectiveness of the protective measures undertaken to prevent infection among these population groups, but it may also reflect the partial coverage of COVID-19 testing and underreporting. It may also reveal the descriptive limitations of correlation coefficients as they show the relationship between a pairs of variables, not controlling for others. Correlation coefficients can thus produce spurious relationships resulting from confounded variables. We will return to this point below.</p>
<p>The results also reveal high collinearity between particular pairs of variables, notably between the share of crowded housing and of nonwhite ethnic population, the share of crowded housing and of elderly population, the share of overcrowded housing and of administrative &amp; support workers, the share of elderly population and of population suffering from long-term illness. A more refined analysis of multicollinearity is needed. Various diagnostics for multicollinearity in a regression framework exist, including matrix condition numbers (CNs), predictor variance inflation factors (VIFs) and variance decomposition factors (VDPs). Rules of thumb (CNs &gt; 30, VIFs &gt; 10 and VDPs &gt; 0.5) to indicate worrying levels of collinearity can be found in <span class="citation"><a href="references.html#ref-belsley2005regression" role="doc-biblioref">Belsley, Kuh, and Welsch</a> (<a href="references.html#ref-belsley2005regression" role="doc-biblioref">2005</a>)</span>. To avoid problems of multicollinearity, often a simple strategy is to remove highly correlated predictors. The difficultly is in deciding which predictor(s) to remove, especially when all are considered important. Keep this in mind when specifying your model.</p>
<blockquote>
<p>Challenge 2:
Analyse the relationship of all the variables executing <code>pairs(df_sel)</code>. How accurate would a linear regression be in capturing the relationships for our set of variables?</p>
</blockquote>
<div id="global-regression-results" class="section level3" number="9.5.1">
<h3><span class="header-section-number">9.5.1</span> Global Regression Results</h3>
<p>To gain a better understanding of these relationships, we can regress the incidence rate of COVID-19 on a series of factors capturing differences across areas. To focus on the description of GWR, we keep our analysis simple and study the incidence rate of COVID-19 as a function of the share of nonwhite ethnic population and of population suffering from long-term illness by estimating the following OLS linear regression model:</p>
<div class="sourceCode" id="cb359"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb359-1"><a href="gwr.html#cb359-1" aria-hidden="true" tabindex="-1"></a><span class="co"># attach data</span></span>
<span id="cb359-2"><a href="gwr.html#cb359-2" aria-hidden="true" tabindex="-1"></a><span class="fu">attach</span>(utla_shp)</span>
<span id="cb359-3"><a href="gwr.html#cb359-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb359-4"><a href="gwr.html#cb359-4" aria-hidden="true" tabindex="-1"></a><span class="co"># specify a model equation</span></span>
<span id="cb359-5"><a href="gwr.html#cb359-5" aria-hidden="true" tabindex="-1"></a>eq1 <span class="ot">&lt;-</span> covid19_r <span class="sc">~</span> ethnic <span class="sc">+</span> lt_illness</span>
<span id="cb359-6"><a href="gwr.html#cb359-6" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> eq1, <span class="at">data =</span> utla_shp)</span>
<span id="cb359-7"><a href="gwr.html#cb359-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb359-8"><a href="gwr.html#cb359-8" aria-hidden="true" tabindex="-1"></a><span class="co"># estimates</span></span>
<span id="cb359-9"><a href="gwr.html#cb359-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = eq1, data = utla_shp)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -109.234  -38.386   -4.879   29.284  143.786 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    63.77      30.13   2.117    0.036 *  
## ethnic        271.10      30.65   8.845 2.64e-15 ***
## lt_illness    216.20     151.88   1.424    0.157    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 51 on 147 degrees of freedom
## Multiple R-squared:  0.3926, Adjusted R-squared:  0.3844 
## F-statistic: 47.52 on 2 and 147 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>We also compute the VIFs for the variables in the model:</p>
<div class="sourceCode" id="cb361"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb361-1"><a href="gwr.html#cb361-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(model1)</span></code></pre></div>
<pre><code>##     ethnic lt_illness 
##    1.43015    1.43015</code></pre>
<p>The regression results indicate a positive relationship exists between the share of nonwhite population and an increased risk of COVID-19 infection. A one percentage point increase in the share of nonwhite population returns a 271 rise in the cumulative count of COVID-19 infection per 100,000 people, everything else constant. The results also reveal a positive (albeit statistically insignificant) relationship between the share of population suffering from long-term illness and an increased risk of COVID-19 infection, after controlling for the share of nonwhite population, thereby confirming our suspicion about the limitations of correlation coefficients; that is, once differences in the share of nonwhite population are taken into account, the association between the share of population suffering from long-term illness and an increased risk of COVID-19 infection becomes positive. We also test for multicollinearity. The VIFs are below 10 indicating that multicollinearity is not highly problematic.</p>
<p>The <span class="math inline">\(R^{2}\)</span> value for the OLS regression is 0.393 indicating that our model explains only 39% of the variance in the rate of COVID-19 infection. This leaves 71% of the variance unexplained. Some of this unexplained variance can be because we have only included two explanatory variables in our model, but also because the OLS regression model assumes that the relationships in the model are constant over space; that is, it assumes a stationary process. Hence, an OLS regression model is considered to capture global relationships. However, relationships may vary over space. Suppose, for instance, that there are intrinsic behavioural variations across England and that people have adhered more strictly to self-isolation and social distancing measures in some areas than in others, or that ethnic minorities are less exposed to contracting COVID-19 in certain parts of England. If such variations in associations exist over space, our estimated OLS model will be a misspecification of reality because it assumes these relationships to be constant.</p>
<p>To better understand this potential misspecification, we investigate the model residuals which show high variability (see below). The distribution is non-random displaying large positive residuals in the metropolitan areas of London, Liverpool, Newcastle (in light colours) and the Lake District and large negative residuals across much of England (in black). This conforms to the spatial pattern of confirmed COVID-19 cases with high concentration in a limited number of metropolitan areas (see above). While our residual map reveals that there is a problem with the OLS model, it does not indicate which, if any, of the parameters in the model might exhibit spatial nonstationarity. A simple way of examining if the relationships being modelled in our global OLS model are likely to be stationary over space would be to estimate separate OLS model for each UTLA in England. But this would require higher resolution i.e. data within UTLA, and we only have one data point per UTLA. <span class="citation">(<a href="references.html#ref-Fotheringham_et_al_2002_book" role="doc-biblioref">2002</a>)</span> (2002, p.40-44) discuss alternative approaches and their limitations.</p>
<div class="sourceCode" id="cb363"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb363-1"><a href="gwr.html#cb363-1" aria-hidden="true" tabindex="-1"></a>utla_shp<span class="sc">$</span>res_m1 <span class="ot">&lt;-</span> <span class="fu">residuals</span>(model1)</span>
<span id="cb363-2"><a href="gwr.html#cb363-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb363-3"><a href="gwr.html#cb363-3" aria-hidden="true" tabindex="-1"></a><span class="co"># map</span></span>
<span id="cb363-4"><a href="gwr.html#cb363-4" aria-hidden="true" tabindex="-1"></a>legend_title <span class="ot">=</span> <span class="fu">expression</span>(<span class="st">&quot;OLS residuals&quot;</span>)</span>
<span id="cb363-5"><a href="gwr.html#cb363-5" aria-hidden="true" tabindex="-1"></a>map_utla <span class="ot">=</span> <span class="fu">tm_shape</span>(utla_shp) <span class="sc">+</span></span>
<span id="cb363-6"><a href="gwr.html#cb363-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">&quot;res_m1&quot;</span>, <span class="at">title =</span> legend_title, <span class="at">palette =</span> <span class="fu">magma</span>(<span class="dv">256</span>), <span class="at">style =</span> <span class="st">&quot;cont&quot;</span>) <span class="sc">+</span> <span class="co"># add fill</span></span>
<span id="cb363-7"><a href="gwr.html#cb363-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">&quot;white&quot;</span>, <span class="at">lwd =</span> .<span class="dv">1</span>)  <span class="sc">+</span> <span class="co"># add borders</span></span>
<span id="cb363-8"><a href="gwr.html#cb363-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_compass</span>(<span class="at">type =</span> <span class="st">&quot;arrow&quot;</span>, <span class="at">position =</span> <span class="fu">c</span>(<span class="st">&quot;right&quot;</span>, <span class="st">&quot;top&quot;</span>) , <span class="at">size =</span> <span class="dv">5</span>) <span class="sc">+</span> <span class="co"># add compass</span></span>
<span id="cb363-9"><a href="gwr.html#cb363-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_scale_bar</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">2</span>), <span class="at">text.size =</span> <span class="fl">0.7</span>, <span class="at">position =</span>  <span class="fu">c</span>(<span class="st">&quot;center&quot;</span>, <span class="st">&quot;bottom&quot;</span>)) <span class="sc">+</span> <span class="co"># add scale bar</span></span>
<span id="cb363-10"><a href="gwr.html#cb363-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">bg.color =</span> <span class="st">&quot;white&quot;</span>) <span class="co"># change background colour</span></span>
<span id="cb363-11"><a href="gwr.html#cb363-11" aria-hidden="true" tabindex="-1"></a>map_utla <span class="sc">+</span> <span class="fu">tm_shape</span>(reg_shp) <span class="sc">+</span> <span class="co"># add region boundaries</span></span>
<span id="cb363-12"><a href="gwr.html#cb363-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">&quot;white&quot;</span>, <span class="at">lwd =</span> .<span class="dv">5</span>) <span class="co"># add borders</span></span></code></pre></div>
<p><img src="09-gwr_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
</div>
</div>
<div id="fitting-a-geographically-weighted-regression" class="section level2" number="9.6">
<h2><span class="header-section-number">9.6</span> Fitting a Geographically Weighted Regression</h2>
<p>GWR overcomes the limitation of the OLS regression model of generating a global set of estimates. The basic idea behind GWR is to examine the way in which the relationships between a dependent variable and a set of predictors might vary over space. GWR operates by moving a search window from one regression point to the next, working sequentially through all the existing regression points in the dataset. A set of regions is then defined around each regression point and within the search window. A regression model is then fitted to all data contained in each of the identified regions around a regression point, with data points closer to the sample point being weighted more heavily than are those farther away. This process is repeated for all samples points in the dataset. For a data set of 150 observations GWR will fit 150 weighted regression models. The resulting local estimates can then be mapped at the locations of the regression points to view possible variations in the relationships between variables.</p>
<p>Graphically, GWR involves fitting a spatial kernel to the data as described in the Fig. 1. For a given regression point <span class="math inline">\(X\)</span>, the weight (<span class="math inline">\(W\)</span>) of a data point is at a maximum at the location of the regression point. The weight decreases gradually as the distance between two points increases. A regression model is thus calibrated locally by moving the regression point across the area under study. For each location, the data are weighted differently so that the resulting estimates are unique to a particular location.</p>
<div class="figure">
<img src="figs/ch8/fixed_bandwidth.png" alt="" />
<p class="caption">Fig. 1. GWR with fixed spatial kernel. Source: Fotheringham et al. <span class="citation">(<a href="references.html#ref-Fotheringham_et_al_2002_book" role="doc-biblioref">2002, 45</a>)</span>.</p>
</div>
<div id="fixed-or-adaptive-kernel" class="section level3" number="9.6.1">
<h3><span class="header-section-number">9.6.1</span> Fixed or Adaptive Kernel</h3>
<p>A key issue is to decide between two options of spatial kernels: a fixed kernel or an adaptive kernel. Intuitively, a fixed kernel involves using a fixed bandwidth to define a region around all regression points as displayed in Fig. 1. The extent of the kernel is determined by the distance to a given regression point, with the kernel being identical at any point in space. An adaptive kernel involves using varying bandwidth to define a region around regression points as displayed in Fig. 2. The extent of the kernel is determined by the number of nearest neighbours from a given regression point. The kernels have larger bandwidths where the data are sparse.</p>
<div class="figure">
<img src="figs/ch8/adaptive_bandwidth.png" alt="" />
<p class="caption">Fig. 2. GWR with adaptive spatial kernel. Source: Fotheringham et al. <span class="citation">(<a href="references.html#ref-Fotheringham_et_al_2002_book" role="doc-biblioref">2002, 47</a>)</span>.</p>
</div>
</div>
<div id="optimal-bandwidth" class="section level3" number="9.6.2">
<h3><span class="header-section-number">9.6.2</span> Optimal Bandwidth</h3>
<p>A second issue is to define the extent of geographical area (i.e. <em>optimal bandwidth</em>) of the spatial kernel. The bandwidth is the distance beyond which a value of zero is assigned to weight observations. Larger bandwidths include a larger number of observations receiving a non-zero weight and more observations are used to fit a local regression.</p>
<p>To determine the optimal bandwidth, a cross-validation approach is applied; that is, for a location, a local regression is fitted based on a given bandwidth and used to predict the value of the dependent variable. The resulting predicted value is used to compute the residuals of the model. Residuals are compared using a series of bandwidth and the bandwidth returning the smallest local residuals are selected.</p>
<p><strong>Variance and Bias Trade off</strong></p>
<p>Choosing an optimal bandwidth involves a compromise between bias and precision. For example, a larger bandwidth will involve using a larger number of observations to fit a local regression, and hence result in reduced variance (or increased precision) but high bias of estimates. On the other hand, too small bandwidth involves using a very small number of observations resulting in increased variance but small bias. An optimal bandwidth offers a compromise between bias and variance.</p>
</div>
<div id="shape-of-spatial-kernel" class="section level3" number="9.6.3">
<h3><span class="header-section-number">9.6.3</span> Shape of Spatial Kernel</h3>
<p>Two general set of kernel functions can be distinguished: continuous kernels and kernels with compact support. Continuous kernels are used to weight all observations in the study area and includes uniform, Gaussian and Exponential kernel functions. Kernel with compact support are used to assign a nonzero weight to observations within a certain distance and a zero weight beyond it. The shape of the kernel has been reported to cause small changes to resulting estimates <span class="citation">(<a href="references.html#ref-brunsdon1998geographically" role="doc-biblioref">Brunsdon, Fotheringham, and Charlton 1998</a>)</span>.</p>
</div>
<div id="selecting-a-bandwidth" class="section level3" number="9.6.4">
<h3><span class="header-section-number">9.6.4</span> Selecting a Bandwidth</h3>
<p>Let’s now implement a GWR model. The first key step is to define the optimal bandwidth. We first illustrate the use of a fixed spatial kernel.</p>
<div id="fixed-bandwidth" class="section level4" number="9.6.4.1">
<h4><span class="header-section-number">9.6.4.1</span> Fixed Bandwidth</h4>
<p>Cross-validation is used to search for the optimal bandwidth. Recall that this procedure compares the model residuals based on different bandwidths and chooses the optimal solution i.e. the bandwidth returning the smallest model residuals based on a given model specification. A key parameter here is the shape of the geographical weight function (<code>gweight</code>). We set it to be a Gaussian function which is the default. A bi-square function is recommended to reduce computational time. Since we have a simple model, a Gaussian function should not take that long. Note that we set the argument <code>longlat</code> to <code>TRUE</code> and use latitude and longitude for coordinates (<code>coords</code>). When <code>longlat</code> is set to <code>TRUE</code>, distances are measured in kilometres.</p>
<div class="sourceCode" id="cb364"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb364-1"><a href="gwr.html#cb364-1" aria-hidden="true" tabindex="-1"></a><span class="co"># find optimal kernel bandwidth using cross validation</span></span>
<span id="cb364-2"><a href="gwr.html#cb364-2" aria-hidden="true" tabindex="-1"></a>fbw <span class="ot">&lt;-</span> <span class="fu">gwr.sel</span>(eq1, </span>
<span id="cb364-3"><a href="gwr.html#cb364-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> utla_shp, </span>
<span id="cb364-4"><a href="gwr.html#cb364-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">coords=</span><span class="fu">cbind</span>( long, lat),</span>
<span id="cb364-5"><a href="gwr.html#cb364-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">longlat =</span> <span class="cn">TRUE</span>,</span>
<span id="cb364-6"><a href="gwr.html#cb364-6" aria-hidden="true" tabindex="-1"></a>               <span class="at">adapt=</span><span class="cn">FALSE</span>, </span>
<span id="cb364-7"><a href="gwr.html#cb364-7" aria-hidden="true" tabindex="-1"></a>               <span class="at">gweight =</span> gwr.Gauss, </span>
<span id="cb364-8"><a href="gwr.html#cb364-8" aria-hidden="true" tabindex="-1"></a>               <span class="at">verbose =</span> <span class="cn">FALSE</span>)</span>
<span id="cb364-9"><a href="gwr.html#cb364-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb364-10"><a href="gwr.html#cb364-10" aria-hidden="true" tabindex="-1"></a><span class="co"># view selected bandwidth</span></span>
<span id="cb364-11"><a href="gwr.html#cb364-11" aria-hidden="true" tabindex="-1"></a>fbw</span></code></pre></div>
<pre><code>## [1] 29.30417</code></pre>
<p>The result indicates that the optimal bandwidth is 39.79 kms. This means that neighbouring UTLAs within a fixed radius of 39.79 kms will be taken to estimate local regressions. To estimate a GWR, we execute the code below in which the optimal bandwidth above is used as an input in the argument <code>bandwidth</code>.</p>
<div class="sourceCode" id="cb366"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb366-1"><a href="gwr.html#cb366-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fit a gwr based on fixed bandwidth</span></span>
<span id="cb366-2"><a href="gwr.html#cb366-2" aria-hidden="true" tabindex="-1"></a>fb_gwr <span class="ot">&lt;-</span> <span class="fu">gwr</span>(eq1, </span>
<span id="cb366-3"><a href="gwr.html#cb366-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> utla_shp,</span>
<span id="cb366-4"><a href="gwr.html#cb366-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">coords=</span><span class="fu">cbind</span>( long, lat),</span>
<span id="cb366-5"><a href="gwr.html#cb366-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">longlat =</span> <span class="cn">TRUE</span>,</span>
<span id="cb366-6"><a href="gwr.html#cb366-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">bandwidth =</span> fbw, </span>
<span id="cb366-7"><a href="gwr.html#cb366-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">gweight =</span> gwr.Gauss,</span>
<span id="cb366-8"><a href="gwr.html#cb366-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">hatmatrix=</span><span class="cn">TRUE</span>, </span>
<span id="cb366-9"><a href="gwr.html#cb366-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">se.fit=</span><span class="cn">TRUE</span>)</span>
<span id="cb366-10"><a href="gwr.html#cb366-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb366-11"><a href="gwr.html#cb366-11" aria-hidden="true" tabindex="-1"></a>fb_gwr</span></code></pre></div>
<pre><code>## Call:
## gwr(formula = eq1, data = utla_shp, coords = cbind(long, lat), 
##     bandwidth = fbw, gweight = gwr.Gauss, hatmatrix = TRUE, longlat = TRUE, 
##     se.fit = TRUE)
## Kernel function: gwr.Gauss 
## Fixed bandwidth: 29.30417 
## Summary of GWR coefficient estimates at data points:
##                   Min.   1st Qu.    Median   3rd Qu.      Max.  Global
## X.Intercept.  -187.913   -42.890    93.702   211.685   792.989  63.768
## ethnic        -785.938   104.813   194.609   254.717  1078.854 271.096
## lt_illness   -2599.119  -563.128   128.176   690.603  1507.024 216.198
## Number of data points: 150 
## Effective number of parameters (residual: 2traceS - traceS&#39;S): 57.11019 
## Effective degrees of freedom (residual: 2traceS - traceS&#39;S): 92.88981 
## Sigma (residual: 2traceS - traceS&#39;S): 38.34777 
## Effective number of parameters (model: traceS): 44.65744 
## Effective degrees of freedom (model: traceS): 105.3426 
## Sigma (model: traceS): 36.00992 
## Sigma (ML): 30.17717 
## AICc (GWR p. 61, eq 2.33; p. 96, eq. 4.21): 1580.349 
## AIC (GWR p. 96, eq. 4.22): 1492.465 
## Residual sum of squares: 136599.2 
## Quasi-global R2: 0.7830537</code></pre>
<p>We will skip the interpretation of the results for now and consider them in the next section. Now, we want to focus on the overall model fit and will map the results of the <span class="math inline">\(R^{2}\)</span> for the estimated local regressions. To do this, we extract the model results stored in a Spatial Data Frame (SDF) and add them to our spatial data frame <code>utla_shp</code>. Note that the Quasi-global <span class="math inline">\(R^{2}\)</span> is very high (0.77) indicating a high in-sample prediction accuracy.</p>
<div class="sourceCode" id="cb368"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb368-1"><a href="gwr.html#cb368-1" aria-hidden="true" tabindex="-1"></a><span class="co"># write gwr output into a data frame</span></span>
<span id="cb368-2"><a href="gwr.html#cb368-2" aria-hidden="true" tabindex="-1"></a>fb_gwr_out <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(fb_gwr<span class="sc">$</span>SDF)</span>
<span id="cb368-3"><a href="gwr.html#cb368-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb368-4"><a href="gwr.html#cb368-4" aria-hidden="true" tabindex="-1"></a>utla_shp<span class="sc">$</span>fmb_localR2 <span class="ot">&lt;-</span> fb_gwr_out<span class="sc">$</span>localR2</span>
<span id="cb368-5"><a href="gwr.html#cb368-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb368-6"><a href="gwr.html#cb368-6" aria-hidden="true" tabindex="-1"></a><span class="co"># map</span></span>
<span id="cb368-7"><a href="gwr.html#cb368-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Local R2</span></span>
<span id="cb368-8"><a href="gwr.html#cb368-8" aria-hidden="true" tabindex="-1"></a>legend_title <span class="ot">=</span> <span class="fu">expression</span>(<span class="st">&quot;Fixed: Local R2&quot;</span>)</span>
<span id="cb368-9"><a href="gwr.html#cb368-9" aria-hidden="true" tabindex="-1"></a>map_fbgwr1 <span class="ot">=</span> <span class="fu">tm_shape</span>(utla_shp) <span class="sc">+</span></span>
<span id="cb368-10"><a href="gwr.html#cb368-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">&quot;fmb_localR2&quot;</span>, <span class="at">title =</span> legend_title, <span class="at">palette =</span> <span class="fu">magma</span>(<span class="dv">256</span>), <span class="at">style =</span> <span class="st">&quot;cont&quot;</span>) <span class="sc">+</span> <span class="co"># add fill</span></span>
<span id="cb368-11"><a href="gwr.html#cb368-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">&quot;white&quot;</span>, <span class="at">lwd =</span> .<span class="dv">1</span>)  <span class="sc">+</span> <span class="co"># add borders</span></span>
<span id="cb368-12"><a href="gwr.html#cb368-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_compass</span>(<span class="at">type =</span> <span class="st">&quot;arrow&quot;</span>, <span class="at">position =</span> <span class="fu">c</span>(<span class="st">&quot;right&quot;</span>, <span class="st">&quot;top&quot;</span>) , <span class="at">size =</span> <span class="dv">5</span>) <span class="sc">+</span> <span class="co"># add compass</span></span>
<span id="cb368-13"><a href="gwr.html#cb368-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_scale_bar</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">2</span>), <span class="at">text.size =</span> <span class="fl">0.7</span>, <span class="at">position =</span>  <span class="fu">c</span>(<span class="st">&quot;center&quot;</span>, <span class="st">&quot;bottom&quot;</span>)) <span class="sc">+</span> <span class="co"># add scale bar</span></span>
<span id="cb368-14"><a href="gwr.html#cb368-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">bg.color =</span> <span class="st">&quot;white&quot;</span>) <span class="co"># change background colour</span></span>
<span id="cb368-15"><a href="gwr.html#cb368-15" aria-hidden="true" tabindex="-1"></a>map_fbgwr1 <span class="sc">+</span> <span class="fu">tm_shape</span>(reg_shp) <span class="sc">+</span> <span class="co"># add region boundaries</span></span>
<span id="cb368-16"><a href="gwr.html#cb368-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">&quot;white&quot;</span>, <span class="at">lwd =</span> .<span class="dv">5</span>) <span class="co"># add borders</span></span></code></pre></div>
<p><img src="09-gwr_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>The map shows very high in-sample model predictions of up to 80% in relatively large UTLAs (i.e. Cornwall, Devon and Cumbria) but poor predictions in Linconshire and small UTLAs in the North West and Yorkshire &amp; The Humber Regions and the Greater London. The spatial distribution of this pattern may reflect a potential problem that arise in the application of GWR with fixed spatial kernels. The use of fixed kernels implies that local regressions for small spatial units may be calibrated on a large number of dissimilar areas, while local regressions for large areas may be calibrated on very few data points, giving rise to estimates with large standard errors. In extreme cases, generating estimates might not be possible due to insufficient variation in small samples. In practice, this issue is relatively common if the number of geographical areas in the dataset is small.</p>
</div>
<div id="adaptive-bandwidth" class="section level4" number="9.6.4.2">
<h4><span class="header-section-number">9.6.4.2</span> Adaptive Bandwidth</h4>
<p>To reduce these problems, adaptive spatial kernels can be used. These kernels adapt in size to variations in the density of the data so that the kernels have larger bandwidths where the data are sparse and have smaller bandwidths where the data are plentiful. As above, we first need to search for the optimal bandwidth before estimating a GWR.</p>
<div class="sourceCode" id="cb369"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb369-1"><a href="gwr.html#cb369-1" aria-hidden="true" tabindex="-1"></a><span class="co"># find optimal kernel bandwidth using cross validation</span></span>
<span id="cb369-2"><a href="gwr.html#cb369-2" aria-hidden="true" tabindex="-1"></a>abw <span class="ot">&lt;-</span> <span class="fu">gwr.sel</span>(eq1, </span>
<span id="cb369-3"><a href="gwr.html#cb369-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> utla_shp, </span>
<span id="cb369-4"><a href="gwr.html#cb369-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">coords=</span><span class="fu">cbind</span>( long, lat),</span>
<span id="cb369-5"><a href="gwr.html#cb369-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">longlat =</span> <span class="cn">TRUE</span>,</span>
<span id="cb369-6"><a href="gwr.html#cb369-6" aria-hidden="true" tabindex="-1"></a>               <span class="at">adapt =</span> <span class="cn">TRUE</span>, </span>
<span id="cb369-7"><a href="gwr.html#cb369-7" aria-hidden="true" tabindex="-1"></a>               <span class="at">gweight =</span> gwr.Gauss, </span>
<span id="cb369-8"><a href="gwr.html#cb369-8" aria-hidden="true" tabindex="-1"></a>               <span class="at">verbose =</span> <span class="cn">FALSE</span>)</span>
<span id="cb369-9"><a href="gwr.html#cb369-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb369-10"><a href="gwr.html#cb369-10" aria-hidden="true" tabindex="-1"></a><span class="co"># view selected bandwidth</span></span>
<span id="cb369-11"><a href="gwr.html#cb369-11" aria-hidden="true" tabindex="-1"></a>abw</span></code></pre></div>
<pre><code>## [1] 0.03126972</code></pre>
<p>The optimal bandwidth is 0.03 indicating the proportion of observations (or k-nearest neighbours) to be included in the weighting scheme. In this example, the optimal bandwidth indicates that for a given UTLA, 3% of its nearest neighbours should be used to calibrate the relevant local regression; that is about 5 UTLAs. The search window will thus be variable in size depending on the extent of UTLAs. Note that here the optimal bandwidth is defined based on a data point’s k-nearest neighbours. It can also be defined by geographical distance as done above for the fixed spatial kernel. We next fit a GWR based on an adaptive bandwidth.</p>
<div class="sourceCode" id="cb371"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb371-1"><a href="gwr.html#cb371-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fit a gwr based on adaptive bandwidth</span></span>
<span id="cb371-2"><a href="gwr.html#cb371-2" aria-hidden="true" tabindex="-1"></a>ab_gwr <span class="ot">&lt;-</span> <span class="fu">gwr</span>(eq1, </span>
<span id="cb371-3"><a href="gwr.html#cb371-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> utla_shp,</span>
<span id="cb371-4"><a href="gwr.html#cb371-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">coords=</span><span class="fu">cbind</span>( long, lat),</span>
<span id="cb371-5"><a href="gwr.html#cb371-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">longlat =</span> <span class="cn">TRUE</span>,</span>
<span id="cb371-6"><a href="gwr.html#cb371-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">adapt =</span> abw, </span>
<span id="cb371-7"><a href="gwr.html#cb371-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">gweight =</span> gwr.Gauss,</span>
<span id="cb371-8"><a href="gwr.html#cb371-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">hatmatrix=</span><span class="cn">TRUE</span>, </span>
<span id="cb371-9"><a href="gwr.html#cb371-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">se.fit=</span><span class="cn">TRUE</span>)</span>
<span id="cb371-10"><a href="gwr.html#cb371-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb371-11"><a href="gwr.html#cb371-11" aria-hidden="true" tabindex="-1"></a>ab_gwr</span></code></pre></div>
<pre><code>## Call:
## gwr(formula = eq1, data = utla_shp, coords = cbind(long, lat), 
##     gweight = gwr.Gauss, adapt = abw, hatmatrix = TRUE, longlat = TRUE, 
##     se.fit = TRUE)
## Kernel function: gwr.Gauss 
## Adaptive quantile: 0.03126972 (about 4 of 150 data points)
## Summary of GWR coefficient estimates at data points:
##                   Min.   1st Qu.    Median   3rd Qu.      Max.  Global
## X.Intercept.  -198.790   -28.398   113.961   226.437   346.510  63.768
## ethnic        -121.872   106.822   229.591   283.739  1162.123 271.096
## lt_illness   -1907.098  -746.468  -125.855   798.875  1496.549 216.198
## Number of data points: 150 
## Effective number of parameters (residual: 2traceS - traceS&#39;S): 48.59361 
## Effective degrees of freedom (residual: 2traceS - traceS&#39;S): 101.4064 
## Sigma (residual: 2traceS - traceS&#39;S): 36.57493 
## Effective number of parameters (model: traceS): 36.04378 
## Effective degrees of freedom (model: traceS): 113.9562 
## Sigma (model: traceS): 34.50222 
## Sigma (ML): 30.07257 
## AICc (GWR p. 61, eq 2.33; p. 96, eq. 4.21): 1546.029 
## AIC (GWR p. 96, eq. 4.22): 1482.809 
## Residual sum of squares: 135653.9 
## Quasi-global R2: 0.7845551</code></pre>
</div>
</div>
<div id="model-fit" class="section level3" number="9.6.5">
<h3><span class="header-section-number">9.6.5</span> Model fit</h3>
<p>Assessing the global fit of the model, marginal improvements are observed. The <span class="math inline">\(AIC\)</span> and <em>Residual sum of squares</em> experienced marginal reductions, while the <span class="math inline">\(R^{2}\)</span> increased compared to the GRW based on a fixed kernel. To gain a better understanding of these changes, as above, we map the <span class="math inline">\(R^{2}\)</span> values for the estimated local regressions.</p>
<div class="sourceCode" id="cb373"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb373-1"><a href="gwr.html#cb373-1" aria-hidden="true" tabindex="-1"></a><span class="co"># write gwr output into a data frame</span></span>
<span id="cb373-2"><a href="gwr.html#cb373-2" aria-hidden="true" tabindex="-1"></a>ab_gwr_out <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(ab_gwr<span class="sc">$</span>SDF)</span>
<span id="cb373-3"><a href="gwr.html#cb373-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb373-4"><a href="gwr.html#cb373-4" aria-hidden="true" tabindex="-1"></a>utla_shp<span class="sc">$</span>amb_ethnic <span class="ot">&lt;-</span> ab_gwr_out<span class="sc">$</span>ethnic</span>
<span id="cb373-5"><a href="gwr.html#cb373-5" aria-hidden="true" tabindex="-1"></a>utla_shp<span class="sc">$</span>amb_lt_illness <span class="ot">&lt;-</span> ab_gwr_out<span class="sc">$</span>lt_illness</span>
<span id="cb373-6"><a href="gwr.html#cb373-6" aria-hidden="true" tabindex="-1"></a>utla_shp<span class="sc">$</span>amb_localR2 <span class="ot">&lt;-</span> ab_gwr_out<span class="sc">$</span>localR2</span>
<span id="cb373-7"><a href="gwr.html#cb373-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb373-8"><a href="gwr.html#cb373-8" aria-hidden="true" tabindex="-1"></a><span class="co"># map</span></span>
<span id="cb373-9"><a href="gwr.html#cb373-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Local R2</span></span>
<span id="cb373-10"><a href="gwr.html#cb373-10" aria-hidden="true" tabindex="-1"></a>legend_title <span class="ot">=</span> <span class="fu">expression</span>(<span class="st">&quot;Adaptive: Local R2&quot;</span>)</span>
<span id="cb373-11"><a href="gwr.html#cb373-11" aria-hidden="true" tabindex="-1"></a>map_abgwr1 <span class="ot">=</span> <span class="fu">tm_shape</span>(utla_shp) <span class="sc">+</span></span>
<span id="cb373-12"><a href="gwr.html#cb373-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">&quot;amb_localR2&quot;</span>, <span class="at">title =</span> legend_title, <span class="at">palette =</span> <span class="fu">magma</span>(<span class="dv">256</span>), <span class="at">style =</span> <span class="st">&quot;cont&quot;</span>) <span class="sc">+</span> <span class="co"># add fill</span></span>
<span id="cb373-13"><a href="gwr.html#cb373-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">&quot;white&quot;</span>, <span class="at">lwd =</span> .<span class="dv">1</span>)  <span class="sc">+</span> <span class="co"># add borders</span></span>
<span id="cb373-14"><a href="gwr.html#cb373-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_compass</span>(<span class="at">type =</span> <span class="st">&quot;arrow&quot;</span>, <span class="at">position =</span> <span class="fu">c</span>(<span class="st">&quot;right&quot;</span>, <span class="st">&quot;top&quot;</span>) , <span class="at">size =</span> <span class="dv">5</span>) <span class="sc">+</span> <span class="co"># add compass</span></span>
<span id="cb373-15"><a href="gwr.html#cb373-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_scale_bar</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">2</span>), <span class="at">text.size =</span> <span class="fl">0.7</span>, <span class="at">position =</span>  <span class="fu">c</span>(<span class="st">&quot;center&quot;</span>, <span class="st">&quot;bottom&quot;</span>)) <span class="sc">+</span> <span class="co"># add scale bar</span></span>
<span id="cb373-16"><a href="gwr.html#cb373-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">bg.color =</span> <span class="st">&quot;white&quot;</span>) <span class="co"># change background colour</span></span>
<span id="cb373-17"><a href="gwr.html#cb373-17" aria-hidden="true" tabindex="-1"></a>map_abgwr1 <span class="sc">+</span> <span class="fu">tm_shape</span>(reg_shp) <span class="sc">+</span> <span class="co"># add region boundaries</span></span>
<span id="cb373-18"><a href="gwr.html#cb373-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">&quot;white&quot;</span>, <span class="at">lwd =</span> .<span class="dv">5</span>) <span class="co"># add borders</span></span></code></pre></div>
<p><img src="09-gwr_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>The map reveals notable improvements in local estimates for UTLAs within West and East Midlands, the South East, South West and East of England. Estimates are still poor in hot spot UTLAs concentrating confirmed cases of COVID-19, such as the Greater London, Liverpool and Newcastle areas.</p>
</div>
<div id="interpretation-1" class="section level3" number="9.6.6">
<h3><span class="header-section-number">9.6.6</span> Interpretation</h3>
<p>The key strength of GWR models is in identifying patterns of spatial variation in the associations between pairs of variables. The results reveal how these coefficients vary across the 150 UTLAs of England. To examine this variability, let’s first focus on the adaptive GWR output reported in Section 8.6.4.2. The output includes a summary of GWR coefficient estimates at various data points. The last column reports the global estimates which are the same as the coefficients from the OLS regression we fitted at the start of our analysis. For our variable nonwhite ethnic population, the GWR outputs reveals that local coefficients range from a minimum value of -148.41 to a maximum value of 1076.84, indicating that one percentage point increase in the share of nonwhite ethnic population is associated with a a reduction of 148.41 in the number of cumulative confirmed cases of COVID-19 per 100,000 people in some UTLAs and an increase of 1076.84 in others. For half of the UTLAs in the dataset, as the share of nonwhite ethnic population increases by one percentage point, the rate of COVID-19 will increase between 106.29 and 291.24 cases; that is, the inter-quartile range between the 1st Qu and the 3rd Qu. To analyse the spatial structure, we next map the estimated coefficients obtained from the adaptive kernel GWR.</p>
<div class="sourceCode" id="cb374"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb374-1"><a href="gwr.html#cb374-1" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Ethnic</span></span>
<span id="cb374-2"><a href="gwr.html#cb374-2" aria-hidden="true" tabindex="-1"></a>legend_title <span class="ot">=</span> <span class="fu">expression</span>(<span class="st">&quot;Ethnic&quot;</span>)</span>
<span id="cb374-3"><a href="gwr.html#cb374-3" aria-hidden="true" tabindex="-1"></a>map_abgwr2 <span class="ot">=</span> <span class="fu">tm_shape</span>(utla_shp) <span class="sc">+</span></span>
<span id="cb374-4"><a href="gwr.html#cb374-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">&quot;amb_ethnic&quot;</span>, <span class="at">title =</span> legend_title, <span class="at">palette =</span> <span class="fu">magma</span>(<span class="dv">256</span>), <span class="at">style =</span> <span class="st">&quot;cont&quot;</span>) <span class="sc">+</span> <span class="co"># add fill</span></span>
<span id="cb374-5"><a href="gwr.html#cb374-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">&quot;white&quot;</span>, <span class="at">lwd =</span> .<span class="dv">1</span>)  <span class="sc">+</span> <span class="co"># add borders</span></span>
<span id="cb374-6"><a href="gwr.html#cb374-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_compass</span>(<span class="at">type =</span> <span class="st">&quot;arrow&quot;</span>, <span class="at">position =</span> <span class="fu">c</span>(<span class="st">&quot;right&quot;</span>, <span class="st">&quot;top&quot;</span>) , <span class="at">size =</span> <span class="dv">5</span>) <span class="sc">+</span> <span class="co"># add compass</span></span>
<span id="cb374-7"><a href="gwr.html#cb374-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_scale_bar</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">2</span>), <span class="at">text.size =</span> <span class="fl">0.7</span>, <span class="at">position =</span>  <span class="fu">c</span>(<span class="st">&quot;center&quot;</span>, <span class="st">&quot;bottom&quot;</span>)) <span class="sc">+</span> <span class="co"># add scale bar</span></span>
<span id="cb374-8"><a href="gwr.html#cb374-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">bg.color =</span> <span class="st">&quot;white&quot;</span>) <span class="co"># change background colour</span></span>
<span id="cb374-9"><a href="gwr.html#cb374-9" aria-hidden="true" tabindex="-1"></a>map_abgwr2 <span class="ot">=</span> map_abgwr2 <span class="sc">+</span> <span class="fu">tm_shape</span>(reg_shp) <span class="sc">+</span> <span class="co"># add region boundaries</span></span>
<span id="cb374-10"><a href="gwr.html#cb374-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">&quot;white&quot;</span>, <span class="at">lwd =</span> .<span class="dv">5</span>) <span class="co"># add borders</span></span>
<span id="cb374-11"><a href="gwr.html#cb374-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb374-12"><a href="gwr.html#cb374-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Long-term Illness</span></span>
<span id="cb374-13"><a href="gwr.html#cb374-13" aria-hidden="true" tabindex="-1"></a>legend_title <span class="ot">=</span> <span class="fu">expression</span>(<span class="st">&quot;Long-term illness&quot;</span>)</span>
<span id="cb374-14"><a href="gwr.html#cb374-14" aria-hidden="true" tabindex="-1"></a>map_abgwr3 <span class="ot">=</span> <span class="fu">tm_shape</span>(utla_shp) <span class="sc">+</span></span>
<span id="cb374-15"><a href="gwr.html#cb374-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">&quot;amb_lt_illness&quot;</span>, <span class="at">title =</span> legend_title, <span class="at">palette =</span> <span class="fu">magma</span>(<span class="dv">256</span>), <span class="at">style =</span> <span class="st">&quot;cont&quot;</span>) <span class="sc">+</span> <span class="co"># add fill</span></span>
<span id="cb374-16"><a href="gwr.html#cb374-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">&quot;white&quot;</span>, <span class="at">lwd =</span> .<span class="dv">1</span>)  <span class="sc">+</span> <span class="co"># add borders</span></span>
<span id="cb374-17"><a href="gwr.html#cb374-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_scale_bar</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">2</span>), <span class="at">text.size =</span> <span class="fl">0.7</span>, <span class="at">position =</span>  <span class="fu">c</span>(<span class="st">&quot;center&quot;</span>, <span class="st">&quot;bottom&quot;</span>)) <span class="sc">+</span> <span class="co"># add scale bar</span></span>
<span id="cb374-18"><a href="gwr.html#cb374-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">bg.color =</span> <span class="st">&quot;white&quot;</span>) <span class="co"># change background colour</span></span>
<span id="cb374-19"><a href="gwr.html#cb374-19" aria-hidden="true" tabindex="-1"></a>map_abgwr3 <span class="ot">=</span> map_abgwr3 <span class="sc">+</span> <span class="fu">tm_shape</span>(reg_shp) <span class="sc">+</span> <span class="co"># add region boundaries</span></span>
<span id="cb374-20"><a href="gwr.html#cb374-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">&quot;white&quot;</span>, <span class="at">lwd =</span> .<span class="dv">5</span>) <span class="co"># add borders</span></span>
<span id="cb374-21"><a href="gwr.html#cb374-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb374-22"><a href="gwr.html#cb374-22" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(map_abgwr2, map_abgwr3)</span></code></pre></div>
<p><img src="09-gwr_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>Analysing the map for long-term illness, a clear North-South divide can be identified. In the North we observed the expected positive relationship between COVID-19 and long-term illness i.e. as the share of the local population suffering from long-term illness rises, the cumulative number of positive COVID-19 cases is expected to increase. In the South, we observe the inverse pattern i.e. as the share of local population suffering from long-term illness rises, the cumulative number of positive COVID-19 cases is expected to drop. This pattern is counterintuitive but may be explained by the wider socio-economic disadvantages between the North and the South of England. The North is usually characterised by a persistent concentration of more disadvantaged neighbourhoods than the South where affluent households have tended to cluster for the last 40 years <span class="citation">(<a href="references.html#ref-rowe2020policy" role="doc-biblioref">Rowe, Patias, and Arribas-Bel 2020</a>)</span>.</p>
</div>
<div id="assessing-statistical-significance" class="section level3" number="9.6.7">
<h3><span class="header-section-number">9.6.7</span> Assessing statistical significance</h3>
<p>While the maps above offer valuable insights to understand the spatial pattering of relationships, they do not identify whether these associations are statistically significant. They may not be. Roughly, if a coefficient estimate has an absolute value of t greater than 1.96 and the sample is sufficiently large, then it is statistically significant. Our sample has only 150 observations, so we are more conservative and considered a coefficient to be statistically significant if it has an absolute value of t larger than 2. Note also that p-values could be computed - see <span class="citation"><a href="references.html#ref-lu2014gwmodel" role="doc-biblioref">Lu et al.</a> (<a href="references.html#ref-lu2014gwmodel" role="doc-biblioref">2014</a>)</span>.</p>
<div class="sourceCode" id="cb375"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb375-1"><a href="gwr.html#cb375-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compute t statistic</span></span>
<span id="cb375-2"><a href="gwr.html#cb375-2" aria-hidden="true" tabindex="-1"></a>utla_shp<span class="sc">$</span>t_ethnic <span class="ot">=</span> ab_gwr_out<span class="sc">$</span>ethnic <span class="sc">/</span> ab_gwr_out<span class="sc">$</span>ethnic_se</span>
<span id="cb375-3"><a href="gwr.html#cb375-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb375-4"><a href="gwr.html#cb375-4" aria-hidden="true" tabindex="-1"></a><span class="co"># categorise t values</span></span>
<span id="cb375-5"><a href="gwr.html#cb375-5" aria-hidden="true" tabindex="-1"></a>utla_shp<span class="sc">$</span>t_ethnic_cat <span class="ot">&lt;-</span> <span class="fu">cut</span>(utla_shp<span class="sc">$</span>t_ethnic,</span>
<span id="cb375-6"><a href="gwr.html#cb375-6" aria-hidden="true" tabindex="-1"></a>                     <span class="at">breaks=</span><span class="fu">c</span>(<span class="fu">min</span>(utla_shp<span class="sc">$</span>t_ethnic), <span class="sc">-</span><span class="dv">2</span>, <span class="dv">2</span>, <span class="fu">max</span>(utla_shp<span class="sc">$</span>t_ethnic)),</span>
<span id="cb375-7"><a href="gwr.html#cb375-7" aria-hidden="true" tabindex="-1"></a>                     <span class="at">labels=</span><span class="fu">c</span>(<span class="st">&quot;sig&quot;</span>,<span class="st">&quot;nonsig&quot;</span>, <span class="st">&quot;sig&quot;</span>))</span>
<span id="cb375-8"><a href="gwr.html#cb375-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb375-9"><a href="gwr.html#cb375-9" aria-hidden="true" tabindex="-1"></a><span class="co"># map statistically significant coefs for ethnic</span></span>
<span id="cb375-10"><a href="gwr.html#cb375-10" aria-hidden="true" tabindex="-1"></a>legend_title <span class="ot">=</span> <span class="fu">expression</span>(<span class="st">&quot;Ethnic: significant&quot;</span>)</span>
<span id="cb375-11"><a href="gwr.html#cb375-11" aria-hidden="true" tabindex="-1"></a>map_sig <span class="ot">=</span> <span class="fu">tm_shape</span>(utla_shp) <span class="sc">+</span> </span>
<span id="cb375-12"><a href="gwr.html#cb375-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">&quot;t_ethnic_cat&quot;</span>, <span class="at">title =</span> legend_title, <span class="at">legend.hist =</span> <span class="cn">TRUE</span>, <span class="at">midpoint =</span> <span class="cn">NA</span>, <span class="at">textNA =</span> <span class="st">&quot;&quot;</span>, <span class="at">colorNA =</span> <span class="st">&quot;white&quot;</span>) <span class="sc">+</span>  <span class="co"># add fill</span></span>
<span id="cb375-13"><a href="gwr.html#cb375-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">&quot;white&quot;</span>, <span class="at">lwd =</span> .<span class="dv">1</span>)  <span class="sc">+</span> <span class="co"># add borders</span></span>
<span id="cb375-14"><a href="gwr.html#cb375-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_compass</span>(<span class="at">type =</span> <span class="st">&quot;arrow&quot;</span>, <span class="at">position =</span> <span class="fu">c</span>(<span class="st">&quot;right&quot;</span>, <span class="st">&quot;top&quot;</span>) , <span class="at">size =</span> <span class="dv">5</span>) <span class="sc">+</span> <span class="co"># add compass</span></span>
<span id="cb375-15"><a href="gwr.html#cb375-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_scale_bar</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">2</span>), <span class="at">text.size =</span> <span class="fl">0.7</span>, <span class="at">position =</span>  <span class="fu">c</span>(<span class="st">&quot;center&quot;</span>, <span class="st">&quot;bottom&quot;</span>)) <span class="sc">+</span> <span class="co"># add scale bar</span></span>
<span id="cb375-16"><a href="gwr.html#cb375-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">bg.color =</span> <span class="st">&quot;white&quot;</span>, <span class="at">legend.outside =</span> <span class="cn">TRUE</span>) <span class="co"># change background colour &amp; place legend outside</span></span>
<span id="cb375-17"><a href="gwr.html#cb375-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb375-18"><a href="gwr.html#cb375-18" aria-hidden="true" tabindex="-1"></a>map_sig <span class="sc">+</span> <span class="fu">tm_shape</span>(reg_shp) <span class="sc">+</span> <span class="co"># add region boundaries</span></span>
<span id="cb375-19"><a href="gwr.html#cb375-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">&quot;white&quot;</span>, <span class="at">lwd =</span> .<span class="dv">5</span>) <span class="co"># add borders</span></span></code></pre></div>
<p><img src="09-gwr_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<div class="sourceCode" id="cb376"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb376-1"><a href="gwr.html#cb376-1" aria-hidden="true" tabindex="-1"></a><span class="co"># utla count</span></span>
<span id="cb376-2"><a href="gwr.html#cb376-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(utla_shp<span class="sc">$</span>t_ethnic_cat)</span></code></pre></div>
<pre><code>## 
##    sig nonsig 
##    105     45</code></pre>
<p>For the share of nonwhite population, 67% of all local coefficients are statistically significant and these are largely in the South of England. Coefficients in the North tend to be insignificant. Through outliers exist in both regions. In the South, nonsignificant coefficients are observed in the metropolitan areas of London, Birmingham and Nottingham, while significant coefficients exist in the areas of Newcastle and Middlesbrough in the North.</p>
<blockquote>
<p>Challenge 3
Compute the t values for the intercept and estimated coefficient for long-term illness and create maps of their statistical significance.
How many UTLAs report statistically significant coefficients?</p>
</blockquote>
</div>
<div id="collinearity-in-gwr" class="section level3" number="9.6.8">
<h3><span class="header-section-number">9.6.8</span> Collinearity in GWR</h3>
<p>An important final note is: collinearity tends to be problematic in GWR models. It can be present in the data subsets to estimate local coefficients even when not observed globally <span class="citation"><a href="references.html#ref-wheeler2005multicollinearity" role="doc-biblioref">Wheeler and Tiefelsdorf</a> (<a href="references.html#ref-wheeler2005multicollinearity" role="doc-biblioref">2005</a>)</span>. Collinearity can be highly problematic in the case of compositional, categorical and ordinal predictors, and may result in exact local collinearity making the search for an optimal bandwidth impossible. A recent paper suggests potential ways forward <span class="citation">(<a href="references.html#ref-comber2020gwr" role="doc-biblioref">Comber et al. 2020</a>)</span>.</p>
</div>
</div>
<div id="questions-5" class="section level2" number="9.7">
<h2><span class="header-section-number">9.7</span> Questions</h2>
<p>We will continue to use the COVID-19 dataset. Please see Chapter <a href="datasets.html#datasets">11</a> for details on the data.</p>
<div class="sourceCode" id="cb378"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb378-1"><a href="gwr.html#cb378-1" aria-hidden="true" tabindex="-1"></a>sdf <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">&quot;data/assignment_2_covid/covid19_eng.gpkg&quot;</span>)</span></code></pre></div>
<pre><code>## Reading layer `covid19_eng&#39; from data source `/home/jovyan/work/data/assignment_2_covid/covid19_eng.gpkg&#39; using driver `GPKG&#39;
## Simple feature collection with 149 features and 507 fields
## geometry type:  MULTIPOLYGON
## dimension:      XY
## bbox:           xmin: 134112.4 ymin: 11429.67 xmax: 655653.8 ymax: 657536
## projected CRS:  OSGB 1936 / British National Grid</code></pre>
<p>Using these data, you are required to address the following challenges:</p>
<ul>
<li><p>Fit a GWR model using a fixed and an adaptive bandwidth.</p></li>
<li><p>Create a multiple map figure to analyse the spatial variation of coefficients.</p></li>
</ul>
<p>Analyse and discuss:</p>
<ol style="list-style-type: decimal">
<li>How regression coefficients vary across space. Do they vary in size and statistical significance?</li>
<li>What is the appropriate bandwidth for your GWR? Why?</li>
</ol>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="27">
<li id="fn27"><p>Read the file in R by executing <code>read_tsv("data/gwr/readme.txt")</code><a href="gwr.html#fnref27" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="mlm2.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="sta.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": null,
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["spatial_analysis_notes.pdf", "spatial_analysis_notes.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
