<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 6 Spatial Econometrics | Spatial Modelling for Data Scientists</title>
  <meta name="description" content="This course will teach you how to analyse and model spatial data using R." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 6 Spatial Econometrics | Spatial Modelling for Data Scientists" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This course will teach you how to analyse and model spatial data using R." />
  <meta name="github-repo" content="gdsl-ul/san" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 6 Spatial Econometrics | Spatial Modelling for Data Scientists" />
  
  <meta name="twitter:description" content="This course will teach you how to analyse and model spatial data using R." />
  

<meta name="author" content="Francisco Rowe and Dani Arribas-Bel" />


<meta name="date" content="2022-01-24" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="flows.html"/>
<link rel="next" href="mlm1.html"/>
<script src="libs/header-attrs-2.6/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Spatial Modelling for Data Scientists</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#contact"><i class="fa fa-check"></i>Contact</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="overview.html"><a href="overview.html"><i class="fa fa-check"></i><b>1</b> Overview</a>
<ul>
<li class="chapter" data-level="1.1" data-path="overview.html"><a href="overview.html#aims"><i class="fa fa-check"></i><b>1.1</b> Aims</a></li>
<li class="chapter" data-level="1.2" data-path="overview.html"><a href="overview.html#learning-outcomes"><i class="fa fa-check"></i><b>1.2</b> Learning Outcomes</a></li>
<li class="chapter" data-level="1.3" data-path="overview.html"><a href="overview.html#feedback"><i class="fa fa-check"></i><b>1.3</b> Feedback</a></li>
<li class="chapter" data-level="1.4" data-path="overview.html"><a href="overview.html#computational-environment"><i class="fa fa-check"></i><b>1.4</b> Computational Environment</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="overview.html"><a href="overview.html#dependency-list"><i class="fa fa-check"></i><b>1.4.1</b> Dependency list</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="overview.html"><a href="overview.html#assessment"><i class="fa fa-check"></i><b>1.5</b> Assessment</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="overview.html"><a href="overview.html#format-requirements"><i class="fa fa-check"></i><b>1.5.1</b> Format Requirements</a></li>
<li class="chapter" data-level="1.5.2" data-path="overview.html"><a href="overview.html#marking-criteria"><i class="fa fa-check"></i><b>1.5.2</b> Marking criteria</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="spatial-data.html"><a href="spatial-data.html"><i class="fa fa-check"></i><b>2</b> Spatial Data</a>
<ul>
<li class="chapter" data-level="2.1" data-path="spatial-data.html"><a href="spatial-data.html#spatial-data-types"><i class="fa fa-check"></i><b>2.1</b> Spatial Data types</a></li>
<li class="chapter" data-level="2.2" data-path="spatial-data.html"><a href="spatial-data.html#hierarchical-structure-of-data"><i class="fa fa-check"></i><b>2.2</b> Hierarchical Structure of Data</a></li>
<li class="chapter" data-level="2.3" data-path="spatial-data.html"><a href="spatial-data.html#key-challenges"><i class="fa fa-check"></i><b>2.3</b> Key Challenges</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="spatial-data.html"><a href="spatial-data.html#modifible-area-unit-problem-maup"><i class="fa fa-check"></i><b>2.3.1</b> Modifible Area Unit Problem (MAUP)</a></li>
<li class="chapter" data-level="2.3.2" data-path="spatial-data.html"><a href="spatial-data.html#ecological-fallacy"><i class="fa fa-check"></i><b>2.3.2</b> Ecological Fallacy</a></li>
<li class="chapter" data-level="2.3.3" data-path="spatial-data.html"><a href="spatial-data.html#spatial-dependence"><i class="fa fa-check"></i><b>2.3.3</b> Spatial Dependence</a></li>
<li class="chapter" data-level="2.3.4" data-path="spatial-data.html"><a href="spatial-data.html#spatial-heterogeneity"><i class="fa fa-check"></i><b>2.3.4</b> Spatial Heterogeneity</a></li>
<li class="chapter" data-level="2.3.5" data-path="spatial-data.html"><a href="spatial-data.html#spatial-nonstationarity"><i class="fa fa-check"></i><b>2.3.5</b> Spatial nonstationarity</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-wrangling.html"><a href="data-wrangling.html"><i class="fa fa-check"></i><b>3</b> Data Wrangling</a>
<ul>
<li class="chapter" data-level="3.1" data-path="data-wrangling.html"><a href="data-wrangling.html#dependencies"><i class="fa fa-check"></i><b>3.1</b> Dependencies</a></li>
<li class="chapter" data-level="3.2" data-path="data-wrangling.html"><a href="data-wrangling.html#introducing-r"><i class="fa fa-check"></i><b>3.2</b> Introducing R</a></li>
<li class="chapter" data-level="3.3" data-path="data-wrangling.html"><a href="data-wrangling.html#setting-the-working-directory"><i class="fa fa-check"></i><b>3.3</b> Setting the working directory</a></li>
<li class="chapter" data-level="3.4" data-path="data-wrangling.html"><a href="data-wrangling.html#r-scripts-and-notebooks"><i class="fa fa-check"></i><b>3.4</b> R Scripts and Notebooks</a></li>
<li class="chapter" data-level="3.5" data-path="data-wrangling.html"><a href="data-wrangling.html#getting-help"><i class="fa fa-check"></i><b>3.5</b> Getting Help</a></li>
<li class="chapter" data-level="3.6" data-path="data-wrangling.html"><a href="data-wrangling.html#variables-and-objects"><i class="fa fa-check"></i><b>3.6</b> Variables and objects</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="data-wrangling.html"><a href="data-wrangling.html#basic-data-types"><i class="fa fa-check"></i><b>3.6.1</b> Basic Data Types</a></li>
<li class="chapter" data-level="3.6.2" data-path="data-wrangling.html"><a href="data-wrangling.html#random-variables"><i class="fa fa-check"></i><b>3.6.2</b> Random Variables</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="data-wrangling.html"><a href="data-wrangling.html#data-frames"><i class="fa fa-check"></i><b>3.7</b> Data Frames</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="data-wrangling.html"><a href="data-wrangling.html#creating-a-data-frame"><i class="fa fa-check"></i><b>3.7.1</b> Creating A Data Frame</a></li>
<li class="chapter" data-level="3.7.2" data-path="data-wrangling.html"><a href="data-wrangling.html#referencing-data-frames"><i class="fa fa-check"></i><b>3.7.2</b> Referencing Data Frames</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="data-wrangling.html"><a href="data-wrangling.html#sec_readdata"><i class="fa fa-check"></i><b>3.8</b> Read Data</a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="data-wrangling.html"><a href="data-wrangling.html#quickly-inspect-the-data"><i class="fa fa-check"></i><b>3.8.1</b> Quickly inspect the data</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="data-wrangling.html"><a href="data-wrangling.html#manipulation-data"><i class="fa fa-check"></i><b>3.9</b> Manipulation Data</a>
<ul>
<li class="chapter" data-level="3.9.1" data-path="data-wrangling.html"><a href="data-wrangling.html#adding-new-variables"><i class="fa fa-check"></i><b>3.9.1</b> Adding New Variables</a></li>
<li class="chapter" data-level="3.9.2" data-path="data-wrangling.html"><a href="data-wrangling.html#selecting-variables"><i class="fa fa-check"></i><b>3.9.2</b> Selecting Variables</a></li>
<li class="chapter" data-level="3.9.3" data-path="data-wrangling.html"><a href="data-wrangling.html#filtering-data"><i class="fa fa-check"></i><b>3.9.3</b> Filtering Data</a></li>
<li class="chapter" data-level="3.9.4" data-path="data-wrangling.html"><a href="data-wrangling.html#joining-data-drames"><i class="fa fa-check"></i><b>3.9.4</b> Joining Data Drames</a></li>
<li class="chapter" data-level="3.9.5" data-path="data-wrangling.html"><a href="data-wrangling.html#saving-data"><i class="fa fa-check"></i><b>3.9.5</b> Saving Data</a></li>
</ul></li>
<li class="chapter" data-level="3.10" data-path="data-wrangling.html"><a href="data-wrangling.html#using-spatial-data-frames"><i class="fa fa-check"></i><b>3.10</b> Using Spatial Data Frames</a>
<ul>
<li class="chapter" data-level="3.10.1" data-path="data-wrangling.html"><a href="data-wrangling.html#read-spatial-data"><i class="fa fa-check"></i><b>3.10.1</b> Read Spatial Data</a></li>
<li class="chapter" data-level="3.10.2" data-path="data-wrangling.html"><a href="data-wrangling.html#basic-mapping"><i class="fa fa-check"></i><b>3.10.2</b> Basic Mapping</a></li>
<li class="chapter" data-level="3.10.3" data-path="data-wrangling.html"><a href="data-wrangling.html#comparing-geographies"><i class="fa fa-check"></i><b>3.10.3</b> Comparing geographies</a></li>
</ul></li>
<li class="chapter" data-level="3.11" data-path="data-wrangling.html"><a href="data-wrangling.html#useful-functions"><i class="fa fa-check"></i><b>3.11</b> Useful Functions</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="points.html"><a href="points.html"><i class="fa fa-check"></i><b>4</b> Points</a>
<ul>
<li class="chapter" data-level="4.1" data-path="points.html"><a href="points.html#dependencies-1"><i class="fa fa-check"></i><b>4.1</b> Dependencies</a></li>
<li class="chapter" data-level="4.2" data-path="points.html"><a href="points.html#data"><i class="fa fa-check"></i><b>4.2</b> Data</a></li>
<li class="chapter" data-level="4.3" data-path="points.html"><a href="points.html#binning"><i class="fa fa-check"></i><b>4.3</b> Binning</a></li>
<li class="chapter" data-level="4.4" data-path="points.html"><a href="points.html#kde"><i class="fa fa-check"></i><b>4.4</b> KDE</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="points.html"><a href="points.html#one-dimensional-kde"><i class="fa fa-check"></i><b>4.4.1</b> One-dimensional KDE</a></li>
<li class="chapter" data-level="4.4.2" data-path="points.html"><a href="points.html#two-dimensional-spatial-kde"><i class="fa fa-check"></i><b>4.4.2</b> Two-dimensional (spatial) KDE</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="points.html"><a href="points.html#spatial-interpolation"><i class="fa fa-check"></i><b>4.5</b> Spatial Interpolation</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="points.html"><a href="points.html#inverse-distance-weight-idw-interpolation"><i class="fa fa-check"></i><b>4.5.1</b> Inverse Distance Weight (IDW) interpolation</a></li>
<li class="chapter" data-level="4.5.2" data-path="points.html"><a href="points.html#a-surface-of-housing-prices"><i class="fa fa-check"></i><b>4.5.2</b> A surface of housing prices</a></li>
<li class="chapter" data-level="4.5.3" data-path="points.html"><a href="points.html#what-should-the-next-houses-price-be"><i class="fa fa-check"></i><b>4.5.3</b> <em>“What should the next house’s price be?”</em></a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="points.html"><a href="points.html#questions"><i class="fa fa-check"></i><b>4.6</b> Questions</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="flows.html"><a href="flows.html"><i class="fa fa-check"></i><b>5</b> Flows</a>
<ul>
<li class="chapter" data-level="5.1" data-path="flows.html"><a href="flows.html#dependencies-2"><i class="fa fa-check"></i><b>5.1</b> Dependencies</a></li>
<li class="chapter" data-level="5.2" data-path="flows.html"><a href="flows.html#data-1"><i class="fa fa-check"></i><b>5.2</b> Data</a></li>
<li class="chapter" data-level="5.3" data-path="flows.html"><a href="flows.html#seeing-flows"><i class="fa fa-check"></i><b>5.3</b> “<em>Seeing</em>” flows</a></li>
<li class="chapter" data-level="5.4" data-path="flows.html"><a href="flows.html#modelling-flows"><i class="fa fa-check"></i><b>5.4</b> Modelling flows</a></li>
<li class="chapter" data-level="5.5" data-path="flows.html"><a href="flows.html#predicting-flows"><i class="fa fa-check"></i><b>5.5</b> Predicting flows</a></li>
<li class="chapter" data-level="5.6" data-path="flows.html"><a href="flows.html#questions-1"><i class="fa fa-check"></i><b>5.6</b> Questions</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="spatialecon.html"><a href="spatialecon.html"><i class="fa fa-check"></i><b>6</b> Spatial Econometrics</a>
<ul>
<li class="chapter" data-level="6.1" data-path="spatialecon.html"><a href="spatialecon.html#dependencies-3"><i class="fa fa-check"></i><b>6.1</b> Dependencies</a></li>
<li class="chapter" data-level="6.2" data-path="spatialecon.html"><a href="spatialecon.html#data-2"><i class="fa fa-check"></i><b>6.2</b> Data</a></li>
<li class="chapter" data-level="6.3" data-path="spatialecon.html"><a href="spatialecon.html#non-spatial-regression-a-refresh"><i class="fa fa-check"></i><b>6.3</b> Non-spatial regression, a refresh</a></li>
<li class="chapter" data-level="6.4" data-path="spatialecon.html"><a href="spatialecon.html#spatial-regression-a-very-first-dip"><i class="fa fa-check"></i><b>6.4</b> Spatial regression: a (very) first dip</a></li>
<li class="chapter" data-level="6.5" data-path="spatialecon.html"><a href="spatialecon.html#spatial-heterogeneity-1"><i class="fa fa-check"></i><b>6.5</b> Spatial heterogeneity</a></li>
<li class="chapter" data-level="6.6" data-path="spatialecon.html"><a href="spatialecon.html#spatial-dependence-1"><i class="fa fa-check"></i><b>6.6</b> Spatial dependence</a></li>
<li class="chapter" data-level="6.7" data-path="spatialecon.html"><a href="spatialecon.html#predicting-house-prices"><i class="fa fa-check"></i><b>6.7</b> Predicting house prices</a></li>
<li class="chapter" data-level="6.8" data-path="spatialecon.html"><a href="spatialecon.html#questions-2"><i class="fa fa-check"></i><b>6.8</b> Questions</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="mlm1.html"><a href="mlm1.html"><i class="fa fa-check"></i><b>7</b> Multilevel Modelling - Part 1</a>
<ul>
<li class="chapter" data-level="7.1" data-path="mlm1.html"><a href="mlm1.html#dependencies-4"><i class="fa fa-check"></i><b>7.1</b> Dependencies</a></li>
<li class="chapter" data-level="7.2" data-path="mlm1.html"><a href="mlm1.html#data-3"><i class="fa fa-check"></i><b>7.2</b> Data</a></li>
<li class="chapter" data-level="7.3" data-path="mlm1.html"><a href="mlm1.html#modelling"><i class="fa fa-check"></i><b>7.3</b> Modelling</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="mlm1.html"><a href="mlm1.html#baseline-linear-regression-model"><i class="fa fa-check"></i><b>7.3.1</b> Baseline Linear Regression Model</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="mlm1.html"><a href="mlm1.html#multilevel-modelling-random-intercept-model"><i class="fa fa-check"></i><b>7.4</b> Multilevel Modelling: Random Intercept Model</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="mlm1.html"><a href="mlm1.html#interpretation"><i class="fa fa-check"></i><b>7.4.1</b> Interpretation</a></li>
<li class="chapter" data-level="7.4.2" data-path="mlm1.html"><a href="mlm1.html#variance-partition-coefficient-vpc"><i class="fa fa-check"></i><b>7.4.2</b> Variance Partition Coefficient (VPC)</a></li>
<li class="chapter" data-level="7.4.3" data-path="mlm1.html"><a href="mlm1.html#uncertainty-of-estimates"><i class="fa fa-check"></i><b>7.4.3</b> Uncertainty of Estimates</a></li>
<li class="chapter" data-level="7.4.4" data-path="mlm1.html"><a href="mlm1.html#assessing-group-level-variation"><i class="fa fa-check"></i><b>7.4.4</b> Assessing Group-level Variation</a></li>
<li class="chapter" data-level="7.4.5" data-path="mlm1.html"><a href="mlm1.html#adding-individual-level-predictors"><i class="fa fa-check"></i><b>7.4.5</b> Adding Individual-level Predictors</a></li>
<li class="chapter" data-level="7.4.6" data-path="mlm1.html"><a href="mlm1.html#adding-group-level-predictors"><i class="fa fa-check"></i><b>7.4.6</b> Adding Group-level Predictors</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="mlm1.html"><a href="mlm1.html#questions-3"><i class="fa fa-check"></i><b>7.5</b> Questions</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="mlm2.html"><a href="mlm2.html"><i class="fa fa-check"></i><b>8</b> Multilevel Modelling - Part 2</a>
<ul>
<li class="chapter" data-level="8.1" data-path="mlm2.html"><a href="mlm2.html#dependencies-5"><i class="fa fa-check"></i><b>8.1</b> Dependencies</a></li>
<li class="chapter" data-level="8.2" data-path="mlm2.html"><a href="mlm2.html#data-4"><i class="fa fa-check"></i><b>8.2</b> Data</a></li>
<li class="chapter" data-level="8.3" data-path="mlm2.html"><a href="mlm2.html#conceptual-overview"><i class="fa fa-check"></i><b>8.3</b> Conceptual Overview</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="mlm2.html"><a href="mlm2.html#exploratory-analysis-varying-slopes"><i class="fa fa-check"></i><b>8.3.1</b> Exploratory Analysis: Varying Slopes</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="mlm2.html"><a href="mlm2.html#estimating-varying-intercept-and-slopes-models"><i class="fa fa-check"></i><b>8.4</b> Estimating Varying Intercept and Slopes Models</a></li>
<li class="chapter" data-level="8.5" data-path="mlm2.html"><a href="mlm2.html#interpreting-correlations-between-group-level-intercepts-and-slopes"><i class="fa fa-check"></i><b>8.5</b> Interpreting Correlations Between Group-level Intercepts and Slopes</a></li>
<li class="chapter" data-level="8.6" data-path="mlm2.html"><a href="mlm2.html#model-building"><i class="fa fa-check"></i><b>8.6</b> Model building</a>
<ul>
<li class="chapter" data-level="8.6.1" data-path="mlm2.html"><a href="mlm2.html#model-comparison"><i class="fa fa-check"></i><b>8.6.1</b> Model Comparison</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="mlm2.html"><a href="mlm2.html#questions-4"><i class="fa fa-check"></i><b>8.7</b> Questions</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="gwr.html"><a href="gwr.html"><i class="fa fa-check"></i><b>9</b> Geographically Weighted Regression</a>
<ul>
<li class="chapter" data-level="9.1" data-path="gwr.html"><a href="gwr.html#dependencies-6"><i class="fa fa-check"></i><b>9.1</b> Dependencies</a></li>
<li class="chapter" data-level="9.2" data-path="gwr.html"><a href="gwr.html#data-5"><i class="fa fa-check"></i><b>9.2</b> Data</a></li>
<li class="chapter" data-level="9.3" data-path="gwr.html"><a href="gwr.html#recap-spatial-effects"><i class="fa fa-check"></i><b>9.3</b> Recap: Spatial Effects</a></li>
<li class="chapter" data-level="9.4" data-path="gwr.html"><a href="gwr.html#exploratory-analysis"><i class="fa fa-check"></i><b>9.4</b> Exploratory Analysis</a></li>
<li class="chapter" data-level="9.5" data-path="gwr.html"><a href="gwr.html#global-regression"><i class="fa fa-check"></i><b>9.5</b> Global Regression</a>
<ul>
<li class="chapter" data-level="9.5.1" data-path="gwr.html"><a href="gwr.html#global-regression-results"><i class="fa fa-check"></i><b>9.5.1</b> Global Regression Results</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="gwr.html"><a href="gwr.html#fitting-a-geographically-weighted-regression"><i class="fa fa-check"></i><b>9.6</b> Fitting a Geographically Weighted Regression</a>
<ul>
<li class="chapter" data-level="9.6.1" data-path="gwr.html"><a href="gwr.html#fixed-or-adaptive-kernel"><i class="fa fa-check"></i><b>9.6.1</b> Fixed or Adaptive Kernel</a></li>
<li class="chapter" data-level="9.6.2" data-path="gwr.html"><a href="gwr.html#optimal-bandwidth"><i class="fa fa-check"></i><b>9.6.2</b> Optimal Bandwidth</a></li>
<li class="chapter" data-level="9.6.3" data-path="gwr.html"><a href="gwr.html#shape-of-spatial-kernel"><i class="fa fa-check"></i><b>9.6.3</b> Shape of Spatial Kernel</a></li>
<li class="chapter" data-level="9.6.4" data-path="gwr.html"><a href="gwr.html#selecting-a-bandwidth"><i class="fa fa-check"></i><b>9.6.4</b> Selecting a Bandwidth</a></li>
<li class="chapter" data-level="9.6.5" data-path="gwr.html"><a href="gwr.html#model-fit"><i class="fa fa-check"></i><b>9.6.5</b> Model fit</a></li>
<li class="chapter" data-level="9.6.6" data-path="gwr.html"><a href="gwr.html#interpretation-1"><i class="fa fa-check"></i><b>9.6.6</b> Interpretation</a></li>
<li class="chapter" data-level="9.6.7" data-path="gwr.html"><a href="gwr.html#assessing-statistical-significance"><i class="fa fa-check"></i><b>9.6.7</b> Assessing statistical significance</a></li>
<li class="chapter" data-level="9.6.8" data-path="gwr.html"><a href="gwr.html#collinearity-in-gwr"><i class="fa fa-check"></i><b>9.6.8</b> Collinearity in GWR</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="gwr.html"><a href="gwr.html#questions-5"><i class="fa fa-check"></i><b>9.7</b> Questions</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="sta.html"><a href="sta.html"><i class="fa fa-check"></i><b>10</b> Spatio-Temporal Analysis</a>
<ul>
<li class="chapter" data-level="10.1" data-path="sta.html"><a href="sta.html#dependencies-7"><i class="fa fa-check"></i><b>10.1</b> Dependencies</a></li>
<li class="chapter" data-level="10.2" data-path="sta.html"><a href="sta.html#data-6"><i class="fa fa-check"></i><b>10.2</b> Data</a></li>
<li class="chapter" data-level="10.3" data-path="sta.html"><a href="sta.html#why-spatio-temporal-analysis"><i class="fa fa-check"></i><b>10.3</b> Why Spatio-Temporal Analysis?</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="sta.html"><a href="sta.html#spatio-temporal-data-structures"><i class="fa fa-check"></i><b>10.3.1</b> Spatio-temporal Data Structures</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="sta.html"><a href="sta.html#data-wrangling"><i class="fa fa-check"></i><b>10.4</b> Data Wrangling</a></li>
<li class="chapter" data-level="10.5" data-path="sta.html"><a href="sta.html#exploring-spatio-temporal-data"><i class="fa fa-check"></i><b>10.5</b> Exploring Spatio-Temporal Data</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="sta.html"><a href="sta.html#visualisation"><i class="fa fa-check"></i><b>10.5.1</b> Visualisation</a></li>
<li class="chapter" data-level="10.5.2" data-path="sta.html"><a href="sta.html#exploratory-analysis-1"><i class="fa fa-check"></i><b>10.5.2</b> Exploratory Analysis</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="sta.html"><a href="sta.html#spatio-temporal-data-modelling"><i class="fa fa-check"></i><b>10.6</b> Spatio-Temporal Data Modelling</a>
<ul>
<li class="chapter" data-level="10.6.1" data-path="sta.html"><a href="sta.html#intuition"><i class="fa fa-check"></i><b>10.6.1</b> Intuition</a></li>
<li class="chapter" data-level="10.6.2" data-path="sta.html"><a href="sta.html#fitting-spatio-temporal-models"><i class="fa fa-check"></i><b>10.6.2</b> Fitting Spatio-Temporal Models</a></li>
</ul></li>
<li class="chapter" data-level="10.7" data-path="sta.html"><a href="sta.html#questions-6"><i class="fa fa-check"></i><b>10.7</b> Questions</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="datasets.html"><a href="datasets.html"><i class="fa fa-check"></i><b>11</b> Data Sets</a>
<ul>
<li class="chapter" data-level="11.1" data-path="datasets.html"><a href="datasets.html#madrid-airbnb"><i class="fa fa-check"></i><b>11.1</b> Madrid AirBnb</a>
<ul>
<li class="chapter" data-level="" data-path="datasets.html"><a href="datasets.html#availability"><i class="fa fa-check"></i>Availability</a></li>
<li class="chapter" data-level="" data-path="datasets.html"><a href="datasets.html#variables"><i class="fa fa-check"></i>Variables</a></li>
<li class="chapter" data-level="" data-path="datasets.html"><a href="datasets.html#projection"><i class="fa fa-check"></i>Projection</a></li>
<li class="chapter" data-level="" data-path="datasets.html"><a href="datasets.html#source-pre-processing"><i class="fa fa-check"></i>Source &amp; Pre-processing</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="datasets.html"><a href="datasets.html#england-covid-19"><i class="fa fa-check"></i><b>11.2</b> England COVID-19</a>
<ul>
<li class="chapter" data-level="" data-path="datasets.html"><a href="datasets.html#availability-1"><i class="fa fa-check"></i>Availability</a></li>
<li class="chapter" data-level="" data-path="datasets.html"><a href="datasets.html#variables-1"><i class="fa fa-check"></i>Variables</a></li>
<li class="chapter" data-level="" data-path="datasets.html"><a href="datasets.html#projection-1"><i class="fa fa-check"></i>Projection</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Spatial Modelling for Data Scientists</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="spatialecon" class="section level1" number="6">
<h1><span class="header-section-number">Chapter 6</span> Spatial Econometrics</h1>
<p>This chapter is based on the following references, which are good follow-up’s on the topic:</p>
<ul>
<li><a href="https://geographicdata.science/book/notebooks/11_regression.html">Chapter 11</a> of the GDS Book, by <span class="citation"><a href="references.html#ref-reyABwolf" role="doc-biblioref">Rey, Arribas-Bel, and Wolf</a> (<a href="references.html#ref-reyABwolf" role="doc-biblioref">forthcoming</a>)</span>.</li>
<li><a href="http://darribas.org/sdar_mini/notes/Class_03.html">Session III</a> of <span class="citation"><a href="references.html#ref-arribas2014spatial" role="doc-biblioref">Dani Arribas-Bel</a> (<a href="references.html#ref-arribas2014spatial" role="doc-biblioref">2014</a>)</span>. Check the “Related readings” section on the session page for more in-depth discussions.</li>
<li><span class="citation"><a href="references.html#ref-anselin2005spatial" role="doc-biblioref">Anselin</a> (<a href="references.html#ref-anselin2005spatial" role="doc-biblioref">2007</a>)</span>, freely available to download [<a href="http://csiss.org/GISPopSci/workshops/2011/PSU/readings/W15_Anselin2007.pdf"><code>pdf</code></a>].</li>
<li>The second part of this tutorial assumes you have reviewed <a href="https://darribas.org/gds_course/content/bE/concepts_E.html">Block E</a> of <span class="citation"><a href="references.html#ref-darribas_gds_course" role="doc-biblioref">Dani Arribas-Bel</a> (<a href="references.html#ref-darribas_gds_course" role="doc-biblioref">2019</a>)</span>. [<a href="https://darribas.org/gds_course/content/bE/concepts_E.html">html</a>]</li>
</ul>
<div id="dependencies-3" class="section level2" number="6.1">
<h2><span class="header-section-number">6.1</span> Dependencies</h2>
<p>We will rely on the following libraries in this section, all of them included in the <a href="#Dependency-list">book list</a>:</p>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb208-1"><a href="spatialecon.html#cb208-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Layout</span></span>
<span id="cb208-2"><a href="spatialecon.html#cb208-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tufte)</span>
<span id="cb208-3"><a href="spatialecon.html#cb208-3" aria-hidden="true" tabindex="-1"></a><span class="co"># For pretty table</span></span>
<span id="cb208-4"><a href="spatialecon.html#cb208-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb208-5"><a href="spatialecon.html#cb208-5" aria-hidden="true" tabindex="-1"></a><span class="co"># For string parsing</span></span>
<span id="cb208-6"><a href="spatialecon.html#cb208-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb208-7"><a href="spatialecon.html#cb208-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Spatial Data management</span></span>
<span id="cb208-8"><a href="spatialecon.html#cb208-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rgdal)</span>
<span id="cb208-9"><a href="spatialecon.html#cb208-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Pretty graphics</span></span>
<span id="cb208-10"><a href="spatialecon.html#cb208-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb208-11"><a href="spatialecon.html#cb208-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Pretty maps</span></span>
<span id="cb208-12"><a href="spatialecon.html#cb208-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggmap)</span>
<span id="cb208-13"><a href="spatialecon.html#cb208-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Various GIS utilities</span></span>
<span id="cb208-14"><a href="spatialecon.html#cb208-14" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GISTools)</span>
<span id="cb208-15"><a href="spatialecon.html#cb208-15" aria-hidden="true" tabindex="-1"></a><span class="co"># For all your interpolation needs</span></span>
<span id="cb208-16"><a href="spatialecon.html#cb208-16" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gstat)</span>
<span id="cb208-17"><a href="spatialecon.html#cb208-17" aria-hidden="true" tabindex="-1"></a><span class="co"># For data manipulation</span></span>
<span id="cb208-18"><a href="spatialecon.html#cb208-18" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb208-19"><a href="spatialecon.html#cb208-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Spatial regression</span></span>
<span id="cb208-20"><a href="spatialecon.html#cb208-20" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(spdep)</span></code></pre></div>
<p>Before we start any analysis, let us set the path to the directory where we are working. We can easily do that with <code>setwd()</code>. Please replace in the following line the path to the folder where you have placed this file -and where the <code>house_transactions</code> folder with the data lives.</p>
<div class="sourceCode" id="cb209"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb209-1"><a href="spatialecon.html#cb209-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">&#39;.&#39;</span>)</span></code></pre></div>
</div>
<div id="data-2" class="section level2" number="6.2">
<h2><span class="header-section-number">6.2</span> Data</h2>
<p>To explore ideas in spatial regression, we will the set of Airbnb properties for San Diego (US), borrowed from the “Geographic Data Science with Python” book (see <a href="https://geographicdata.science/book/data/airbnb/regression_cleaning.html">here</a> for more info on the dataset source). This covers the point location of properties advertised on the Airbnb website in the San Diego region.</p>
<p>Let us load it up first of all:</p>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb210-1"><a href="spatialecon.html#cb210-1" aria-hidden="true" tabindex="-1"></a>db <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">&#39;data/abb_sd/regression_db.geojson&#39;</span>)</span></code></pre></div>
<pre><code>## Reading layer `regression_db&#39; from data source `/home/rstudio/work/Dropbox/Francisco/uol/teaching/envs453/202122/san/data/abb_sd/regression_db.geojson&#39; using driver `GeoJSON&#39;
## Simple feature collection with 6110 features and 19 fields
## geometry type:  POINT
## dimension:      XY
## bbox:           xmin: -117.2812 ymin: 32.57349 xmax: -116.9553 ymax: 33.08311
## geographic CRS: WGS 84</code></pre>
<p>The table contains the followig variables:</p>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb212-1"><a href="spatialecon.html#cb212-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(db)</span></code></pre></div>
<pre><code>##  [1] &quot;accommodates&quot;       &quot;bathrooms&quot;          &quot;bedrooms&quot;          
##  [4] &quot;beds&quot;               &quot;neighborhood&quot;       &quot;pool&quot;              
##  [7] &quot;d2balboa&quot;           &quot;coastal&quot;            &quot;price&quot;             
## [10] &quot;log_price&quot;          &quot;id&quot;                 &quot;pg_Apartment&quot;      
## [13] &quot;pg_Condominium&quot;     &quot;pg_House&quot;           &quot;pg_Other&quot;          
## [16] &quot;pg_Townhouse&quot;       &quot;rt_Entire_home.apt&quot; &quot;rt_Private_room&quot;   
## [19] &quot;rt_Shared_room&quot;     &quot;geometry&quot;</code></pre>
<p>For most of this chapter, we will be exploring determinants and strategies for modelling the price of a property advertised in AirBnb. To get a first taste of what this means, we can create a plot of prices within the area of San Diego:</p>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb214-1"><a href="spatialecon.html#cb214-1" aria-hidden="true" tabindex="-1"></a>db <span class="sc">%&gt;%</span></span>
<span id="cb214-2"><a href="spatialecon.html#cb214-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">color =</span> price)) <span class="sc">+</span></span>
<span id="cb214-3"><a href="spatialecon.html#cb214-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>() <span class="sc">+</span> </span>
<span id="cb214-4"><a href="spatialecon.html#cb214-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_viridis_c</span>() <span class="sc">+</span></span>
<span id="cb214-5"><a href="spatialecon.html#cb214-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>()</span></code></pre></div>
<p><img src="06-spatial_econometrics_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
</div>
<div id="non-spatial-regression-a-refresh" class="section level2" number="6.3">
<h2><span class="header-section-number">6.3</span> Non-spatial regression, a refresh</h2>
<p>Before we discuss how to explicitly include space into the linear regression framework, let us show how basic regression can be carried out in R, and how you can interpret the results. By no means is this a formal and complete introduction to regression so, if that is what you are looking for, the first part of <span class="citation"><a href="references.html#ref-gelman2006data" role="doc-biblioref">Gelman and Hill</a> (<a href="references.html#ref-gelman2006data" role="doc-biblioref">2006a</a>)</span>, in particular chapters 3 and 4, are excellent places to check out.</p>
<p>The core idea of linear regression is to explain the variation in a given (<em>dependent</em>) variable as a linear function of a series of other (<em>explanatory</em>) variables. For example, in our case, we may want to express/explain the price of a property advertised on AirBnb as a function of some of its characteristics, such as the number of people it accommodates, and how many bathrooms, bedrooms and beds it features. At the individual level, we can express this as:</p>
<p><span class="math display">\[
\log(P_i) = \alpha + \beta_1 Acc_i + \beta_2 Bath_i + \beta_3 Bedr_i + \beta_4 Beds_i + \epsilon_i
\]</span></p>
<p>where <span class="math inline">\(P_i\)</span> is the price of house <span class="math inline">\(i\)</span>, <span class="math inline">\(Acc_i\)</span>, <span class="math inline">\(Bath_i\)</span>, <span class="math inline">\(Bedr_i\)</span> and <span class="math inline">\(Beds_i\)</span> are the count of people it accommodates, bathrooms, bedrooms and beds that house <span class="math inline">\(i\)</span> has, respectively. The parameters <span class="math inline">\(\beta_{1,2, 3, 4}\)</span> give us information about in which way and to what extent each variable is related to the price, and <span class="math inline">\(\alpha\)</span>, the constant term, is the average house price when all the other variables are zero. The term <span class="math inline">\(\epsilon_i\)</span> is usually referred to as the “error” and captures elements that influence the price of a house but are not accounted for explicitly. We can also express this relation in matrix form, excluding subindices for <span class="math inline">\(i\)</span> as:</p>
<p><span class="math display">\[
\log(P) = \alpha + \beta_1 Acc + \beta_2 Bath + \beta_3 Bedr + \beta_4 Beds + \epsilon
\]</span>
where each term can be interpreted in terms of vectors instead of scalars (wit the exception of the parameters <span class="math inline">\((\alpha, \beta_{1, 2, 3, 4})\)</span>, which <em>are</em> scalars). Note we are using the logarithm of the price, since this allows us to interpret the coefficients as roughly the percentual change induced by a unit increase in the explanatory variable of the estimate.</p>
<p>Remember a regression can be seen as a multivariate extension of bivariate correlations. Indeed, one way to interpret the <span class="math inline">\(\beta_k\)</span> coefficients in the equation above is as the degree of correlation between the explanatory variable <span class="math inline">\(k\)</span> and the dependent variable, <em>keeping all the other explanatory variables constant</em>. When you calculate simple bivariate correlations, the coefficient of a variable is picking up the correlation between the variables, but it is also subsuming into it variation associated with other correlated variables –also called confounding factors<a href="#fn21" class="footnote-ref" id="fnref21"><sup>21</sup></a>. Regression allows you to isolate the distinct effect that a single variable has on the dependent one, once we <em>control</em> for those other variables.</p>
<p>Practically speaking, running linear regressions in <code>R</code> is straightforward. For example, to fit the model specified in the equation above, we only need one line of code:</p>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb215-1"><a href="spatialecon.html#cb215-1" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="st">&#39;log_price ~ accommodates + bathrooms + bedrooms + beds&#39;</span>, db)</span></code></pre></div>
<p>We use the command <code>lm</code>, for linear model, and specify the equation we want to fit using a string that relates the dependent variable (the log of the price, <code>log_price</code>) with a set of explanatory ones (<code>accommodates</code>, <code>bathrooms</code>, <code>bedrooms</code>, <code>beds</code>) by using a tilde <code>~</code> that is akin to the <span class="math inline">\(=\)</span> symbol in the mathematical equation above. Since we are using names of variables that are stored in a table, we need to pass the table object (<code>db</code>) as well.</p>
<p>In order to inspect the results of the model, the quickest way is to call <code>summary</code>:</p>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb216-1"><a href="spatialecon.html#cb216-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = &quot;log_price ~ accommodates + bathrooms + bedrooms + beds&quot;, 
##     data = db)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.8486 -0.3234 -0.0095  0.3023  3.3975 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   4.018133   0.013947  288.10   &lt;2e-16 ***
## accommodates  0.176851   0.005323   33.23   &lt;2e-16 ***
## bathrooms     0.150981   0.012526   12.05   &lt;2e-16 ***
## bedrooms      0.111700   0.012537    8.91   &lt;2e-16 ***
## beds         -0.076974   0.007927   -9.71   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.5366 on 6105 degrees of freedom
## Multiple R-squared:  0.5583, Adjusted R-squared:  0.558 
## F-statistic:  1929 on 4 and 6105 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>A full detailed explanation of the output is beyond the scope of the chapter, but we will highlight the relevant bits for our main purpose. This is concentrated on the <code>Coefficients</code> section, which gives us the estimates for the <span class="math inline">\(\beta_k\)</span> coefficients in our model. These estimates are the raw equivalent of the correlation coefficient between each explanatory variable and the dependent one, once the “polluting” effect of the other variables included in the model has been accounted for<a href="#fn22" class="footnote-ref" id="fnref22"><sup>22</sup></a>. Results are as expected for the most part: houses tend to be significantly more expensive if they accommodate more people (an extra person increases the price by 17.7%, approximately), have more bathrooms (15.1%), or bedrooms (11.2%). Perhaps counter intuitively, an extra bed available seems to decrease the price by about -7.7%. However, keep in mind that this is the case, <em>everything else equal</em>. Hence, more beds per room and bathroom (ie. a more crowded house), is a bit cheaper.</p>
</div>
<div id="spatial-regression-a-very-first-dip" class="section level2" number="6.4">
<h2><span class="header-section-number">6.4</span> Spatial regression: a (very) first dip</h2>
<p>Spatial regression is about <em>explicitly</em> introducing space or geographical context into the statistical framework of a regression. Conceptually, we want to introduce space into our model whenever we think it plays an important role in the process we are interested in, or when space can act as a reasonable proxy for other factors we cannot but should include in our model. As an example of the former, we can imagine how houses at the seafront are probably more expensive than those in the second row, given their better views. To illustrate the latter, we can think of how the character of a neighborhood is important in determining the price of a house; however, it is very hard to identify and quantify “character” per se, although it might be easier to get at its spatial variation, hence a case of space as a proxy.</p>
<p>Spatial regression is a large field of development in the econometrics and statistics literatures. In this brief introduction, we will consider two related but very different processes that give rise to spatial effects: spatial heterogeneity and spatial dependence. For more rigorous treatments of the topics introduced here, the reader is referred to <span class="citation"><a href="references.html#ref-anselin2003spatial" role="doc-biblioref">Anselin</a> (<a href="references.html#ref-anselin2003spatial" role="doc-biblioref">2003</a>)</span>, <span class="citation"><a href="references.html#ref-anselin2014modern" role="doc-biblioref">Anselin and Rey</a> (<a href="references.html#ref-anselin2014modern" role="doc-biblioref">2014</a>)</span>, and <span class="citation"><a href="references.html#ref-gibbons2014spatial" role="doc-biblioref">Gibbons, Overman, and Patacchini</a> (<a href="references.html#ref-gibbons2014spatial" role="doc-biblioref">2014</a>)</span>.</p>
</div>
<div id="spatial-heterogeneity-1" class="section level2" number="6.5">
<h2><span class="header-section-number">6.5</span> Spatial heterogeneity</h2>
<p>Spatial heterogeneity (SH) arises when we cannot safely assume the process we are studying operates under the same “rules” throughout the geography of interest. In other words, we can observe SH when there are effects on the outcome variable that are intrinsically linked to specific locations. A good example of this is the case of seafront houses above: we are trying to model the price of a house and, the fact some houses are located under certain conditions (i.e. by the sea), makes their price behave differently. This somewhat abstract concept of SH can be made operational in a model in several ways. We will explore the following two: spatial fixed-effects (FE); and spatial regimes, which is a generalization of FE.</p>
<p><strong>Spatial FE</strong></p>
<p>Let us consider the house price example from the previous section to introduce a more general illustration that relates to the second motivation for spatial effects (“space as a proxy”). Given we are only including two explanatory variables in the model, it is likely we are missing some important factors that play a role at determining the price at which a house is sold. Some of them, however, are likely to vary systematically over space (e.g. different neighborhood characteristics). If that is the case, we can control for those unobserved factors by using traditional dummy variables but basing their creation on a spatial rule. For example, let us include a binary variable for every neighbourhood, as provided by AirBnB, indicating whether a given house is located within such area (<code>1</code>) or not (<code>0</code>). Neighbourhood membership is expressed on the <code>neighborhood</code> column:</p>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb218-1"><a href="spatialecon.html#cb218-1" aria-hidden="true" tabindex="-1"></a>db <span class="sc">%&gt;%</span></span>
<span id="cb218-2"><a href="spatialecon.html#cb218-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">color =</span> neighborhood)) <span class="sc">+</span></span>
<span id="cb218-3"><a href="spatialecon.html#cb218-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>() <span class="sc">+</span> </span>
<span id="cb218-4"><a href="spatialecon.html#cb218-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>()</span></code></pre></div>
<p><img src="06-spatial_econometrics_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>Mathematically, we are now fitting the following equation:</p>
<p><span class="math display">\[
\log(P_i) = \alpha_r + \beta_1 Acc_i + \beta_2 Bath_i + \beta_3 Bedr_i + \beta_4 Beds_i + \epsilon_i
\]</span></p>
<p>where the main difference is that we are now allowing the constant term, <span class="math inline">\(\alpha\)</span>, to vary by neighbourhood <span class="math inline">\(r\)</span>, <span class="math inline">\(\alpha_r\)</span>.</p>
<p>Programmatically, we can fit this model with <code>lm</code>:</p>
<div class="sourceCode" id="cb219"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb219-1"><a href="spatialecon.html#cb219-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Include `-1` to eliminate the constant term and include a dummy for every area</span></span>
<span id="cb219-2"><a href="spatialecon.html#cb219-2" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb219-3"><a href="spatialecon.html#cb219-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">&#39;log_price ~ neighborhood + accommodates + bathrooms + bedrooms + beds - 1&#39;</span>, </span>
<span id="cb219-4"><a href="spatialecon.html#cb219-4" aria-hidden="true" tabindex="-1"></a>  db</span>
<span id="cb219-5"><a href="spatialecon.html#cb219-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb219-6"><a href="spatialecon.html#cb219-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = &quot;log_price ~ neighborhood + accommodates + bathrooms + bedrooms + beds - 1&quot;, 
##     data = db)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.4549 -0.2920 -0.0203  0.2741  3.5323 
## 
## Coefficients:
##                                      Estimate Std. Error t value Pr(&gt;|t|)    
## neighborhoodBalboa Park              3.994775   0.036539  109.33   &lt;2e-16 ***
## neighborhoodBay Ho                   3.780025   0.086081   43.91   &lt;2e-16 ***
## neighborhoodBay Park                 3.941847   0.055788   70.66   &lt;2e-16 ***
## neighborhoodCarmel Valley            4.034052   0.062811   64.23   &lt;2e-16 ***
## neighborhoodCity Heights West        3.698788   0.065502   56.47   &lt;2e-16 ***
## neighborhoodClairemont Mesa          3.658339   0.051438   71.12   &lt;2e-16 ***
## neighborhoodCollege Area             3.649859   0.064979   56.17   &lt;2e-16 ***
## neighborhoodCore                     4.433447   0.058864   75.32   &lt;2e-16 ***
## neighborhoodCortez Hill              4.294790   0.057648   74.50   &lt;2e-16 ***
## neighborhoodDel Mar Heights          4.300659   0.060912   70.61   &lt;2e-16 ***
## neighborhoodEast Village             4.241146   0.032019  132.46   &lt;2e-16 ***
## neighborhoodGaslamp Quarter          4.473863   0.052493   85.23   &lt;2e-16 ***
## neighborhoodGrant Hill               4.001481   0.058825   68.02   &lt;2e-16 ***
## neighborhoodGrantville               3.664989   0.080168   45.72   &lt;2e-16 ***
## neighborhoodKensington               4.073520   0.087322   46.65   &lt;2e-16 ***
## neighborhoodLa Jolla                 4.400145   0.026772  164.36   &lt;2e-16 ***
## neighborhoodLa Jolla Village         4.066151   0.087263   46.60   &lt;2e-16 ***
## neighborhoodLinda Vista              3.817940   0.063128   60.48   &lt;2e-16 ***
## neighborhoodLittle Italy             4.390651   0.052433   83.74   &lt;2e-16 ***
## neighborhoodLoma Portal              4.034473   0.036173  111.53   &lt;2e-16 ***
## neighborhoodMarina                   4.046133   0.052178   77.55   &lt;2e-16 ***
## neighborhoodMidtown                  4.032038   0.030280  133.16   &lt;2e-16 ***
## neighborhoodMidtown District         4.356943   0.071756   60.72   &lt;2e-16 ***
## neighborhoodMira Mesa                3.570523   0.061543   58.02   &lt;2e-16 ***
## neighborhoodMission Bay              4.251309   0.023318  182.32   &lt;2e-16 ***
## neighborhoodMission Valley           4.012410   0.083766   47.90   &lt;2e-16 ***
## neighborhoodMoreno Mission           4.028288   0.063342   63.59   &lt;2e-16 ***
## neighborhoodNormal Heights           3.791895   0.054730   69.28   &lt;2e-16 ***
## neighborhoodNorth Clairemont         3.498107   0.076432   45.77   &lt;2e-16 ***
## neighborhoodNorth Hills              3.959403   0.026823  147.61   &lt;2e-16 ***
## neighborhoodNorthwest                3.810201   0.078158   48.75   &lt;2e-16 ***
## neighborhoodOcean Beach              4.152695   0.032352  128.36   &lt;2e-16 ***
## neighborhoodOld Town                 4.127737   0.046523   88.72   &lt;2e-16 ***
## neighborhoodOtay Ranch               3.722902   0.091633   40.63   &lt;2e-16 ***
## neighborhoodPacific Beach            4.116749   0.022711  181.27   &lt;2e-16 ***
## neighborhoodPark West                4.216829   0.050370   83.72   &lt;2e-16 ***
## neighborhoodRancho Bernadino         3.873962   0.080780   47.96   &lt;2e-16 ***
## neighborhoodRancho Penasquitos       3.772037   0.068808   54.82   &lt;2e-16 ***
## neighborhoodRoseville                4.070468   0.065299   62.34   &lt;2e-16 ***
## neighborhoodSan Carlos               3.935042   0.093205   42.22   &lt;2e-16 ***
## neighborhoodScripps Ranch            3.641239   0.085190   42.74   &lt;2e-16 ***
## neighborhoodSerra Mesa               3.912127   0.066630   58.71   &lt;2e-16 ***
## neighborhoodSouth Park               3.987019   0.060141   66.30   &lt;2e-16 ***
## neighborhoodUniversity City          3.772504   0.039638   95.17   &lt;2e-16 ***
## neighborhoodWest University Heights  4.043161   0.048238   83.82   &lt;2e-16 ***
## accommodates                         0.150283   0.005086   29.55   &lt;2e-16 ***
## bathrooms                            0.132287   0.011886   11.13   &lt;2e-16 ***
## bedrooms                             0.147631   0.011960   12.34   &lt;2e-16 ***
## beds                                -0.074622   0.007405  -10.08   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.4971 on 6061 degrees of freedom
## Multiple R-squared:  0.9904, Adjusted R-squared:  0.9904 
## F-statistic: 1.28e+04 on 49 and 6061 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Econometrically speaking, what the postcode FE we have introduced imply is that, instead of comparing all house prices across San Diego as equal, we only derive variation from <em>within</em> each postcode. In our particular case, estimating spatial FE in our particular example also gives you an indirect measure of area <em>desirability</em>: since they are simple dummies in a regression explaining the price of a house, their estimate tells us about how much people are willing to pay to live in a given area. We can visualise this “geography of desirability” by plotting the estimates of each fixed effect on a map:</p>
<div class="sourceCode" id="cb221"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb221-1"><a href="spatialecon.html#cb221-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract neighborhood names from coefficients</span></span>
<span id="cb221-2"><a href="spatialecon.html#cb221-2" aria-hidden="true" tabindex="-1"></a>nei.names <span class="ot">&lt;-</span> m2<span class="sc">$</span>coefficients <span class="sc">%&gt;%</span></span>
<span id="cb221-3"><a href="spatialecon.html#cb221-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">%&gt;%</span></span>
<span id="cb221-4"><a href="spatialecon.html#cb221-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">row.names</span>() <span class="sc">%&gt;%</span></span>
<span id="cb221-5"><a href="spatialecon.html#cb221-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_replace</span>(<span class="st">&quot;neighborhood&quot;</span>, <span class="st">&quot;&quot;</span>)</span>
<span id="cb221-6"><a href="spatialecon.html#cb221-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Set up as Data Frame</span></span>
<span id="cb221-7"><a href="spatialecon.html#cb221-7" aria-hidden="true" tabindex="-1"></a>nei.fes <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb221-8"><a href="spatialecon.html#cb221-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">coef =</span> m2<span class="sc">$</span>coefficients,</span>
<span id="cb221-9"><a href="spatialecon.html#cb221-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">nei =</span> nei.names,</span>
<span id="cb221-10"><a href="spatialecon.html#cb221-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">row.names =</span> nei.names</span>
<span id="cb221-11"><a href="spatialecon.html#cb221-11" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb221-12"><a href="spatialecon.html#cb221-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">right_join</span>(</span>
<span id="cb221-13"><a href="spatialecon.html#cb221-13" aria-hidden="true" tabindex="-1"></a>    db, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">&quot;nei&quot;</span> <span class="ot">=</span> <span class="st">&quot;neighborhood&quot;</span>)</span>
<span id="cb221-14"><a href="spatialecon.html#cb221-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb221-15"><a href="spatialecon.html#cb221-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot</span></span>
<span id="cb221-16"><a href="spatialecon.html#cb221-16" aria-hidden="true" tabindex="-1"></a>nei.fes <span class="sc">%&gt;%</span></span>
<span id="cb221-17"><a href="spatialecon.html#cb221-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_as_sf</span>() <span class="sc">%&gt;%</span></span>
<span id="cb221-18"><a href="spatialecon.html#cb221-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">color =</span> coef)) <span class="sc">+</span></span>
<span id="cb221-19"><a href="spatialecon.html#cb221-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>() <span class="sc">+</span></span>
<span id="cb221-20"><a href="spatialecon.html#cb221-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_viridis_c</span>() <span class="sc">+</span></span>
<span id="cb221-21"><a href="spatialecon.html#cb221-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>()</span></code></pre></div>
<p><img src="06-spatial_econometrics_files/figure-html/unnamed-chunk-10-1.png" width="672" />
We can see how neighborhoods in the left (west) tend to have higher prices. What we can’t see, but it is represented there if you are familiar with the geography of San Diego, is that the city is bounded by the Pacific ocean on the left, suggesting neighbourhoods by the beach tend to be more expensive.</p>
<p>Remember that the interpretation of a <span class="math inline">\(\beta_k\)</span> coefficient is the effect of variable <span class="math inline">\(k\)</span>, <em>given all the other explanatory variables included remain constant</em>. By including a single variable for each area, we are effectively forcing the model to compare as equal only house prices that share the same value for each variable; in other words, only houses located within the same area. Introducing FE affords you a higher degree of isolation of the effects of the variables you introduce in your model because you can control for unobserved effects that align spatially with the distribution of the FE you introduce (by neighbourhood, in our case).</p>
<p><strong>Spatial regimes</strong></p>
<p>At the core of estimating spatial FEs is the idea that, instead of assuming the dependent variable behaves uniformly over space, there are systematic effects following a geographical pattern that affect its behaviour. In other words, spatial FEs introduce econometrically the notion of spatial heterogeneity. They do this in the simplest possible form: by allowing the constant term to vary geographically. The other elements of the regression are left untouched and hence apply uniformly across space. The idea of spatial regimes (SRs) is to generalize the spatial FE approach to allow not only the constant term to vary but also any other explanatory variable. This implies that the equation we will be estimating is:
<span class="math display">\[
\log(P_i) = \alpha_r + \beta_{1r} Acc_i + \beta_{2r} Bath_i + \beta_{3r} Bedr_i + \beta_{4r} Beds_i + \epsilon_i
\]</span></p>
<p>where we are not only allowing the constant term to vary by region (<span class="math inline">\(\alpha_r\)</span>), but also every other parameter (<span class="math inline">\(\beta_{kr}\)</span>).</p>
<p>Also, given we are going to allow <em>every</em> coefficient to vary by regime, we will need to explicitly set a constant term that we can allow to vary:</p>
<div class="sourceCode" id="cb222"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb222-1"><a href="spatialecon.html#cb222-1" aria-hidden="true" tabindex="-1"></a>db<span class="sc">$</span>one <span class="ot">&lt;-</span> <span class="dv">1</span></span></code></pre></div>
<p>Then, the estimation leverages the capabilities in model description of R formulas:</p>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb223-1"><a href="spatialecon.html#cb223-1" aria-hidden="true" tabindex="-1"></a><span class="co"># `:` notation implies interaction variables</span></span>
<span id="cb223-2"><a href="spatialecon.html#cb223-2" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb223-3"><a href="spatialecon.html#cb223-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">&#39;log_price ~ 0 + (accommodates + bathrooms + bedrooms + beds):(neighborhood)&#39;</span>, </span>
<span id="cb223-4"><a href="spatialecon.html#cb223-4" aria-hidden="true" tabindex="-1"></a>  db</span>
<span id="cb223-5"><a href="spatialecon.html#cb223-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb223-6"><a href="spatialecon.html#cb223-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m3)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = &quot;log_price ~ 0 + (accommodates + bathrooms + bedrooms + beds):(neighborhood)&quot;, 
##     data = db)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -10.4790  -0.0096   1.0931   1.7599   6.1073 
## 
## Coefficients:
##                                                   Estimate Std. Error t value
## accommodates:neighborhoodBalboa Park              0.063528   0.093237   0.681
## accommodates:neighborhoodBay Ho                  -0.259615   0.335007  -0.775
## accommodates:neighborhoodBay Park                -0.355401   0.232720  -1.527
## accommodates:neighborhoodCarmel Valley            0.129786   0.187193   0.693
## accommodates:neighborhoodCity Heights West        0.447371   0.231998   1.928
## accommodates:neighborhoodClairemont Mesa          0.711353   0.177821   4.000
## accommodates:neighborhoodCollege Area            -0.346152   0.188071  -1.841
## accommodates:neighborhoodCore                     0.125864   0.148417   0.848
## accommodates:neighborhoodCortez Hill              0.715958   0.126562   5.657
## accommodates:neighborhoodDel Mar Heights          0.829195   0.214067   3.874
## accommodates:neighborhoodEast Village             0.214642   0.077394   2.773
## accommodates:neighborhoodGaslamp Quarter          0.451443   0.197637   2.284
## accommodates:neighborhoodGrant Hill               1.135176   0.167771   6.766
## accommodates:neighborhoodGrantville               0.300907   0.280369   1.073
## accommodates:neighborhoodKensington               0.668742   0.450243   1.485
## accommodates:neighborhoodLa Jolla                 0.520882   0.055887   9.320
## accommodates:neighborhoodLa Jolla Village         0.566452   0.413185   1.371
## accommodates:neighborhoodLinda Vista              0.523975   0.282219   1.857
## accommodates:neighborhoodLittle Italy             0.603908   0.121899   4.954
## accommodates:neighborhoodLoma Portal              0.487743   0.127870   3.814
## accommodates:neighborhoodMarina                   0.431384   0.172628   2.499
## accommodates:neighborhoodMidtown                  0.618058   0.087992   7.024
## accommodates:neighborhoodMidtown District         0.430398   0.191682   2.245
## accommodates:neighborhoodMira Mesa               -0.018199   0.310167  -0.059
## accommodates:neighborhoodMission Bay              0.440951   0.049454   8.916
## accommodates:neighborhoodMission Valley           0.144530   0.507925   0.285
## accommodates:neighborhoodMoreno Mission           0.100471   0.229460   0.438
## accommodates:neighborhoodNormal Heights           0.413682   0.198584   2.083
## accommodates:neighborhoodNorth Clairemont        -0.242723   0.307090  -0.790
## accommodates:neighborhoodNorth Hills              0.262840   0.083258   3.157
## accommodates:neighborhoodNorthwest               -0.229157   0.255656  -0.896
## accommodates:neighborhoodOcean Beach              0.754771   0.079097   9.542
## accommodates:neighborhoodOld Town                 0.177176   0.159714   1.109
## accommodates:neighborhoodOtay Ranch              -0.333536   0.309545  -1.078
## accommodates:neighborhoodPacific Beach            0.345475   0.057599   5.998
## accommodates:neighborhoodPark West                0.909020   0.156013   5.827
## accommodates:neighborhoodRancho Bernadino        -0.118939   0.256750  -0.463
## accommodates:neighborhoodRancho Penasquitos       0.121845   0.228456   0.533
## accommodates:neighborhoodRoseville                0.316929   0.226110   1.402
## accommodates:neighborhoodSan Carlos               0.191248   0.318706   0.600
## accommodates:neighborhoodScripps Ranch            0.347638   0.127239   2.732
## accommodates:neighborhoodSerra Mesa               0.495491   0.282281   1.755
## accommodates:neighborhoodSouth Park               0.334378   0.256708   1.303
## accommodates:neighborhoodUniversity City          0.107605   0.113883   0.945
## accommodates:neighborhoodWest University Heights  0.190215   0.212040   0.897
## bathrooms:neighborhoodBalboa Park                 2.275321   0.225032  10.111
## bathrooms:neighborhoodBay Ho                      3.312231   0.530568   6.243
## bathrooms:neighborhoodBay Park                    2.231649   0.365655   6.103
## bathrooms:neighborhoodCarmel Valley               1.191058   0.224138   5.314
## bathrooms:neighborhoodCity Heights West           2.517235   0.550272   4.575
## bathrooms:neighborhoodClairemont Mesa             3.737297   0.427366   8.745
## bathrooms:neighborhoodCollege Area                3.370263   0.413479   8.151
## bathrooms:neighborhoodCore                        3.635188   0.490640   7.409
## bathrooms:neighborhoodCortez Hill                 1.631032   0.299654   5.443
## bathrooms:neighborhoodDel Mar Heights             1.346206   0.342828   3.927
## bathrooms:neighborhoodEast Village                2.600489   0.190932  13.620
## bathrooms:neighborhoodGaslamp Quarter             3.183092   0.527615   6.033
## bathrooms:neighborhoodGrant Hill                  2.770976   0.416838   6.648
## bathrooms:neighborhoodGrantville                  2.177175   0.693599   3.139
## bathrooms:neighborhoodKensington                  1.284044   0.671482   1.912
## bathrooms:neighborhoodLa Jolla                    0.852667   0.099413   8.577
## bathrooms:neighborhoodLa Jolla Village            0.984426   1.193870   0.825
## bathrooms:neighborhoodLinda Vista                 2.359895   0.393392   5.999
## bathrooms:neighborhoodLittle Italy                2.600567   0.275834   9.428
## bathrooms:neighborhoodLoma Portal                 2.575164   0.249679  10.314
## bathrooms:neighborhoodMarina                      3.317139   0.656533   5.053
## bathrooms:neighborhoodMidtown                     0.899736   0.112205   8.019
## bathrooms:neighborhoodMidtown District            3.143440   0.594875   5.284
## bathrooms:neighborhoodMira Mesa                   2.858280   0.512511   5.577
## bathrooms:neighborhoodMission Bay                 1.764929   0.122421  14.417
## bathrooms:neighborhoodMission Valley              2.666000   1.365483   1.952
## bathrooms:neighborhoodMoreno Mission              3.234512   0.557898   5.798
## bathrooms:neighborhoodNormal Heights              3.505139   0.467965   7.490
## bathrooms:neighborhoodNorth Clairemont            2.574847   0.613471   4.197
## bathrooms:neighborhoodNorth Hills                 2.584724   0.191541  13.494
## bathrooms:neighborhoodNorthwest                   2.877519   0.569924   5.049
## bathrooms:neighborhoodOcean Beach                 1.702208   0.207508   8.203
## bathrooms:neighborhoodOld Town                    2.249120   0.302755   7.429
## bathrooms:neighborhoodOtay Ranch                  2.818736   1.132794   2.488
## bathrooms:neighborhoodPacific Beach               2.272803   0.130607  17.402
## bathrooms:neighborhoodPark West                   2.676739   0.308257   8.683
## bathrooms:neighborhoodRancho Bernadino            0.856723   0.555198   1.543
## bathrooms:neighborhoodRancho Penasquitos          0.677767   0.414569   1.635
## bathrooms:neighborhoodRoseville                   1.109625   0.360103   3.081
## bathrooms:neighborhoodSan Carlos                  2.489815   0.511232   4.870
## bathrooms:neighborhoodScripps Ranch               2.459862   0.469601   5.238
## bathrooms:neighborhoodSerra Mesa                  2.968934   0.602807   4.925
## bathrooms:neighborhoodSouth Park                  2.895471   0.521793   5.549
## bathrooms:neighborhoodUniversity City             3.125387   0.347825   8.986
## bathrooms:neighborhoodWest University Heights     2.188257   0.390408   5.605
## bedrooms:neighborhoodBalboa Park                  0.605655   0.245384   2.468
## bedrooms:neighborhoodBay Ho                       0.836163   0.631871   1.323
## bedrooms:neighborhoodBay Park                     1.060944   0.430737   2.463
## bedrooms:neighborhoodCarmel Valley                0.521954   0.480497   1.086
## bedrooms:neighborhoodCity Heights West           -0.272600   0.663983  -0.411
## bedrooms:neighborhoodClairemont Mesa             -0.742539   0.450344  -1.649
## bedrooms:neighborhoodCollege Area                -0.306621   0.410476  -0.747
## bedrooms:neighborhoodCore                        -0.786470   0.395991  -1.986
## bedrooms:neighborhoodCortez Hill                  0.793039   0.380195   2.086
## bedrooms:neighborhoodDel Mar Heights             -0.071069   0.369070  -0.193
## bedrooms:neighborhoodEast Village                -0.186076   0.213572  -0.871
## bedrooms:neighborhoodGaslamp Quarter             -0.294024   0.342057  -0.860
## bedrooms:neighborhoodGrant Hill                  -0.456825   0.425374  -1.074
## bedrooms:neighborhoodGrantville                   0.907259   0.770945   1.177
## bedrooms:neighborhoodKensington                  -0.257195   1.009326  -0.255
## bedrooms:neighborhoodLa Jolla                    -0.152098   0.133726  -1.137
## bedrooms:neighborhoodLa Jolla Village             4.291700   1.882046   2.280
## bedrooms:neighborhoodLinda Vista                 -0.485372   0.642684  -0.755
## bedrooms:neighborhoodLittle Italy                 0.057475   0.306357   0.188
## bedrooms:neighborhoodLoma Portal                 -0.406484   0.250607  -1.622
## bedrooms:neighborhoodMarina                      -0.831114   0.511626  -1.624
## bedrooms:neighborhoodMidtown                      0.696852   0.167900   4.150
## bedrooms:neighborhoodMidtown District             0.010614   0.509151   0.021
## bedrooms:neighborhoodMira Mesa                   -0.197692   0.780959  -0.253
## bedrooms:neighborhoodMission Bay                 -0.330540   0.121602  -2.718
## bedrooms:neighborhoodMission Valley               0.514998   1.295767   0.397
## bedrooms:neighborhoodMoreno Mission              -0.584689   0.596044  -0.981
## bedrooms:neighborhoodNormal Heights              -0.127744   0.391691  -0.326
## bedrooms:neighborhoodNorth Clairemont             0.281306   0.695297   0.405
## bedrooms:neighborhoodNorth Hills                  0.380444   0.178477   2.132
## bedrooms:neighborhoodNorthwest                    0.288603   0.607295   0.475
## bedrooms:neighborhoodOcean Beach                 -0.038069   0.207927  -0.183
## bedrooms:neighborhoodOld Town                    -0.319724   0.375203  -0.852
## bedrooms:neighborhoodOtay Ranch                   0.015564   1.332279   0.012
## bedrooms:neighborhoodPacific Beach               -0.037912   0.139026  -0.273
## bedrooms:neighborhoodPark West                   -0.696514   0.413881  -1.683
## bedrooms:neighborhoodRancho Bernadino             1.034776   0.579798   1.785
## bedrooms:neighborhoodRancho Penasquitos           0.674520   0.519260   1.299
## bedrooms:neighborhoodRoseville                    0.881011   0.592962   1.486
## bedrooms:neighborhoodSan Carlos                  -0.394191   0.540343  -0.730
## bedrooms:neighborhoodScripps Ranch                1.107455   0.336101   3.295
## bedrooms:neighborhoodSerra Mesa                   0.253001   0.620774   0.408
## bedrooms:neighborhoodSouth Park                  -0.595844   0.407811  -1.461
## bedrooms:neighborhoodUniversity City              0.203783   0.455767   0.447
## bedrooms:neighborhoodWest University Heights      0.242873   0.359245   0.676
## beds:neighborhoodBalboa Park                      0.041556   0.173183   0.240
## beds:neighborhoodBay Ho                          -0.402544   0.495241  -0.813
## beds:neighborhoodBay Park                         0.283958   0.410776   0.691
## beds:neighborhoodCarmel Valley                    0.150416   0.288268   0.522
## beds:neighborhoodCity Heights West               -0.217526   0.497878  -0.437
## beds:neighborhoodClairemont Mesa                 -1.109581   0.308998  -3.591
## beds:neighborhoodCollege Area                     0.594892   0.312780   1.902
## beds:neighborhoodCore                             0.602559   0.277027   2.175
## beds:neighborhoodCortez Hill                     -0.609996   0.143559  -4.249
## beds:neighborhoodDel Mar Heights                 -0.708476   0.257299  -2.754
## beds:neighborhoodEast Village                     0.399909   0.148641   2.690
## beds:neighborhoodGaslamp Quarter                  0.240245   0.319910   0.751
## beds:neighborhoodGrant Hill                      -1.315807   0.186724  -7.047
## beds:neighborhoodGrantville                      -0.382590   0.469011  -0.816
## beds:neighborhoodKensington                       0.133474   0.664698   0.201
## beds:neighborhoodLa Jolla                         0.001347   0.085013   0.016
## beds:neighborhoodLa Jolla Village                -2.878676   1.020652  -2.820
## beds:neighborhoodLinda Vista                     -0.142372   0.278211  -0.512
## beds:neighborhoodLittle Italy                    -0.569868   0.099961  -5.701
## beds:neighborhoodLoma Portal                     -0.255510   0.222956  -1.146
## beds:neighborhoodMarina                           0.024175   0.429466   0.056
## beds:neighborhoodMidtown                         -0.346866   0.137915  -2.515
## beds:neighborhoodMidtown District                -0.464781   0.337775  -1.376
## beds:neighborhoodMira Mesa                        0.319934   0.426799   0.750
## beds:neighborhoodMission Bay                     -0.108936   0.067105  -1.623
## beds:neighborhoodMission Valley                  -0.502441   0.879795  -0.571
## beds:neighborhoodMoreno Mission                   0.492514   0.439355   1.121
## beds:neighborhoodNormal Heights                  -0.532907   0.227211  -2.345
## beds:neighborhoodNorth Clairemont                 0.562363   0.704213   0.799
## beds:neighborhoodNorth Hills                     -0.279430   0.123678  -2.259
## beds:neighborhoodNorthwest                        0.742017   0.474903   1.562
## beds:neighborhoodOcean Beach                     -0.667651   0.137647  -4.850
## beds:neighborhoodOld Town                         0.459210   0.287008   1.600
## beds:neighborhoodOtay Ranch                       0.235723   0.983870   0.240
## beds:neighborhoodPacific Beach                   -0.179242   0.087511  -2.048
## beds:neighborhoodPark West                       -0.873297   0.225334  -3.876
## beds:neighborhoodRancho Bernadino                 0.378088   0.348640   1.084
## beds:neighborhoodRancho Penasquitos               0.147457   0.344820   0.428
## beds:neighborhoodRoseville                       -0.391529   0.328609  -1.191
## beds:neighborhoodSan Carlos                       0.115338   0.621666   0.186
## beds:neighborhoodScripps Ranch                   -1.654484   0.338331  -4.890
## beds:neighborhoodSerra Mesa                      -1.018812   0.705888  -1.443
## beds:neighborhoodSouth Park                       0.452815   0.406052   1.115
## beds:neighborhoodUniversity City                 -0.345822   0.232779  -1.486
## beds:neighborhoodWest University Heights          0.146128   0.364075   0.401
##                                                  Pr(&gt;|t|)    
## accommodates:neighborhoodBalboa Park             0.495668    
## accommodates:neighborhoodBay Ho                  0.438397    
## accommodates:neighborhoodBay Park                0.126774    
## accommodates:neighborhoodCarmel Valley           0.488131    
## accommodates:neighborhoodCity Heights West       0.053861 .  
## accommodates:neighborhoodClairemont Mesa         6.40e-05 ***
## accommodates:neighborhoodCollege Area            0.065740 .  
## accommodates:neighborhoodCore                    0.396446    
## accommodates:neighborhoodCortez Hill             1.61e-08 ***
## accommodates:neighborhoodDel Mar Heights         0.000108 ***
## accommodates:neighborhoodEast Village            0.005565 ** 
## accommodates:neighborhoodGaslamp Quarter         0.022395 *  
## accommodates:neighborhoodGrant Hill              1.45e-11 ***
## accommodates:neighborhoodGrantville              0.283202    
## accommodates:neighborhoodKensington              0.137520    
## accommodates:neighborhoodLa Jolla                 &lt; 2e-16 ***
## accommodates:neighborhoodLa Jolla Village        0.170446    
## accommodates:neighborhoodLinda Vista             0.063414 .  
## accommodates:neighborhoodLittle Italy            7.47e-07 ***
## accommodates:neighborhoodLoma Portal             0.000138 ***
## accommodates:neighborhoodMarina                  0.012484 *  
## accommodates:neighborhoodMidtown                 2.40e-12 ***
## accommodates:neighborhoodMidtown District        0.024780 *  
## accommodates:neighborhoodMira Mesa               0.953213    
## accommodates:neighborhoodMission Bay              &lt; 2e-16 ***
## accommodates:neighborhoodMission Valley          0.776000    
## accommodates:neighborhoodMoreno Mission          0.661505    
## accommodates:neighborhoodNormal Heights          0.037279 *  
## accommodates:neighborhoodNorth Clairemont        0.429327    
## accommodates:neighborhoodNorth Hills             0.001602 ** 
## accommodates:neighborhoodNorthwest               0.370103    
## accommodates:neighborhoodOcean Beach              &lt; 2e-16 ***
## accommodates:neighborhoodOld Town                0.267333    
## accommodates:neighborhoodOtay Ranch              0.281298    
## accommodates:neighborhoodPacific Beach           2.12e-09 ***
## accommodates:neighborhoodPark West               5.96e-09 ***
## accommodates:neighborhoodRancho Bernadino        0.643202    
## accommodates:neighborhoodRancho Penasquitos      0.593817    
## accommodates:neighborhoodRoseville               0.161071    
## accommodates:neighborhoodSan Carlos              0.548479    
## accommodates:neighborhoodScripps Ranch           0.006311 ** 
## accommodates:neighborhoodSerra Mesa              0.079258 .  
## accommodates:neighborhoodSouth Park              0.192775    
## accommodates:neighborhoodUniversity City         0.344762    
## accommodates:neighborhoodWest University Heights 0.369719    
## bathrooms:neighborhoodBalboa Park                 &lt; 2e-16 ***
## bathrooms:neighborhoodBay Ho                     4.60e-10 ***
## bathrooms:neighborhoodBay Park                   1.11e-09 ***
## bathrooms:neighborhoodCarmel Valley              1.11e-07 ***
## bathrooms:neighborhoodCity Heights West          4.87e-06 ***
## bathrooms:neighborhoodClairemont Mesa             &lt; 2e-16 ***
## bathrooms:neighborhoodCollege Area               4.37e-16 ***
## bathrooms:neighborhoodCore                       1.45e-13 ***
## bathrooms:neighborhoodCortez Hill                5.45e-08 ***
## bathrooms:neighborhoodDel Mar Heights            8.71e-05 ***
## bathrooms:neighborhoodEast Village                &lt; 2e-16 ***
## bathrooms:neighborhoodGaslamp Quarter            1.71e-09 ***
## bathrooms:neighborhoodGrant Hill                 3.25e-11 ***
## bathrooms:neighborhoodGrantville                 0.001704 ** 
## bathrooms:neighborhoodKensington                 0.055892 .  
## bathrooms:neighborhoodLa Jolla                    &lt; 2e-16 ***
## bathrooms:neighborhoodLa Jolla Village           0.409651    
## bathrooms:neighborhoodLinda Vista                2.10e-09 ***
## bathrooms:neighborhoodLittle Italy                &lt; 2e-16 ***
## bathrooms:neighborhoodLoma Portal                 &lt; 2e-16 ***
## bathrooms:neighborhoodMarina                     4.49e-07 ***
## bathrooms:neighborhoodMidtown                    1.28e-15 ***
## bathrooms:neighborhoodMidtown District           1.31e-07 ***
## bathrooms:neighborhoodMira Mesa                  2.55e-08 ***
## bathrooms:neighborhoodMission Bay                 &lt; 2e-16 ***
## bathrooms:neighborhoodMission Valley             0.050935 .  
## bathrooms:neighborhoodMoreno Mission             7.07e-09 ***
## bathrooms:neighborhoodNormal Heights             7.88e-14 ***
## bathrooms:neighborhoodNorth Clairemont           2.74e-05 ***
## bathrooms:neighborhoodNorth Hills                 &lt; 2e-16 ***
## bathrooms:neighborhoodNorthwest                  4.58e-07 ***
## bathrooms:neighborhoodOcean Beach                2.85e-16 ***
## bathrooms:neighborhoodOld Town                   1.25e-13 ***
## bathrooms:neighborhoodOtay Ranch                 0.012863 *  
## bathrooms:neighborhoodPacific Beach               &lt; 2e-16 ***
## bathrooms:neighborhoodPark West                   &lt; 2e-16 ***
## bathrooms:neighborhoodRancho Bernadino           0.122861    
## bathrooms:neighborhoodRancho Penasquitos         0.102129    
## bathrooms:neighborhoodRoseville                  0.002070 ** 
## bathrooms:neighborhoodSan Carlos                 1.14e-06 ***
## bathrooms:neighborhoodScripps Ranch              1.68e-07 ***
## bathrooms:neighborhoodSerra Mesa                 8.66e-07 ***
## bathrooms:neighborhoodSouth Park                 3.00e-08 ***
## bathrooms:neighborhoodUniversity City             &lt; 2e-16 ***
## bathrooms:neighborhoodWest University Heights    2.18e-08 ***
## bedrooms:neighborhoodBalboa Park                 0.013608 *  
## bedrooms:neighborhoodBay Ho                      0.185782    
## bedrooms:neighborhoodBay Park                    0.013803 *  
## bedrooms:neighborhoodCarmel Valley               0.277400    
## bedrooms:neighborhoodCity Heights West           0.681416    
## bedrooms:neighborhoodClairemont Mesa             0.099236 .  
## bedrooms:neighborhoodCollege Area                0.455100    
## bedrooms:neighborhoodCore                        0.047070 *  
## bedrooms:neighborhoodCortez Hill                 0.037033 *  
## bedrooms:neighborhoodDel Mar Heights             0.847309    
## bedrooms:neighborhoodEast Village                0.383650    
## bedrooms:neighborhoodGaslamp Quarter             0.390058    
## bedrooms:neighborhoodGrant Hill                  0.282895    
## bedrooms:neighborhoodGrantville                  0.239317    
## bedrooms:neighborhoodKensington                  0.798872    
## bedrooms:neighborhoodLa Jolla                    0.255422    
## bedrooms:neighborhoodLa Jolla Village            0.022623 *  
## bedrooms:neighborhoodLinda Vista                 0.450143    
## bedrooms:neighborhoodLittle Italy                0.851191    
## bedrooms:neighborhoodLoma Portal                 0.104857    
## bedrooms:neighborhoodMarina                      0.104332    
## bedrooms:neighborhoodMidtown                     3.37e-05 ***
## bedrooms:neighborhoodMidtown District            0.983369    
## bedrooms:neighborhoodMira Mesa                   0.800169    
## bedrooms:neighborhoodMission Bay                 0.006583 ** 
## bedrooms:neighborhoodMission Valley              0.691053    
## bedrooms:neighborhoodMoreno Mission              0.326658    
## bedrooms:neighborhoodNormal Heights              0.744334    
## bedrooms:neighborhoodNorth Clairemont            0.685798    
## bedrooms:neighborhoodNorth Hills                 0.033080 *  
## bedrooms:neighborhoodNorthwest                   0.634643    
## bedrooms:neighborhoodOcean Beach                 0.854736    
## bedrooms:neighborhoodOld Town                    0.394173    
## bedrooms:neighborhoodOtay Ranch                  0.990680    
## bedrooms:neighborhoodPacific Beach               0.785097    
## bedrooms:neighborhoodPark West                   0.092450 .  
## bedrooms:neighborhoodRancho Bernadino            0.074358 .  
## bedrooms:neighborhoodRancho Penasquitos          0.193994    
## bedrooms:neighborhoodRoseville                   0.137390    
## bedrooms:neighborhoodSan Carlos                  0.465713    
## bedrooms:neighborhoodScripps Ranch               0.000990 ***
## bedrooms:neighborhoodSerra Mesa                  0.683614    
## bedrooms:neighborhoodSouth Park                  0.144046    
## bedrooms:neighborhoodUniversity City             0.654804    
## bedrooms:neighborhoodWest University Heights     0.499025    
## beds:neighborhoodBalboa Park                     0.810374    
## beds:neighborhoodBay Ho                          0.416352    
## beds:neighborhoodBay Park                        0.489423    
## beds:neighborhoodCarmel Valley                   0.601836    
## beds:neighborhoodCity Heights West               0.662195    
## beds:neighborhoodClairemont Mesa                 0.000332 ***
## beds:neighborhoodCollege Area                    0.057226 .  
## beds:neighborhoodCore                            0.029663 *  
## beds:neighborhoodCortez Hill                     2.18e-05 ***
## beds:neighborhoodDel Mar Heights                 0.005914 ** 
## beds:neighborhoodEast Village                    0.007156 ** 
## beds:neighborhoodGaslamp Quarter                 0.452696    
## beds:neighborhoodGrant Hill                      2.04e-12 ***
## beds:neighborhoodGrantville                      0.414683    
## beds:neighborhoodKensington                      0.840859    
## beds:neighborhoodLa Jolla                        0.987357    
## beds:neighborhoodLa Jolla Village                0.004812 ** 
## beds:neighborhoodLinda Vista                     0.608851    
## beds:neighborhoodLittle Italy                    1.25e-08 ***
## beds:neighborhoodLoma Portal                     0.251837    
## beds:neighborhoodMarina                          0.955112    
## beds:neighborhoodMidtown                         0.011927 *  
## beds:neighborhoodMidtown District                0.168872    
## beds:neighborhoodMira Mesa                       0.453518    
## beds:neighborhoodMission Bay                     0.104565    
## beds:neighborhoodMission Valley                  0.567962    
## beds:neighborhoodMoreno Mission                  0.262337    
## beds:neighborhoodNormal Heights                  0.019038 *  
## beds:neighborhoodNorth Clairemont                0.424572    
## beds:neighborhoodNorth Hills                     0.023899 *  
## beds:neighborhoodNorthwest                       0.118233    
## beds:neighborhoodOcean Beach                     1.26e-06 ***
## beds:neighborhoodOld Town                        0.109654    
## beds:neighborhoodOtay Ranch                      0.810658    
## beds:neighborhoodPacific Beach                   0.040583 *  
## beds:neighborhoodPark West                       0.000108 ***
## beds:neighborhoodRancho Bernadino                0.278202    
## beds:neighborhoodRancho Penasquitos              0.668932    
## beds:neighborhoodRoseville                       0.233515    
## beds:neighborhoodSan Carlos                      0.852819    
## beds:neighborhoodScripps Ranch                   1.03e-06 ***
## beds:neighborhoodSerra Mesa                      0.148987    
## beds:neighborhoodSouth Park                      0.264826    
## beds:neighborhoodUniversity City                 0.137433    
## beds:neighborhoodWest University Heights         0.688164    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.81 on 5930 degrees of freedom
## Multiple R-squared:  0.8759, Adjusted R-squared:  0.8721 
## F-statistic: 232.4 on 180 and 5930 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>This allows us to get a separate constant term and estimate of the impact of each variable <em>for every neighborhood</em></p>
</div>
<div id="spatial-dependence-1" class="section level2" number="6.6">
<h2><span class="header-section-number">6.6</span> Spatial dependence</h2>
<p>As we have just discussed, SH is about effects of phenomena that are <em>explicitly linked</em> to geography and that hence cause spatial variation and clustering of values. This encompasses many of the kinds of spatial effects we may be interested in when we fit linear regressions. However, in other cases, our interest is on the effect of the <em>spatial configuration</em> of the observations, and the extent to which that has an effect on the outcome we are considering. For example, we might think that the price of a house not only depends on the number of bathrooms it has but, if we take number of bathrooms as a proxy for size and status, also whether it is surrounded by other houses with many bathrooms. This kind of spatial effect is fundamentally different from SH in that is it not related to inherent characteristics of the geography but relates to the characteristics of the observations in our dataset and, specially, to their spatial arrangement. We call this phenomenon by which the values of observations are related to each other through distance <em>spatial dependence</em> <span class="citation">(<a href="references.html#ref-anselin1988spatial" role="doc-biblioref">Anselin 1988</a>)</span>.</p>
<p><strong>Spatial Weights</strong></p>
<p>There are several ways to introduce spatial dependence in an econometric framework, with varying degrees of econometric sophistication <span class="citation">(see <a href="references.html#ref-anselin2003spatial" role="doc-biblioref">Anselin 2003</a> for a good overview)</span>. Common to all of them however is the way space is formally encapsulated: through <em>spatial weights matrices (<span class="math inline">\(W\)</span>)</em><a href="#fn23" class="footnote-ref" id="fnref23"><sup>23</sup></a>. These are <span class="math inline">\(NxN\)</span> matrices with zero diagonals and every <span class="math inline">\(w_{ij}\)</span> cell with a value that represents the degree of spatial connectivity/interaction between observations <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span>. If they are not connected at all, <span class="math inline">\(w_{ij}=0\)</span>, otherwise <span class="math inline">\(w_{ij}&gt;0\)</span> and we call <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span> neighbors. The exact value in the latter case depends on the criterium we use to define neighborhood relations. These matrices also tend to be row-standardized so the sum of each row equals to one.</p>
<p>A related concept to spatial weight matrices is that of <em>spatial lag</em>. This is an operator that multiplies a given variable <span class="math inline">\(y\)</span> by a spatial weight matrix:</p>
<p><span class="math display">\[
y_{lag} = W y
\]</span></p>
<p>If <span class="math inline">\(W\)</span> is row-standardized, <span class="math inline">\(y_{lag}\)</span> is effectively the average value of <span class="math inline">\(y\)</span> in the neighborhood of each observation. The individual notation may help clarify this:</p>
<p><span class="math display">\[
y_{lag-i} = \displaystyle \sum_j w_{ij} y_j
\]</span></p>
<p>where <span class="math inline">\(y_{lag-i}\)</span> is the spatial lag of variable <span class="math inline">\(y\)</span> at location <span class="math inline">\(i\)</span>, and <span class="math inline">\(j\)</span> sums over the entire dataset. If <span class="math inline">\(W\)</span> is row-standardized, <span class="math inline">\(y_{lag-i}\)</span> becomes an average of <span class="math inline">\(y\)</span> weighted by the spatial criterium defined in <span class="math inline">\(W\)</span>.</p>
<p>Given that spatial weights matrices are not the focus of this tutorial, we will stick to a very simple case. Since we are dealing with points, we will use <span class="math inline">\(K\)</span>-nn weights, which take the <span class="math inline">\(k\)</span> nearest neighbors of each observation as neighbors and assign a value of one, assigning everyone else a zero. We will use <span class="math inline">\(k=50\)</span> to get a good degree of variation and sensible results.</p>
<div class="sourceCode" id="cb225"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb225-1"><a href="spatialecon.html#cb225-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create knn list of each house</span></span>
<span id="cb225-2"><a href="spatialecon.html#cb225-2" aria-hidden="true" tabindex="-1"></a>hnn <span class="ot">&lt;-</span> db <span class="sc">%&gt;%</span></span>
<span id="cb225-3"><a href="spatialecon.html#cb225-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_coordinates</span>() <span class="sc">%&gt;%</span></span>
<span id="cb225-4"><a href="spatialecon.html#cb225-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.matrix</span>() <span class="sc">%&gt;%</span></span>
<span id="cb225-5"><a href="spatialecon.html#cb225-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">knearneigh</span>(<span class="at">k =</span> <span class="dv">50</span>)</span>
<span id="cb225-6"><a href="spatialecon.html#cb225-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Create nb object</span></span>
<span id="cb225-7"><a href="spatialecon.html#cb225-7" aria-hidden="true" tabindex="-1"></a>hnb <span class="ot">&lt;-</span> <span class="fu">knn2nb</span>(hnn)</span>
<span id="cb225-8"><a href="spatialecon.html#cb225-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Create spatial weights matrix (note it row-standardizes by default)</span></span>
<span id="cb225-9"><a href="spatialecon.html#cb225-9" aria-hidden="true" tabindex="-1"></a>hknn <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(hnb)</span></code></pre></div>
<p>We can inspect the weights created by simply typing the name of the object:</p>
<div class="sourceCode" id="cb226"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb226-1"><a href="spatialecon.html#cb226-1" aria-hidden="true" tabindex="-1"></a>hknn</span></code></pre></div>
<pre><code>## Characteristics of weights list object:
## Neighbour list object:
## Number of regions: 6110 
## Number of nonzero links: 305500 
## Percentage nonzero weights: 0.8183306 
## Average number of links: 50 
## Non-symmetric neighbours list
## 
## Weights style: W 
## Weights constants summary:
##      n       nn   S0       S1       S2
## W 6110 37332100 6110 220.5032 24924.44</code></pre>
<p><strong>Exogenous spatial effects</strong></p>
<p>Let us come back to the house price example we have been working with. So far, we have hypothesized that the price of an AirBnb property in San Diego can be explained using information about its own characteristics, and the neighbourhood it belongs to. However, we can hypothesise that the price of a house is also affected by the characteristics of the houses surrounding it. Considering it as a proxy for larger and more luxurious houses, we will use the number of bathrooms of neighboring houses as an additional explanatory variable. This represents the most straightforward way to introduce spatial dependence in a regression, by considering not only a given explanatory variable, but also its spatial lag.</p>
<p>In our example case, in addition to including the number of bathrooms of the property, we will include its spatial lag. In other words, we will be saying that it is not only the number of bathrooms in a house but also that of the surrounding properties that helps explain the final price at which a house is advertised for. Mathematically, this implies estimating the following model:</p>
<p><span class="math display">\[
\log(P_i) = \alpha + \beta_1 Acc_i + \beta_2 Bath_i + \beta_3 Bedr_i + \beta_4 Beds_i+ \beta_5 Bath_{lag-i} + \epsilon_i
\]</span></p>
<p>Let us first compute the spatial lag of <code>bathrooms</code>:</p>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb228-1"><a href="spatialecon.html#cb228-1" aria-hidden="true" tabindex="-1"></a>db<span class="sc">$</span>w_bathrooms <span class="ot">&lt;-</span> <span class="fu">lag.listw</span>(hknn, db<span class="sc">$</span>bathrooms)</span></code></pre></div>
<p>And then we can include it in our previous specification. Note that we apply the log to the lag, not the reverse:</p>
<div class="sourceCode" id="cb229"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb229-1"><a href="spatialecon.html#cb229-1" aria-hidden="true" tabindex="-1"></a>m5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb229-2"><a href="spatialecon.html#cb229-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">&#39;log_price ~ accommodates + bedrooms + beds + bathrooms + w_bathrooms&#39;</span>,</span>
<span id="cb229-3"><a href="spatialecon.html#cb229-3" aria-hidden="true" tabindex="-1"></a>  db</span>
<span id="cb229-4"><a href="spatialecon.html#cb229-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb229-5"><a href="spatialecon.html#cb229-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb229-6"><a href="spatialecon.html#cb229-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m5)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = &quot;log_price ~ accommodates + bedrooms + beds + bathrooms + w_bathrooms&quot;, 
##     data = db)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.8869 -0.3243 -0.0206  0.2931  3.5132 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   3.579448   0.032337 110.692   &lt;2e-16 ***
## accommodates  0.173226   0.005233  33.100   &lt;2e-16 ***
## bedrooms      0.103116   0.012327   8.365   &lt;2e-16 ***
## beds         -0.075071   0.007787  -9.641   &lt;2e-16 ***
## bathrooms     0.117268   0.012507   9.376   &lt;2e-16 ***
## w_bathrooms   0.353021   0.023572  14.976   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.5271 on 6104 degrees of freedom
## Multiple R-squared:  0.574,  Adjusted R-squared:  0.5736 
## F-statistic:  1645 on 5 and 6104 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>As we can see, the lag is not only significative and positive, but its effect seems to be even larger that that of the property itself. Taken literally, this implies that the average number of bathrooms in AirBnb’s nearby has a larger effect on the final price of a given AirBnb than its own number of bathrooms. There are several ways to interpret this. One is that, if we take the spatial lag of bathrooms, as we said above, to be a proxy for the types of houses surrounding a property, this is probably a better predictor of how wealthy an area is than the number of bathrooms of a single property, which is more variable. If we also assume that the area where an AirBnb is located has a bigger effect on price than the number of bathrooms, we can start seeing an answer to the apparent puzzle.</p>
<p><strong>A note on more advanced spatial regression</strong></p>
<p>Introducing a spatial lag of an explanatory variable, as we have just seen, is the most straightforward way of incorporating the notion of spatial dependence in a linear regression framework. It does not require additional changes, it can be estimated with OLS, and the interpretation is rather similar to interpreting non-spatial variables. The field of spatial econometrics however is a much broader one and has produced over the last decades many techniques to deal with spatial effects and spatial dependence in different ways. Although this might be an over simplification, one can say that most of such efforts for the case of a single cross-section are focused on two main variations: the spatial lag and the spatial error model. Both are similar to the case we have seen in that they are based on the introduction of a spatial lag, but they differ in the component of the model they modify and affect.</p>
<p>The spatial lag model introduces a spatial lag of the <em>dependent</em> variable. In the example we have covered, this would translate into:</p>
<p><span class="math display">\[
\log(P_i) = \alpha + \rho \log(P_i) + \beta_1 Acc_i + \beta_2 Bath_i + \beta_3 Bedr_i + \beta_4 Beds_i + \epsilon_i
\]</span></p>
<p>Although it might not seem very different from the previous equation, this model violates the exogeneity assumption, crucial for OLS to work.</p>
<p>Equally, the spatial error model includes a spatial lag in the <em>error</em> term of the equation:</p>
<p><span class="math display">\[
\log(P_i) = \alpha + \beta_1 Acc_i + \beta_2 Bath_i + \beta_3 Bedr_i + \beta_4 Beds_i + u_i
\]</span></p>
<p><span class="math display">\[
u_i = u_{lag-i} + \epsilon_i
\]</span></p>
<p>Again, although similar, one can show this specification violates the assumptions about the error term in a classical OLS model.</p>
<p>Both the spatial lag and error model violate some of the assumptions on which OLS relies and thus render the technique unusable. Much of the efforts have thus focused on coming up with alternative methodologies that allow unbiased, robust, and efficient estimation of such models. A survey of those is beyond the scope of this note, but the interested reader is referred to <span class="citation"><a href="references.html#ref-anselin1988spatial" role="doc-biblioref">Anselin</a> (<a href="references.html#ref-anselin1988spatial" role="doc-biblioref">1988</a>)</span>, <span class="citation"><a href="references.html#ref-anselin2003spatial" role="doc-biblioref">Anselin</a> (<a href="references.html#ref-anselin2003spatial" role="doc-biblioref">2003</a>)</span>, and <span class="citation"><a href="references.html#ref-anselin2014modern" role="doc-biblioref">Anselin and Rey</a> (<a href="references.html#ref-anselin2014modern" role="doc-biblioref">2014</a>)</span> for further reference.</p>
</div>
<div id="predicting-house-prices" class="section level2" number="6.7">
<h2><span class="header-section-number">6.7</span> Predicting house prices</h2>
<p>So far, we have seen how to exploit the output of a regression model to evaluate the role different variables play in explaining another one of interest. However, once fit, a model can also be used to obtain predictions of the dependent variable given a new set of values for the explanatory variables. We will finish this session by dipping our toes in predicting with linear models.</p>
<p>The core idea is that once you have estimates for the way in which the explanatory variables can be combined to explain the dependent one, you can plug new values on the explanatory side of the model and combine them following the model estimates to obtain predictions. In the example we have worked with, you can imagine this application would be useful to obtain valuations of a house, given we know its characteristics.</p>
<p>Conceptually, predicting in linear regression models involves using the estimates of the parameters to obtain a value for the dependent variable:</p>
<p><span class="math display">\[
\bar{\log(P_i)} = \bar{\alpha} + \bar{\beta_1} Acc_i^* + \bar{\beta_2 Bath_i^*} + \bar{\beta_3} Bedr_i^* + \bar{\beta_4} Beds_i^*
\]</span>
where <span class="math inline">\(\bar{\log{P_i}}\)</span> is our predicted value, and we include the <span class="math inline">\(\bar{}\)</span> sign to note that it is our estimate obtained from fitting the model. We use the <span class="math inline">\(^*\)</span> sign to note that those can be new values for the explanatory variables, not necessarily those used to fit the model.</p>
<p>Technically speaking, prediction in linear models is relatively streamlined in R. Suppose we are given data for a new house which is to be put on the AirBnb platform. We know it accommodates four people, and has two bedrooms, three beds, and one bathroom. We also know that the surrounding properties have, on average, 1.5 bathrooms. Let us record the data first:</p>
<div class="sourceCode" id="cb231"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb231-1"><a href="spatialecon.html#cb231-1" aria-hidden="true" tabindex="-1"></a>new.house <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb231-2"><a href="spatialecon.html#cb231-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">accommodates =</span> <span class="dv">4</span>, </span>
<span id="cb231-3"><a href="spatialecon.html#cb231-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">bedrooms =</span> <span class="dv">2</span>,</span>
<span id="cb231-4"><a href="spatialecon.html#cb231-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">beds =</span> <span class="dv">3</span>,</span>
<span id="cb231-5"><a href="spatialecon.html#cb231-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">bathrooms =</span> <span class="dv">1</span>,</span>
<span id="cb231-6"><a href="spatialecon.html#cb231-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">w_bathrooms =</span> <span class="fl">1.5</span></span>
<span id="cb231-7"><a href="spatialecon.html#cb231-7" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<p>To obtain the prediction for its price, we can use the <code>predict</code> method:</p>
<div class="sourceCode" id="cb232"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb232-1"><a href="spatialecon.html#cb232-1" aria-hidden="true" tabindex="-1"></a>new.price <span class="ot">&lt;-</span> <span class="fu">predict</span>(m5, new.house)</span>
<span id="cb232-2"><a href="spatialecon.html#cb232-2" aria-hidden="true" tabindex="-1"></a>new.price</span></code></pre></div>
<pre><code>##        1 
## 4.900168</code></pre>
<p>Now remember we were using the log of the price as dependent variable. If we want to recover the actual price of the house, we need to take its exponent:</p>
<div class="sourceCode" id="cb234"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb234-1"><a href="spatialecon.html#cb234-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(new.price)</span></code></pre></div>
<pre><code>##        1 
## 134.3123</code></pre>
<p>According to our model, the house would be worth $134.3123448.</p>
<!-- #region -->
</div>
<div id="questions-2" class="section level2" number="6.8">
<h2><span class="header-section-number">6.8</span> Questions</h2>
<p>We will be using again the Madrid AirBnb dataset:
<!-- #endregion --></p>
<div class="sourceCode" id="cb236"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb236-1"><a href="spatialecon.html#cb236-1" aria-hidden="true" tabindex="-1"></a>mad_abb <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">&#39;./data/assignment_1_madrid/madrid_abb.gpkg&#39;</span>)</span></code></pre></div>
<pre><code>## Reading layer `madrid_abb&#39; from data source `/home/rstudio/work/Dropbox/Francisco/uol/teaching/envs453/202122/san/data/assignment_1_madrid/madrid_abb.gpkg&#39; using driver `GPKG&#39;
## Simple feature collection with 18399 features and 16 fields
## geometry type:  POINT
## dimension:      XY
## bbox:           xmin: -3.86391 ymin: 40.33243 xmax: -3.556 ymax: 40.56274
## geographic CRS: WGS 84</code></pre>
<div class="sourceCode" id="cb238"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb238-1"><a href="spatialecon.html#cb238-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(mad_abb)</span></code></pre></div>
<pre><code>##  [1] &quot;price&quot;           &quot;price_usd&quot;       &quot;log1p_price_usd&quot; &quot;accommodates&quot;   
##  [5] &quot;bathrooms_text&quot;  &quot;bathrooms&quot;       &quot;bedrooms&quot;        &quot;beds&quot;           
##  [9] &quot;neighbourhood&quot;   &quot;room_type&quot;       &quot;property_type&quot;   &quot;WiFi&quot;           
## [13] &quot;Coffee&quot;          &quot;Gym&quot;             &quot;Parking&quot;         &quot;km_to_retiro&quot;   
## [17] &quot;geom&quot;</code></pre>
<!-- #region -->
<p>In addition to those we have already seen, the columns to use here are:</p>
<ul>
<li><code>neighbourhood</code>: a column with the name of the neighbourhood in which the property is located</li>
</ul>
<p>With this at hand, answer the following questions:</p>
<ol style="list-style-type: decimal">
<li>Fit a baseline model with only property characteristics explaining the log of price</li>
</ol>
<p><span class="math display">\[
\log(P_i) = \alpha + \beta_1 Acc_i + \beta_2 Bath_i + \beta_3 Bedr_i + \beta_4 Beds_i + \epsilon_i
\]</span></p>
<ol start="2" style="list-style-type: decimal">
<li>Augment the model with fixed effects at the neighbourhood level</li>
</ol>
<p><span class="math display">\[
\log(P_i) = \alpha_r + \beta_1 Acc_i + \beta_2 Bath_i + \beta_3 Bedr_i + \beta_4 Beds_i + \epsilon_i
\]</span></p>
<ol start="3" style="list-style-type: decimal">
<li>[Optional] Augment the model with spatial regimes at the neighbourhood level:</li>
</ol>
<p><span class="math display">\[
\log(P_i) = \alpha_r + \beta_{r1} Acc_i + \beta_{r2} Bath_i + \beta_{r3} Bedr_i + \beta_{r4} Beds_i + \epsilon_{ri}
\]</span></p>
<ol start="4" style="list-style-type: decimal">
<li>Fit a model that augments the baseline in 1. with the spatial lag of a variable you consider interesting. Motivate this choice. Note that to complete this, you will need to also generate a spatial weights matrix.</li>
</ol>
<p>In each instance, provide a brief interpretation (no more thana few lines for each) that demonstrates your understanding of theunderlying concepts behind your approach.
<!-- #endregion --></p>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="21">
<li id="fn21"><p><strong>EXAMPLE</strong> Assume that new houses tend to be built more often in areas with low deprivation. If that is the case, then <span class="math inline">\(NEW\)</span> and <span class="math inline">\(IMD\)</span> will be correlated with each other (as well as with the price of a house, as we are hypothesizing in this case). If we calculate a simple correlation between <span class="math inline">\(P\)</span> and <span class="math inline">\(IMD\)</span>, the coefficient will represent the degree of association between both variables, but it will also include some of the association between <span class="math inline">\(IMD\)</span> and <span class="math inline">\(NEW\)</span>. That is, part of the obtained correlation coefficient will be due not to the fact that higher prices tend to be found in areas with low IMD, but to the fact that new houses tend to be more expensive. This is because (in this example) new houses tend to be built in areas with low deprivation and simple bivariate correlation cannot account for that.<a href="spatialecon.html#fnref21" class="footnote-back">↩︎</a></p></li>
<li id="fn22"><p>Keep in mind that regression is no magic. We are only discounting the effect of other confounding factors that we include in the model, not of <em>all</em> potentially confounding factors.<a href="spatialecon.html#fnref22" class="footnote-back">↩︎</a></p></li>
<li id="fn23"><p>If you need to refresh your knowledge on spatial weight matrices, check <a href="https://darribas.org/gds_course/content/bE/concepts_E.html">Block E</a> of <span class="citation"><a href="references.html#ref-darribas_gds_course" role="doc-biblioref">Dani Arribas-Bel</a> (<a href="references.html#ref-darribas_gds_course" role="doc-biblioref">2019</a>)</span> or <a href="https://geographicdata.science/book/notebooks/04_spatial_weights.html">Chapter 4</a> of <span class="citation"><a href="references.html#ref-reyABwolf" role="doc-biblioref">Rey, Arribas-Bel, and Wolf</a> (<a href="references.html#ref-reyABwolf" role="doc-biblioref">forthcoming</a>)</span>.<a href="spatialecon.html#fnref23" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="flows.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="mlm1.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": null,
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["spatial_analysis_notes.pdf", "spatial_analysis_notes.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
